DimensionDev/Maskbook

package.json
src/background-service.ts
src/components/InjectedComponents/DecryptedPost.tsx
src/components/InjectedComponents/PostInspector.tsx
src/extension/background-script/CryptoServices/decryptFrom.ts
src/extension/options-page/Welcome/index.tsx
src/extension/service.ts
src/network/gun/version.2/post.ts
src/social-network-provider/facebook.com/UI/injectPostInspector.tsx
src/social-network-provider/facebook.com/Worker/fetchPostContent.ts
src/social-network-provider/facebook.com/Worker/fetchProfile.ts
src/social-network/defaults/injectPostInspector.tsx
src/utils/messages.ts
src/utils/type-transform/Serialization.ts
tsconfig.json
yarn.lock

- update @holoflows/kit
- Rewrite MessageCenter with new built-in serialization
- Rewrite MessageCenter related code with new `off()` method
- Use new AutomatedTabTask option
- Use AsyncCall new `sendLocalStack` and `preferLocalImplementation` flag
- Use AsyncGeneratorCall to rewrite `decryptFrom` to provide a more suitable call cycle in UI
- In previous version AutomatedTabTask can only run once, after upgraded, this should be fixed.

Update @holoflows/kit and rewrite some functions with new @kit features

---

config-overrides/index.js
public/index.html

This is based on t4, `feat: use manifest generator to generate manifests `

fix: bring copy polyfills back

---

src/components/shared-settings/createSettings.tsx
src/extension/injected-script/addEventListener.ts
src/extension/service.ts
src/utils/components/AsyncComponent.tsx

This commit brings a regression on Firefox.
This reverts commit a5402a8456e1de0a882cbaf0560f6ce432cbb3f3.

fix: firefox regression (bring by "chore: reduce the use of `any`")

---

src/background-service.ts
src/components/Welcomes/1b1.tsx
src/components/Welcomes/Banner.tsx
src/extension/options-page/Welcome/index.tsx
src/utils/hooks/useValueRef.ts

This commit fixes:
+ repeatedly brings up scan-qr UI on iOS
+ try close options-page after setup on mobile geckoview and WKWebView

iOS: Fix QR scanning; try close options-page after setup

---

src/extension/popup-page/index.tsx
src/social-network-provider/facebook.com/ui-provider.ts
src/social-network-provider/popup-page/index.ts
src/social-network-provider/twitter.com/ui/index.ts
src/social-network/ui.ts

This PR (together with its parent #291 #290) introduces real-time identity updating and selecting from the popup, and updates failing reason to be more accurate.
If it's not a site that we care about, then the selector won't show up at all.

feat: popup identity selector

---

tsconfig.json

ES2018 support status:
Chrome all green. Firefox and iOS does not support some RegExp features.
RegExp related features can not be transformed by TypeScript compiler. So it's safe to upgrade to ES2018
ES2019 support status:
All platforms green.

Bump target version from es2017 to es2019

---

src/components/InjectedComponents/AdditionalPostContent.tsx
src/components/InjectedComponents/PersonKnown.tsx
src/social-network-provider/facebook.com/UI/injectKnownIdentity.tsx
src/social-network-provider/twitter.com/ui/inject.tsx
src/social-network-provider/twitter.com/ui/injectKnownIdentity.tsx
src/social-network-provider/twitter.com/utils/selector.ts

+ Refactor `PersonKnown` and move it to `InjectedCompone/` folder;
+ Refactor `querySelector()` make it support specific `singleMode`;
+ Inject `PersonKnown` component into twitter profile page;
+ Refine vertical alignment of `AdditionalContent` component;
Related Issues:
+ #469 
Screenshots:

Add 'Seen by Maskbook database' into twitter profile page

---

config-overrides/index.js
config-overrides/manifest.overrides.js

The ID will be `jkoeaghipilijlahjplgbfiocjhldnap`. Same as the one of chrome store.
? what about firefox?
close #28

chore: provide consistent extension id when install from source

---

src/components/InjectedComponents/ImmersiveSetup/SetupStepper.tsx

This fixes if a user changes their id at the first step, we still show the previously auto-detected one when setting up bio.
#545

fix: immersive setup not respect user input

---

package.json
yarn.lock

[Here](https://material-ui.com/zh/getting-started/faq/#i-have-several-instances-of-styles-on-the-page) and [here](https://stackoverflow.com/a/58435846) indicates `@material-ui/styles` should possibly not be a resolved dependency and should not appear in dependencies.
? But I think it's a bit magic if we can import a package without specifying it as a dependency.

fix: material-ui styles duplicated dependency and pure lock files

---

src/social-network-provider/twitter.com/ui/custom.ts

Get background color API may return `''` during app running. So use a default background color may cause flash it with theme color. Remove the background color and let it fail silently.
close #623

Remove default background color

---

src/components/InjectedComponents/AdditionalPostBox.tsx
src/components/InjectedComponents/DecryptedPost.tsx
src/components/InjectedComponents/PostDialog.tsx
src/components/InjectedComponents/PostInspector.tsx
src/crypto/crypto-alpha-38.ts
src/crypto/crypto-alpha-39.ts
src/crypto/crypto-alpha-40.ts
src/extension/background-script/CryptoServices/decryptFrom.ts
src/extension/background-script/CryptoServices/encryptTo.ts
src/extension/background-script/CryptoServices/utils.ts
src/social-network/defaults/injectPostInspector.tsx
src/stories/Injections.tsx

This PR introduce a new mechanism: Typed Message.
In many IM protocol, there're more message types than the plain text. This PR enables Maskbook to construct typed message with metadata. With this mechanism, we can support message type like picture, files, audios, etc... Plugin can inject their data into the `meta` section.
Typed Message is a media-independent representation of a Maskbook message. The `parse` and `stringify` part can be different according to the payload version.
For example: In version -38, it will be constructed as `{"some_meta": "meta_1"}🧩Normal message`.
In future version, it can be constructed as some custom binary format.
```ts
export interface TypedMessageMetadata {
meta?: object
version: 1
}
export interface TypedMessageText extends TypedMessageMetadata {
type: …
```

feat: add new typed message

---

src/components/InjectedComponents/PostDialog.tsx

+ Fix #750 
+ Fix a UI bug
close #750

Early open option page if no wallet was imported

---

src/social-network-provider/facebook.com/UI/collectPosts.tsx
src/social-network-provider/twitter.com/utils/fetch.ts
src/social-network-provider/twitter.com/utils/url.ts

Twitter may delivery different image URLs according to network condition or user preferred configrations. Some of them are highly compressed which can not be decoded.
The URL of Twitter photo adhere [fixed formatting](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/entities-object#photo_format). We can get original photo with URL like `https://pbs.twimg.com/media/[id]?format=[jpg|png]&name=orig`.
- https://stackoverflow.com/questions/39108742/how-to-get-different-sized-media-twitter-api/39118748
close #773

Canonify image URL for Twitter

---

public/firefoxFix.js
src/social-network-provider/twitter.com/ui/fetch.ts

This PR fixs:
+ `getComputedStyle` not working when get background color of specific element
+ `dotAll` flag not supported in FF

Fix some firefox bugs

---

src/social-network-provider/twitter.com/ui/inject.tsx
src/social-network-provider/twitter.com/ui/injectPostInspector.tsx

The PR blocked by #475 due to the fact that subtle node changes will cause double injections of inspector component.
**ATTENTION: This PR includes code which alters network vendor's DOM tree. This may be violate our secure strategy**
close #749

Zip tweet payload

---

package.json

Solve the intermittently failing with “not enough memory” error.
+ https://blog.lysender.com/2019/08/jest-tests-failing-on-circleci-enomem-not-enough-memory/
+ https://github.com/zcorky/moment/issues/26

Run ci test cases in single tread mode

---

package.json
webpack.config.js

close #920
add a new flag `--reproducible-build`. default on for `build:firefox`

fix: remove git related info in firefox build close #920

---

package.json
yarn.lock

#1146
Move **puppeteer** packages to optional dependencies
```
yarn install --ignore-optional
```

chore: move puppeteer to optionalDependencies

---

src/plugins/Wallet/erc20/mainnet.json

see: https://etherscan.io/token/0xeb269732ab75a6fd61ea60b06fe994cd32a83549
The correct decimal of USDx is 18. right now the incorrect decimal is causing problems like -
(now w/ incorrect decimal) https://imgur.com/o3Fzpad
correct number https://imgur.com/VrV3ZrW

Fix USDx Decimal

---

.vscode/settings.json
src/database/Plugin/index.ts
src/database/Plugin/wrap-plugin-database.ts
src/database/Plugin/wrap-wallet-for-plugin.ts
src/extension/background-script/CryptoServices/utils.ts
src/plugins/Wallet/createRedPacketTransaction.ts
src/plugins/Wallet/gitcoin.ts

The new plugin db design:
*   give up the isomorphism to the Indexed DB (it's too complex)
*   give up the consistency guarantee by the transaction (reason: it's not possible to share a transaction in the external wallet format)
*   use a simpler & minimal API set that works like `localStorage`
*   MUST use tagged union to store the data
*   old plugin DB is deprecated. migrate in future

Plugin db (picked from #1331)

---

src/content-script.ts

close https://github.com/DimensionDev/Maskbook/issues/1483
content-script would be loaded in all case, content-script contains injected-script already: https://github.com/DimensionDev/Maskbook/commit/975febc10c035ef0015089b501b428f7d842d8ea#diff-075daa7a311f82142f0742717ab50b51R1
so I think we can just remove other injected-script load.

chore: remove duplicated injected script

---

src/extension/injected-script/addEventListener.ts
webpack.config.js

Fix the bug that there's no 'img payload' in firefox browser.

fix: img payload in firefox

---

src/plugins/RedPacket/UI/CreateRedPacketForm.tsx

It should show the total amount.

fix: show red packet total amount

---

src/extension/options-page/DashboardComponents/AbstractTab.tsx

It always displays a width broken tab indicator when opening its container at first time: https://github.com/mui-org/material-ui/issues/10465. According to https://github.com/mui-org/material-ui/pull/14638, to fix it just override its style.

fix: material-ui tab indicator width

---

packages/maskbook/src/plugins/FileService/define.tsx
packages/maskbook/src/plugins/Gitcoin/define.tsx
packages/maskbook/src/plugins/Polls/define.tsx
packages/maskbook/src/plugins/RedPacket/define.tsx
packages/maskbook/src/plugins/Storybook/define.tsx
packages/maskbook/src/plugins/Trader/define.tsx
packages/maskbook/src/plugins/Transak/define.tsx
packages/maskbook/src/plugins/Wallet/define.tsx
packages/maskbook/src/plugins/plugin.ts

> Maybe use a "beta: true" when registering plugin
one idea, add a `PluginStage` enum.
```ts
stage: PluginStage.Development // e.q: us election 2020 
stage: PluginStage.Internal // e.q: metadata inspector
stage: PluginStage.Beta // e.q: poll
stage: PluginStage.Production // e.q: red packet and file service
```
_Originally posted by @septs in https://github.com/DimensionDev/Maskbook/issues/1810#issuecomment-720209879_

feat: add plugin stage and scope

---

packages/maskbook/src/components/InjectedComponents/AutoPasteFailedDialog.tsx
packages/maskbook/src/components/InjectedComponents/CommentBox.tsx
packages/maskbook/src/social-network-provider/facebook.com/UI/collectPosts.tsx
packages/maskbook/src/utils/hooks/useQueryNavigatorPermission.ts

I have no idea if it really fixed. But at least on my machine, it works as the following table describes.
Picture decryption failure is not caused by DOM change so cc @guanbinrui (#1813 and #976)
cc @Tedko.
maybe close #1813
fix for #1909 already pushed to the master branch (display a download button and requiring the user to upload by themself.)
-   [x] Encrypt text
-   [x] Decrypt text
-   [x] Encrypt pic
-   [x] Decrypt pic
-   [x] Encrypt comment
-   [x] Decrypt comment
-   [x] Encrypt text
-   [x] Decrypt text
-   [x] Encrypt pic
-   [ ] Decrypt pic
-   [x] Encrypt comment
-   [x] Decrypt comment

fix: facebook support

---

scripts/SSRWorker.js
webpack.config.ts

Actually, I didn't fix it.
```
/home/jack/workspace/maskbook/node_modules/ts-node/src/index.ts:1
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/jack/workspace/maskbook/node_modules/@babel/runtime/helpers/esm/extends.js
at new NodeError (node:internal/errors:278:15)
at Module._extensions..js (node:internal/modules/cjs/loader:1119:13)
at Object.require.extensions.<computed> [as .js] (/home/jack/workspace/maskbook/node_modules/ts-node/src/index.ts:1032:44) {
code: 'ERR_REQUIRE_ESM'
}
```
Help wanted cc @septs @zhouhanseng @guanbinrui .
You can run SSR without webpack by
```shell
node scripts/SSRWorker.js packages/maskbook/src/extension/popup-page/index.tsx
```

fix: emotion throw window not found in ssr

---

packages/maskbook/src/extension/options-page/DashboardDialogs/Contact.tsx

fix: after delete contact background remains vaguely.

fix: delete contact vague bg

---

.circleci/config.yml
.github/workflows/e2e.yml

We must use NPM v7 in the future (#2007) and [it will be shipping with NodeJS 15.3.0](https://blog.npmjs.org/post/631877012766785536/release-v700). So upgrade to NodeJS 15.3.0 is a good choice.

Upgrade to nodejs to 15.3.0

---

package-lock.json

```
$ npm dedupe
added 16 packages, removed 47 packages, changed 59 packages, and audited 3883 packages in 5m
41 packages are looking for funding
run `npm fund` for details
11 vulnerabilities (10 low, 1 moderate)
To address issues that do not require attention, run:
npm audit fix
To address all issues possible (including breaking changes), run:
npm audit fix --force
Some issues need review, and may require choosing
a different dependency.
Run `npm audit` for details.
```

chore: npm dedupe

---

package-lock.json
package.json

Reverts DimensionDev/Maskbook#2166
this breaks *connect to metamask* for unknown reason and i don't have bandwidth for it currently

Revert "chore(deps): bump stream-browserify from 2.0.2 to 3.0.0"

---

packages/maskbook/src/components/QRScanner/ShapeDetectionPolyfill.ts
packages/maskbook/src/network/gun/index.ts
packages/maskbook/src/plugins/Polls/utils.ts
public/patches.js

cc @septs with this PR you don't need
```js
__webpack_public_path__ = browser.runtime.getURL('/')
```
anymore

fix: workaround for Chunk Load failed

---

packages/maskbook/src/_locales/en/messages.json
packages/maskbook/src/_locales/ja/messages.json
packages/maskbook/src/_locales/zh/messages.json
packages/maskbook/src/plugins/FileService/arweave/index.ts
packages/maskbook/src/plugins/FileService/components/Upload.tsx
packages/maskbook/src/plugins/FileService/components/Uploading.tsx
packages/maskbook/src/plugins/FileService/constants.ts

#2160 
We add a checkbox in upload page. If user check this option, the file link will be changed to acceleration link.
For users who can't reach the basic endpoint `https://arweave.net`, we can add the cache link for landing page in next iteration.
Test link (have fun): https://arweave.net/VzLiXPYJLyAmWoQbH05W5P5SOaqWesQCFg7a935iKYE#MrRBRMeAnB8EQBE4

feat: add CDN for the arweave file service

---

packages/maskbook/src/plugins/Wallet/services/wallet.ts

close #2258
Delete 'Persona Card' would delete the data of persona, wallet remains. So check the existence of wallet when restore.

fix: restore wallet if not exist

---

packages/maskbook/src/plugins/FileService/Preview.tsx
packages/maskbook/src/plugins/FileService/components/Uploading.tsx
packages/maskbook/src/plugins/FileService/constants.ts
packages/maskbook/src/plugins/FileService/database.ts
packages/maskbook/src/plugins/FileService/define.tsx
packages/maskbook/src/plugins/FileService/schema-v1.json
packages/maskbook/src/plugins/FileService/schema-v2.json
packages/maskbook/src/plugins/FileService/types.ts
packages/maskbook/src/stories/Plugin-FileService.tsx

Now FileService will emit v2 FileInfo so the older version of Mask Network needs to upgrade to see the content of v2.
I didn't test it. @septs 
It's a necessary part of #2176 . @developerfred may want to take a look about this PR

feat!: upgrade version of file service metadata

---

.husky/pre-commit
.prettierignore

```
septs@CBDesktop02 ~/Projects/DimensionDev/Maskbook (feature/integrate-stego-js-v2) $ git commit -m 'chore: update lock'
.husky/pre-commit: line 4: lint-staged: command not found
husky - pre-commit hook exited with code 127 (error)
```
```
septs@CBDesktop02 ~/Projects/DimensionDev/Maskbook (feature/integrate-stego-js-v2*) $ git commit -m 'chore: update lock'
ℹ No staged files match any configured task.
> maskbook@1.22.3 locale-kit
> ts-node scripts/locale-kit.ts "--sync-key"
Scanned 0 unused keys, run `npm run locale-kit -- --remove-unused-keys` to remove them.
Unsynced [] locales
Synced keys
$ git add packages/maskbook/src/_locales # cwd:
Checking formatting...
[warn] packages/storybook-shared/index.d.ts
[warn] packages/storybook-shared/index.js
[warn] …
```

fix: husky configuration

---

packages/maskbook/src/plugins/ITO/UI/ClaimDialog.tsx

Remove the unacceptable decimal for the calculating result of swap token when slide.
the unacceptable decimal would cause error when approve token:
```
console.log(tAmount.multipliedBy(ratio)) 
console.log(tAmount.multipliedBy(ratio).dp(0)) 
// 79388027.0000000000000000000000004
// 79388027
```

fix: rm swap amount decimal when slide

---

packages/maskbook/src/extension/options-page/DashboardComponents/FixedTokenList.tsx
packages/maskbook/src/extension/options-page/DashboardDialogs/Wallet.tsx
packages/maskbook/src/plugins/Ethereum/UI/SelectERC20TokenDialog.tsx
packages/maskbook/src/plugins/Ethereum/UI/SelectTokenDialog.tsx
packages/maskbook/src/plugins/Ethereum/messages.ts
packages/maskbook/src/plugins/Gitcoin/UI/DonateDialog.tsx
packages/maskbook/src/plugins/Gitcoin/apis/index.ts
packages/maskbook/src/plugins/ITO/UI/ClaimDialog.tsx
packages/maskbook/src/plugins/ITO/UI/ExchangeTokenPanel.tsx
packages/maskbook/src/plugins/RedPacket/UI/RedPacketForm.tsx
packages/maskbook/src/plugins/Trader/UI/trader/Trader.tsx
packages/maskbook/src/plugins/Wallet/define.tsx
packages/maskbook/src/plugins/Wallet/messages.ts
packages/maskbook/src/web3/UI/EthereumERC20TokenApprovedBoundary.tsx
packages/maskbook/src/web3/UI/EthereumWalletConnectedBoundary.tsx

```ts
const [, setOpenSelectERC20TokenDialog] = useRemoteControlledDialog(WalletMessages.events.selectERC20TokenDialogUpdated, useCallback((ev) => {
if (ev.open || !ev.token) return
// the user has already selected a token from the built-in token list.
}, []))
const onTokenChipClick = useCallback(() => {
// the user clicked the token selector chip
}, [])
```

refactor: invoke SelectERC20TokenDialog by message center

---

packages/maskbook/package.json
packages/maskbook/src/extension/background-script/EthereumServices/providers/MetaMask.ts
packages/maskbook/src/plugins/ITO/UI/ITO.tsx
packages/maskbook/src/plugins/ITO/UI/PostInspector.tsx
pnpm-lock.yaml

Issue: https://github.com/MetaMask/metamask-extension/issues/10368
`inpage-provider` pkg workaround: https://github.com/DimensionDev/extension-provider/pull/5
Fix the issue that when metamask has locked, but ITO still shown, which leads to errors in the further using:
Now with https://github.com/DimensionDev/extension-provider/pull/5, we can detect the lock event. unlock event still can't be detected, but it's almost okay since ITO displays as below image as soon as lock happens(whether manually or automatically lock), click the button to connect the metamask and the following unlock event can be detected, because `Services.Ethereum.connectMetaMask()` creates a new provider first:

fix: mm locked state workaround

---

packages/maskbook/src/plugins/NFT/utils.ts
packages/maskbook/src/utils/flags.ts

fix: when parsing an url string without a valid protocol, prepend a 'https://'

---

packages/maskbook/src/plugins/Trader/trader/0x/useTradeComputed.ts
packages/maskbook/src/plugins/Trader/types/0x.ts

close https://github.com/DimensionDev/Maskbook/issues/2394
close https://github.com/DimensionDev/Maskbook/issues/2392
Try DAI => MUSE, when input 0.1 DAI, the price is 2.044 * 10 ** -15, when input 10 the price is 2.044 * 10 ** -13, and whatever you input 0.1 1 or 10, buyAmount is always 2044, this is obviously wrong. 
I find that `res.buyTokenToEthRate` and `res.sellTokenToEthRate` is basically a fixed number, and using it can calculate out the correct price and buyAmount which is identify as other providers.

fix: 0x api data wrong

---

packages/maskbook/src/plugins/ITO/UI/ITO.tsx

Showing disabled button with hint when ITO was expired or out of stock, otherwise some users who didn't get the chance to buy would not willing to accept the fact and complain or even censure revengefully.

chore: ito show button even sold out or expired

---

packages/maskbook/src/plugins/Wallet/UI/WalletConnectQRCodeDialog/QRCodeModel.tsx

After modification, the QR code looks as following:
1. On Chrome:
2. On Mobile:

fix: WalletConnect QR code too large on mobile

---

packages/maskbook/src/plugins/RedPacket/constants.ts

The old redpacket ropsten address `0x26760783c12181efa3c435aee4ae686c53bdddbb` is obviously wrong that it is as same as mainnet.
I deploy on ropsten again using the current mainnet [contract](https://etherscan.io/tx/0xd940a784416feabbca0cb20c81ed9e1d762d39f62d28e619cc5b4900ca25975b)

fix: redpacket ropsten address

---

packages/maskbook/src/social-network/ui.ts
packages/maskbook/src/utils/flags.ts

The injected toolbar breaks Twitter's mobile layout, let's hide it before we have a compatible design on mobile.

chore: hide injected toolbar on mobile, enable trader on mobile

---

packages/shared/package.json
packages/shared/src/state/known.ts
packages/shared/src/state/state.ts
packages/shared/src/state/use-site.ts
pnpm-lock.yaml

close #1884 
This is a draft. You can see the API shape (RFC cc @guanbinrui @septs @zhouhanseng @nuanyang233) on the usage site at packages/shared/src/state/use-site.ts
The new API is generally compatible with the current API shape but
- React concurrent-mode safe (version field, useMutableSource)
- Allow split the API model so isolate mode dashboard can use those infras
- Add non-persistent storage (see #1884)

feat: new api for cross-env settings

---

.gitignore

Avoid uploads by third-party contributors the non pnpm lock file

fix: disallow other package manager lock-file

---

packages/maskbook/src/extension/options-page/DashboardComponents/Drawer.tsx

The drawer header already has `background-color: var(--drawerHeader);` style declared.

fix: remove unnecessary inline style for drawer header

---

packages/maskbook/src/extension/options-page/DashboardDialogs/Wallet.tsx

update some style as well after communicating with @xiazhiming 
closes #2826
| | |
|--|--|
| ![image](https://user-images.githubusercontent.com/1141198/114827105-dcfec100-9dfa-11eb-965f-c5d837f131d6.png) | ![image](https://user-images.githubusercontent.com/1141198/114827134-e720bf80-9dfa-11eb-97ca-c62d04b1da64.png) |
| ![image](https://user-images.githubusercontent.com/1141198/114827059-cfe1d200-9dfa-11eb-9a71-fed4f43e2240.png) | ![image](https://user-images.githubusercontent.com/1141198/114827172-eee06400-9dfa-11eb-84cd-638419435123.png) |

fix: hint info in wallet creation dialog being covered by the activated confirm button

---

packages/maskbook/src/social-network/PostInfo.ts

fix: fails to found PostInfo from @dimensiondev/mask-plugin-infra

---

packages/maskbook/src/components/InjectedComponents/ToolboxHint.tsx
packages/maskbook/src/social-network-adaptor/twitter.com/customization/custom.ts

refs:
- https://github.com/mui-org/material-ui/commit/1f267fabe0dcf8a816b5ddbd89b1cf9dd2d6435a
- https://github.com/mui-org/material-ui/blob/58c7e708a419bc8895774e964b8ef00b55d045ac/packages/material-ui/src/Paper/Paper.js#L72-L75

fix: material-ui@5-alpha.29 makes paper look lighter on dark mode

---

packages/maskbook/src/plugins/Snapshot/UI/LoadingCard.tsx
packages/maskbook/src/plugins/Snapshot/UI/LoadingFailCard.tsx
packages/maskbook/src/plugins/Snapshot/UI/PostInspector.tsx
packages/maskbook/src/plugins/Snapshot/UI/ProgressTab.tsx
packages/maskbook/src/plugins/Snapshot/UI/ProposalTab.tsx
packages/maskbook/src/plugins/Snapshot/UI/ResultCard.tsx
packages/maskbook/src/plugins/Snapshot/UI/Snapshot.tsx
packages/maskbook/src/plugins/Snapshot/UI/Vote.tsx
packages/maskbook/src/plugins/Snapshot/UI/VotesCard.tsx
packages/maskbook/src/plugins/Snapshot/UI/VotingCard.tsx
packages/maskbook/src/plugins/Snapshot/apis/index.ts
packages/maskbook/src/plugins/Snapshot/define.tsx
packages/maskbook/src/plugins/Snapshot/hooks/useProposal.ts
packages/maskbook/src/plugins/Snapshot/hooks/useResults.ts
packages/maskbook/src/plugins/Snapshot/hooks/useRetry.ts
packages/maskbook/src/plugins/Snapshot/hooks/useVotes.ts
packages/maskbook/src/plugins/Snapshot/types.ts

Revamp suspense related. Display loading UI for single card rather than whole plugin when only single card is loading.
From:
to:

chore: revamp snapshot

---

packages/shared/src/utils/parseURL.ts

url like `https://…a.com`. see alexcorvi/anchorme.js/issues/109
closes #3185

fix: some invalid url wrongly detected by anchorme

---

packages/maskbook/src/social-network-adaptor/twitter.com/utils/selector.ts

theme color got updated according to `a[href=/compose/tweet]`.
When retweet menu which also contains an `a[href=/compose/tweet]`,
pop up, theme color got updated by the menu wrongly.
fixes: #3168

fix: theme color got updated according to wrong element

---

packages/icons/package.json
packages/icons/utils/index.tsx
pnpm-lock.yaml

closes #3153 
This PR do the following changes:
Before:
```ts
export function createIcon(
name: string,
svg: React.ReactNode,
viewBox?: string,
defaultSize?: Size
): typeof SvgIcon
```
After:
```ts
export function createIcon(
name: string,
svg: JSX.Element | ((theme: Theme) => JSX.Element),
viewBox?: string,
defaultSize?: Size
): typeof SvgIcon
export function createPaletteAwareIcon(
name: string,
light: JSX.Element,
dark: JSX.Element,
viewBox?: string,
defaultSize?: Size
): typeof SvgIcon
```

feat: support theme access in icons package close #3153

---

packages/maskbook/src/UIRoot.tsx
packages/maskbook/src/extension/background-script/HelperService.ts
packages/maskbook/src/extension/options-page/Route.ts
packages/maskbook/src/extension/options-page/index.tsx
packages/maskbook/src/extension/popups/RequestPermission/RequestPermission.tsx
packages/maskbook/src/extension/popups/RequestPermission/index.tsx
packages/maskbook/src/extension/popups/RequestPermission/utils.ts
packages/maskbook/src/extension/popups/index.tsx
packages/maskbook/src/extension/popups/render.tsx

related #3131 (cc @manishoo)
This PR adds a new service method `Services.Helper.requestBrowserPermission` has the same function as `browser.permission.request` but works in content script.
In Chrome, it is OK to call `browser.permission.request` directly in the background.
In Firefox, it will create a new popup window that can request permission in that context.
UI is reused from the unused GitCoin plugin.

feat: add requestBrowserPermission

---

packages/maskbook/src/_locales/en/messages.json
packages/maskbook/src/_locales/ja/messages.json
packages/maskbook/src/_locales/ko/messages.json
packages/maskbook/src/_locales/zh/messages.json
packages/maskbook/src/plugins/ITO/UI/ITO.tsx

Disable the claim button after receive its relative tx hash and before network update.

chore: ito tx hash disable button

---

packages/maskbook/src/social-network-adaptor/twitter.com/utils/fetch.ts

fix: postInspector fails to find the original tweet if there is a retweet of it

---

.github/workflows/build.yml
.github/workflows/e2e.yml
.github/workflows/linters.yml
packages/dashboard/src/API.tsx
packages/maskbook/src/database/migrate/fix.qr.private.key.bug.ts
packages/maskbook/src/database/tasks/clean-avatar-profile.ts
packages/maskbook/tsconfig.json
packages/plugin-infra/tsconfig.json
packages/plugins/example/src/Components.tsx
packages/plugins/example/tsconfig.json
packages/shared/tsconfig.json
packages/web3-shared/tsconfig.json

Before (on commit c40cc5e8f62ccc30c74d58b673d9176174fb0cc3 which does not have a dependency changes):
- Type check spent 1m35s (2m52s in total) to run
- Webpack spent 5m52s (7m1s in total) to run
After (when cache hits):
- Type check spent 14s (3m23s in total) to run
- Webpack spent 2m22s (6m31s in total) to run
Note: I only optimized for Github Actions. Not for CircleCI or Netlify (maybe future)

ci: speedup ci by share build caches between build

---

package.json
packages/dashboard/src/index.tsx
packages/external-plugin-previewer/src/DOMImpl.tsx
packages/maskbook/src/env.d.ts
packages/maskbook/src/extension/dashboard/index.tsx
packages/maskbook/src/extension/popups/render.tsx
packages/shared/src/ShadowRoot/createReactRootShadowed.tsx
packages/shared/src/react/createGlobalState.ts
packages/shared/src/react/createResource.ts
packages/web3-shared/src/env.d.ts
pnpm-lock.yaml

- feat: upgrade to react 18
- chore: drop support for legacy render
closes #3312

feat: upgrade to react 18

---

packages/maskbook/src/components/DataSource/usePostInfo.ts
packages/maskbook/src/components/InjectedComponents/DecryptedPost/DecryptedPost.tsx
packages/maskbook/src/components/InjectedComponents/DecryptedPost/DecryptedPostDebug.tsx
packages/maskbook/src/components/InjectedComponents/PostComments.tsx
packages/maskbook/src/components/InjectedComponents/PostInspector.tsx
packages/maskbook/src/components/InjectedComponents/PostReplacer.tsx
packages/maskbook/src/plugins/Collectible/define.tsx
packages/maskbook/src/plugins/Gitcoin/define.tsx
packages/maskbook/src/plugins/NFT/define.tsx
packages/maskbook/src/plugins/RedPacket/UI/RedPacketInPost.tsx
packages/maskbook/src/plugins/Snapshot/define.tsx
packages/maskbook/src/plugins/VCent/define.tsx
packages/maskbook/src/plugins/dHEDGE/define.tsx
packages/maskbook/src/social-network/defaults/inject/CommentBox.tsx
packages/plugin-infra/src/PostInfo.ts

This PR allows items on `PostInfo` can be reference-discoverable.

refactor: let usePostInfoDetails support reference

---

packages/maskbook/src/extension/background-script/EthereumServices/send.ts
packages/maskbook/src/extension/options-page/DashboardComponents/ProfileBox.tsx
packages/maskbook/src/plugins/Wallet/settings.ts
packages/maskbook/src/social-network/ui.ts

fix: firefox does not connect correctly close jira-42

---

packages/maskbook/src/extension/background-script/EthereumServices/tokenList.ts
packages/maskbook/src/extension/options-page/DashboardComponents/TokenIcon.tsx
packages/maskbook/src/extension/options-page/DashboardComponents/TokenIconSpeialIconList.json
packages/maskbook/src/extension/options-page/DashboardComponents/TokenInList.tsx
packages/web3-shared/src/constants/index.ts
packages/web3-shared/src/types/index.ts

fix: token icon not show on BSC

---

packages/maskbook/src/plugins/ITO/apis/index.ts
packages/maskbook/src/plugins/RedPacket/apis/index.ts
packages/maskbook/src/plugins/Trader/apis/uniswap-v2-subgraph/index.ts

This is an urgent and quick fix.
thegraph api only returns default first 100 entities when `first` attribute is absent, which cause that the user can't retrieve his 101th red packets from history.
I will open another issue to discuss tech solution of List lazy loading later.

fix: unlimit thegraph query amount

---

packages/maskbook/package.json
pnpm-lock.yaml

chore: lock snapshot.js version

---

packages/theme/src/Components/Dialogs/DialogTitle.tsx

`:first-of-type` let close button get the margin when there is no back button, `:first-child` would get server side rending unsafe error tip, so just add the margin to back button.

fix: dialog close button position

---

packages/maskbook/src/plugins/FileService/SNSAdaptor/index.tsx

fix: file service label

---

package.json
pnpm-lock.yaml

This version contains a performance regression fix from 4.4
https://github.com/microsoft/TypeScript/pull/44431
The incremental build time shorten from ~2min to ~15s on my mahcine.

chore: upgrade typescript to 4.3.5

---

packages/maskbook/src/plugins/ITO/SNSAdaptor/ITO.tsx
packages/maskbook/src/plugins/ITO/SNSAdaptor/PostInspector.tsx
packages/maskbook/src/plugins/ITO/SNSAdaptor/index.tsx
packages/maskbook/src/plugins/ITO/types.ts
packages/web3-shared/src/hooks/useERC20TokenDetailed.ts

Since we reduce the size of ITO compose payload to support image payload. `exchange_tokens` only retains `address` property, then the ITO postInspector will fetch the detail of tokens by `useFungibleTokensDetailed()`

feat: ito use tokens detail

---

packages/maskbook/src/_locales/en/messages.json
packages/maskbook/src/_locales/ja/messages.json
packages/maskbook/src/_locales/ko/messages.json
packages/maskbook/src/_locales/zh/messages.json
packages/maskbook/src/extension/background-script/EthereumServices/tokenList.ts
packages/maskbook/src/plugins/ITO/SNSAdaptor/PostInspector.tsx
packages/maskbook/src/plugins/RedPacket/SNSAdaptor/RedPacket.tsx
packages/maskbook/src/plugins/RedPacket/SNSAdaptor/hooks/useAvailabilityComputed.ts
packages/maskbook/src/plugins/RedPacket/SNSAdaptor/index.tsx
packages/maskbook/src/plugins/Wallet/services/assets.ts
packages/maskbook/src/web3/UI/EthereumChainBoundary.tsx
packages/maskbook/src/web3/UI/EthereumWalletConnectedBoundary.tsx
packages/shared/src/UI/components/TokenIcon/index.tsx
packages/web3-shared/src/assets/chains.json
packages/web3-shared/src/context/index.tsx
packages/web3-shared/src/hooks/useChainIdValid.ts
packages/web3-shared/src/utils/address.ts
packages/web3-shared/src/utils/chainDetailed.ts
packages/web3-shared/src/utils/index.ts
packages/web3-shared/src/utils/token.ts

refactor: chain detailed

---

packages/maskbook/package.json
packages/maskbook/webpack.config.ts
pnpm-lock.yaml

fix(build): watcher of webpack watches too many files including output files and files in node_modules

---

packages/maskbook/src/components/InjectedComponents/ToolboxHint.tsx
packages/maskbook/src/plugins/Wallet/SNSAdaptor/WalletStatusDialog/index.tsx
packages/maskbook/src/web3/UI/EthereumAccountButton.tsx

if the wallet is a valid one, clicking on status button should open
status dialog.
closes #3602 
@wenluomask Please take a look.
I found another issue during testing: I have two wallets (one connects to MetaMask which is currently activate, another is Maskbook wallet), when I delete the first one, the account becomes Maskbook wallet, but the selected wallet is unset. We might discuss the behave details further.

fix: open status dialog instead of select dialog

---

packages/icons/general/Search.tsx
packages/icons/package.json
packages/maskbook/src/extension/options-page/DashboardRouters/Contacts.tsx
pnpm-lock.yaml

also remove @masknet/theme from icons' dependencies

refactor: let SearchIcon inherit color from style context

---

packages/maskbook/src/plugins/Wallet/apis/debank.ts
packages/maskbook/src/plugins/Wallet/apis/zerion.ts
packages/maskbook/src/plugins/Wallet/pipes/index.ts
packages/maskbook/src/plugins/Wallet/services/assets.ts
packages/maskbook/src/plugins/Wallet/services/transactions.ts

fix: zerion with polygon & bsc

---

packages/maskbook/src/plugins/PoolTogether/SNSAdaptor/index.tsx
packages/maskbook/src/web3/UI/EthereumChainBoundary.tsx

fix: the entrance of PL

---

packages/maskbook/src/plugins/Trader/trending/useAvailableCoins.ts
packages/maskbook/src/plugins/Trader/trending/useAvailableDataProviders.ts
packages/maskbook/src/plugins/Trader/trending/useAvailableTraderProviders.ts
packages/maskbook/src/utils/hooks/useQRCodeImageScan.tsx

```
Error: packages/maskbook/src/plugins/Trader/trending/useAvailableCoins.ts(5,17): error TS2742: The inferred type of 'useAvailableCoins' cannot be named without a reference to '../../../../../web3-shared/node_modules/react-use/lib/useAsyncFn'. This is likely not portable. A type annotation is necessary.
Error: packages/maskbook/src/plugins/Trader/trending/useAvailableDataProviders.ts(6,17): error TS2742: The inferred type of 'useAvailableDataProviders' cannot be named without a reference to '../../../../../web3-shared/node_modules/react-use/lib/useAsyncFn'. This is likely not portable. A type annotation is necessary.
Error: packages/maskbook/src/plugins/Trader/trending/useAvailableTraderProviders.ts(6,17): error TS2742: The inferred type of 'useAvailableTraderProviders' cannot be named …
```

fix: type error

---

packages/maskbook/src/_locales/en/messages.json
packages/maskbook/src/_locales/ja/messages.json
packages/maskbook/src/_locales/ko/messages.json
packages/maskbook/src/_locales/zh/messages.json
packages/maskbook/src/plugins/Wallet/services/account.ts
packages/maskbook/src/web3/UI/EthereumChainBoundary.tsx

fix: absence account

---

packages/.eslintrc.json

```
➜  Maskbook git:(septs/date-fns-limit) npm run lint
> maskbook@1.34.1 lint
> eslint -c packages/.eslintrc.json packages --ext .ts,.tsx,.js --cache --fix
/Volumes/Projects/DimensionDev/Maskbook/packages/maskbook/test.ts
1:1  error  'date-fns' import is restricted from being used. Please use date-fns/{submodule} instead      no-restricted-imports
2:1  error  'date-fns/esm' import is restricted from being used. Please use date-fns/{submodule} instead  no-restricted-imports
✖ 2 problems (2 errors, 0 warnings)
```

chore: add date-fns usage limit

---

.vscode/settings.json
docs/rfc/000-Payload-v37.md
docs/rfc/000-TypedMessage-and-Payload-37-playground.js
docs/rfc/000-TypedMessage-binary-format.md

- TypedMessage binary format ([rendered preview](https://github.com/DimensionDev/Maskbook/blob/rfc/next-payload/docs/rfc/000-TypedMessage-binary-format.md))
- Payload 37 format ([rendered preview](https://github.com/DimensionDev/Maskbook/blob/rfc/next-payload/docs/rfc/000-Payload-v37.md))

RFC: new payload v-37 and TypedMessage binary format

---

packages/maskbook/src/utils/flags.ts

If `v2_enabled` is using. It means the same features from v1 will be disabled. The v2 replacements will be enabled by default.

refactor: add v2_enabled flag

---

.github/workflows/compile.yml
.github/workflows/linters.yml

closes #
1. vscode thinks `build.yml` belong hammerkit's build file format
therefore rename `build.yml` -> `compile.yaml`
2. add cache action name
3. switch `actions/setup-node@v2-beta` to `actions/setup-node@v2`

chore: update actions

---

packages/maskbook/src/plugins/Airdrop/index.ts
packages/maskbook/src/plugins/Collectible/index.ts
packages/maskbook/src/plugins/External/index.ts
packages/maskbook/src/plugins/FileService/Worker/rpc.ts
packages/maskbook/src/plugins/FileService/index.ts
packages/maskbook/src/plugins/Gitcoin/index.ts
packages/maskbook/src/plugins/GoodGhosting/index.ts
packages/maskbook/src/plugins/ITO/index.ts
packages/maskbook/src/plugins/NFT/index.ts
packages/maskbook/src/plugins/Polls/index.ts
packages/maskbook/src/plugins/PoolTogether/index.ts
packages/maskbook/src/plugins/PoolTogether/messages.ts
packages/maskbook/src/plugins/RedPacket/index.ts
packages/maskbook/src/plugins/Snapshot/index.ts
packages/maskbook/src/plugins/Trader/index.ts
packages/maskbook/src/plugins/Transak/index.ts
packages/maskbook/src/plugins/VCent/index.ts
packages/maskbook/src/plugins/Wallet/index.ts
packages/maskbook/src/plugins/dHEDGE/index.ts
packages/plugin-infra/src/types.ts
packages/plugins/example/src/index.ts

This is a regression introduced in #3471 which @guanbinrui converts all `import.meta.webpackHot && import.meta.webpackHot.accept` into `import.meta.webpackHot?.accept`. I was raised concern about if HMR still works and get the answer of yes but it proved it's not the case.
We can go back to `?.` once we get #3750 back (that depends on webpack/webpack#12960).

fix: hot reload for plugins

---

packages/maskbook/package.json
packages/maskbook/src/plugins/Snapshot/SNSAdaptor/ResultCard.tsx
packages/maskbook/src/plugins/Snapshot/SNSAdaptor/VotesCard.tsx
packages/maskbook/src/plugins/Snapshot/SNSAdaptor/hooks/useResults.ts
packages/maskbook/src/plugins/Snapshot/SNSAdaptor/hooks/useVotes.ts
packages/maskbook/src/plugins/Snapshot/Worker/apis/index.ts
packages/maskbook/src/plugins/Snapshot/types.ts
pnpm-lock.yaml

fix: Snapshot api breaks
* refactor: snapshot api
* chore: github package
Test link:
https://twitter.com/Zhouhancheng/status/1425395315469733895
https://snapshot.org/#/balancer/proposal/QmZk8p2iJwHd94pA61RBXYDk2StHLmQowHDKqLMorQP2k7

refactor: snapshot api

---

packages/maskbook/src/utils/native-rpc/Web.ts
packages/public-api/src/web.ts

Raw `Date` type inside a JSON is difficult for mobile apps to resolve

fix: return UTC time string instead of `Date` for `public-api`s

---

packages/maskbook/src/_locales/en-US/messages.json
packages/maskbook/src/_locales/ja-JP/messages.json
packages/maskbook/src/_locales/ko-KR/messages.json
packages/maskbook/src/_locales/zh-TW/messages.json
packages/maskbook/src/components/InjectedComponents/PostDialog.tsx
packages/maskbook/src/extension/background-script/EthereumServices/provider.ts
packages/maskbook/src/extension/background-script/EthereumServices/providers/MetaMask.ts
packages/maskbook/src/extension/background-script/EthereumServices/send.ts
packages/maskbook/src/plugins/Wallet/settings.ts
packages/maskbook/src/web3/UI/EthereumWalletConnectedBoundary.tsx

This PR removed `currentIsMetaMaskLockedSettings` and related UI interface. For each transaction that needs to be signed. We will emit a preflight request to make sure MetaMask has connected an account and unlocked it. 
closes #

fix: unlock metamask

---

packages/maskbook/src/components/InjectedComponents/DecryptedPost/DecryptedPost.tsx
packages/maskbook/src/database/post.ts
packages/maskbook/src/extension/background-script/CryptoServices/decryptFrom.ts
packages/maskbook/src/extension/background-script/CryptoServices/encryptTo.ts
packages/maskbook/src/polyfill/global.d.ts
packages/maskbook/src/social-network-adaptor/facebook.com/shared.ts
packages/maskbook/src/social-network-adaptor/minds.com/shared.ts
packages/maskbook/src/social-network-adaptor/twitter.com/shared.ts
packages/maskbook/src/social-network/utils/create-post-context.ts
packages/maskbook/src/utils/type-transform/BackupFormat/JSON/DBRecord-JSON/PostRecord.ts
packages/maskbook/src/utils/type-transform/BackupFormat/JSON/version-2.ts
packages/plugin-infra/src/PostContext.ts

Record the following information of a post:
- URL
- `encryptedBy`: `PersonaIdentifier`
- `summary`: string (a char that has a length around 20, can overflow to keep the completeness of Unicode code-point cluster)
- `interestedMeta`: The interested metadata that this post contains.
Notice: Only URL is recorded on the decryption process. All other extra information ARE ONLY recorded at the composition (encryption) time!
Since the dashboard is ONLY using the post _I_ sent, so I will not record other one's posts to save space.
close #3374 
close MASK-58

feat: record post history

---

packages/maskbook/src/utils/native-rpc/Web.ts
packages/public-api/src/web.ts

Since `SNSAdaptor_getCurrentDetectedProfile` returns `ProfileIdentifier` as the result, the `persona_connectProfile` should also accept `ProfileIdentifier` as the input param

feat: update connectProfile to directly use `ProfileIdentifier` as param

---

packages/maskbook/src/plugins/ITO/SNSAdaptor/ITO.tsx

Support ITO qualification `ifQualified()` which returns an error msg, and display it.
(This is a testing qualification, 'not started' is pure text)

chore: ito qual error msg

---

packages/maskbook/src/extension/background-script/EthereumServices/request.ts
packages/maskbook/src/extension/background-script/EthereumServices/send.ts
packages/maskbook/src/extension/popups/pages/Wallet/GasSetting/index.tsx
packages/maskbook/src/extension/popups/pages/Wallet/SignRequest/index.tsx
packages/maskbook/src/plugins/ITO/SNSAdaptor/hooks/useBlockNumberOfChain.ts
packages/maskbook/src/plugins/ITO/SNSAdaptor/hooks/useClaimablePoolsByWeb3.ts
packages/maskbook/src/plugins/Wallet/services/rpc.ts

+ Use `chainId` to replace the `rpc` in overrides;
+ Need to confirm or reject each request by second time;
closes #

refactor: send request with second-time confirmation

---

packages/maskbook/src/plugins/Collectible/SNSAdaptor/CollectibleTab.tsx

fix(Firefox): collectibles detail tab can't scrolll

---

.github/workflows/linters.yml

prettier@latest or prettier@2.4.0 fails CI (see https://github.com/DimensionDev/Maskbook/pull/4288/checks?check_run_id=3554560830)

ci: lock prettier version at prettier job

---

packages/maskbook/src/extension/background-script/EthereumServices/send.ts

Redirect all read-only methods to Mask Network provider.
closes #

refactor: redirect readonly methods

---

packages/maskbook/src/plugins/VCent/SNSAdaptor/TweetDialog.tsx
packages/maskbook/src/plugins/VCent/SNSAdaptor/index.tsx
packages/maskbook/src/plugins/VCent/Worker/index.ts
packages/maskbook/src/plugins/VCent/index.ts
packages/maskbook/src/plugins/VCent/messages.ts
packages/maskbook/src/plugins/VCent/services.ts

+ [x] Only fetch data of the primary tweet on the detailed page.
+ [x] Move requests to the background.
+ [x] Reduce duplicate requests.
closes #4420

refactor: move to rpc apis

---

packages/maskbook/src/plugins/ITO/SNSAdaptor/ClaimAllDialog.tsx

Show nft airdrop card on all networks, the Claim button is disabled when not on Matic.

fix: show nft airdrop

---

packages/maskbook/src/plugins/Polls/base.ts

chore: close poll plugin by default close #4400

---

.pnpmfile.cjs

As discussed in https://github.com/pnpm/pnpm/issues/4001, limiting build scripts is not enough.
It can be bypassed by specifying a non-safe installation target.
This PR adds a PNPM installation hook to validate all those non-safe installation targets.
#3323

feat(security): limit installation source

---

packages/mask/src/extension/background-script/EthereumServices/providers/MaskWallet.ts
packages/mask/src/extension/popups/pages/Wallet/DeleteWallet/index.tsx
packages/mask/src/extension/popups/pages/Wallet/SelectWallet/index.tsx
packages/mask/src/plugins/Wallet/services/account.ts

fix: select wallet page is empty

---

packages/injected-script/main/EventListenerPatch/capture.ts

fix: fb image paste not work

---

packages/mask/src/components/CompositionDialog/PluginEntryRender.tsx
packages/mask/src/plugins/ITO/base.ts
packages/mask/src/plugins/RedPacket/base.ts
packages/mask/src/plugins/UnlockProtocol/base.ts
packages/plugin-infra/src/manager/sns-adaptor.ts
packages/plugin-infra/src/types.ts
packages/plugin-infra/src/web3-types.ts

A plugin can declare web3 requirements on various chains. And, from now on, if a plugin has Web3 released features. It must declare the web3 requirements in the definition phase. That information will help the plugin infra conditionally render the plugin UI in various places.
closes #

refactor: web3 requirement

---

packages/mask/src/plugins/EVM/base.ts
packages/mask/src/plugins/EVM/constants.ts
packages/plugin-infra/src/types.ts
packages/plugin-infra/src/web3-types.ts
packages/plugins/Flow/src/base.ts

refactor: move application entrance definition to app-plugin

---

packages/mask/src/extension/background-script/WelcomeServices/restoreBackup.ts
packages/mask/src/plugins/Wallet/services/wallet/index.ts
packages/mask/src/plugins/Wallet/services/wallet/type.ts

Avoid updating the `derivationPath` of the wallet record, use `latestDerivationPath` to serve the same purpose.
closes #5111

fix: failed to restore the initial wallet

---

packages/mask/src/components/InjectedComponents/PageInspector.tsx

fix: popup's position is too low when do image payload on Facebook

---

packages/mask/src/plugins/Furucombo/UI/FurucomboView.tsx
packages/mask/src/plugins/Furucombo/UI/InvestmentsView.tsx
packages/mask/src/plugins/Furucombo/UI/PoolView.tsx
packages/mask/src/plugins/Furucombo/types.tsx

Furucombo will release some investable without pool token. So I have update investable.token.address to investable.address. To make sure the plugin is normal.

chore: update investable.token.address to investable.address

---

packages/mask/src/components/shared/Video.tsx

can still be override from outside

fix: mute video by default

---

packages/web3-shared/evm/hooks/useAssetsFromChain.ts

https://mask.atlassian.net/browse/MASK-373

fix: use assets without connected

---

packages/mask/src/components/InjectedComponents/SearchResultBox.tsx
packages/mask/src/social-network-adaptor/twitter.com/injection/EnhancedProfile.tsx
packages/mask/src/social-network-adaptor/twitter.com/injection/EnhancedProfileTab.tsx
packages/mask/src/social-network-adaptor/twitter.com/utils/selector.ts

fix(ui): the web3 tab abnormal style

---

packages/dashboard/src/locales/en-US.json
packages/dashboard/src/pages/Wallets/components/Transfer/TransferERC721.tsx
packages/mask/background/database/persona/db.ts
packages/web3-shared/evm/hooks/useERC721TokenTransferCallback.ts

1. Should keep login status when restore persona which not have private key
2. User can send NFT to self in dashboard

fix: should keep login status when restore persona which not have private key

---

packages/dashboard/src/pages/Wallets/components/Transfer/TransferERC20.tsx

fix: dashboard transfer ERC20 error

---

packages/dashboard/src/pages/Wallets/components/Transfer/TransferERC20.tsx

fix: send eth can not call provider

---

packages/mask/src/extension/popups/components/NetworkSelector/index.tsx
packages/mask/src/extension/popups/pages/Wallet/ContractInteraction/index.tsx
packages/mask/src/extension/popups/pages/Wallet/GasSetting/index.tsx
packages/mask/src/extension/popups/pages/Wallet/ReplaceTransaction/index.tsx
packages/mask/src/extension/popups/pages/Wallet/Transfer/index.tsx
packages/mask/src/plugins/Trader/SNSAdaptor/trader/SettingsDialog.tsx
packages/mask/src/plugins/Trader/SNSAdaptor/trending/TraderView.tsx

fix: read network type from wrong place

---

packages/mask/src/plugins/Avatar/SNSAdaptor/NFTAvatarRing.tsx
packages/mask/src/plugins/Avatar/SNSAdaptor/RainbowBox.tsx
packages/mask/src/social-network-adaptor/twitter.com/injection/NFT/NFTAvatarInTwitter.tsx
packages/mask/src/social-network-adaptor/twitter.com/utils/selector.ts

refactor: profile nft avatar

---

packages/mask/src/plugins/MaskBox/SNSAdaptor/components/PreviewCard.tsx

fix(Maskbox): add a space between digit and symbol

---

packages/web3-shared/evm/hooks/useERC721TokenDetailed.ts

`JSON.stringify()` hook object type dependency to avoid infinite calling NFT red packet ERC721 method.

fix: stringify hook dependency

---

packages/mask/src/extension/background-script/EthereumServices/send.ts
packages/public-api/src/mobile.ts

Due to GeckoView's bug
> GeckoView fails to serialize a JSON object with a nested array while communicating between JS and native, this makes the native side CANNOT receive some messages from `public-api`
This PR introduces a walkaround of stringifying the JSON before sending it to the message channel.
Tested positive on Android

fix: walkaround of GeckoView's JSON serialization bug by stringifying the JSON object

---

packages/mask/src/plugins/Avatar/constants.ts
packages/mask/src/plugins/Profile/SNSAdaptor/hooks/useDao.ts

refactor: update configuration url

---

packages/mask/src/extension/popups/pages/Wallet/components/AssetsList/index.tsx

fix: add fallback when import erc721 in popup asset list

---

packages/mask/src/plugins/MaskBox/SNSAdaptor/components/DrawDialog.tsx
packages/mask/src/plugins/MaskBox/helpers/formatCountdown.ts
packages/mask/src/plugins/MaskBox/hooks/useContext.ts
packages/mask/src/plugins/MaskBox/hooks/useHeartBeat.ts
packages/mask/src/plugins/MaskBox/type.ts
packages/web3-shared/evm/hooks/useTransactionCallback.ts

Fix the problem that requires input gas in MetaMask manually.

fix: guarding gas config in useTransactionCallback

---

packages/mask/src/plugins/ITO/SNSAdaptor/ConfirmDialog.tsx
packages/mask/src/plugins/ITO/SNSAdaptor/ITO.tsx
packages/web3-shared/evm/utils/formatter.ts

[MASK-496](https://mask.atlassian.net/jira/software/c/projects/MASK/boards/20?modal=detail&selectedIssue=MASK-496)

chore: remove formatAmountPrecision

---

packages/mask/src/plugins/Avatar/SNSAdaptor/NFTBadge.tsx
packages/mask/src/social-network-adaptor/twitter.com/injection/NFT/NFTAvatarInTwitter.tsx

fix: recovery normal style when user doesn't have an NFT avatar
