packages/constants/data/trader.json
packages/maskbook/src/plugins/Trader/apis/trader/index.ts

feat: sashimiswap on BSC

---

packages/maskbook/src/plugins/dHEDGE/UI/PoolView.tsx
packages/maskbook/src/plugins/dHEDGE/define.tsx

fix: dhedge plugin was involved in incorrect context

---

docs/css-in-js.md

docs: upgrade CSS in JS guide

---

packages/maskbook/src/extension/options-page/DashboardComponents/PluginCard.tsx
packages/maskbook/src/extension/options-page/DashboardDialogs/Plugin.tsx
packages/maskbook/src/extension/options-page/DashboardRouters/Plugins.tsx

fix: only dhedge in plugin list page

---

packages/maskbook/src/components/InjectedComponents/PostReplacer.tsx
packages/maskbook/src/plugins/types.ts
packages/plugin-infra/src/types.ts

feat: enable typedMessageTransformer in post replacer

---

packages/maskbook/src/plugins/Wallet/SNSAdaptor/ImportWalletDialog/MnemonicTab.tsx
packages/maskbook/src/plugins/Wallet/SNSAdaptor/WalletStatusDialog/index.tsx

chore: clean template string

---

packages/maskbook/src/plugins/Trader/SNSAdaptor/index.tsx
packages/plugin-infra/src/types.ts

fix: the cash popover

---

packages/maskbook/src/plugins/Polls/SNSAdaptor/PollsDialog.tsx

fix: the list boxes in Poll can not be expanded fully

---

packages/maskbook/src/plugins/RedPacket/SNSAdaptor/RedPacket.tsx
packages/maskbook/src/plugins/RedPacket/SNSAdaptor/RedPacketForm.tsx

Do not change redpacket payload after tx has sent.

fix: rp compose payload

---

packages/maskbook/webpack.config.ts

fix: reproducible build on firefox close #3577

---

packages/maskbook/src/plugins/dHEDGE/define.tsx

fix: dhedge crash if it encounters an unknown network

---

packages/maskbook/src/components/InjectedComponents/PostDialog.tsx

Clear payload when close Compose dialog

fix: clear compose payload

---

packages/maskbook/src/plugins/RedPacket/SNSAdaptor/RedPacket.tsx

fix: redpacket native token

---

packages/maskbook/src/_locales/en/messages.json
packages/maskbook/src/plugins/ITO/SNSAdaptor/PoolList.tsx
packages/maskbook/src/plugins/ITO/SNSAdaptor/hooks/useAllPoolsAsSeller.ts

Stop sending further query when scroll to bottom as there's already no data can fetch.

fix: list lazy loading

---

packages/maskbook/src/plugins/ITO/SNSAdaptor/hooks/useClaimAll.ts

fix: ito claim all

---

packages/maskbook/package.json
packages/maskbook/src/env.d.ts
pnpm-lock.yaml

chore: remove `eth-contract-metadata`

---

packages/maskbook/src/plugins/Wallet/services/assets.ts
packages/maskbook/src/plugins/Wallet/services/transactions.ts

fix: zerion api only works on ethereum

---

packages/maskbook/src/plugins/Wallet/apis/gasnow.ts
packages/web3-shared/src/types/index.ts

you can test ws connect on https://www.websocket.org/echo.html

fix: update GasNow websocket

---

packages/maskbook/src/plugins/ITO/SNSAdaptor/ConfirmDialog.tsx

fix: display wrong number

---

packages/maskbook/src/social-network-adaptor/options-page/index.ts

fix: huge backup restore

---

packages/maskbook/src/components/InjectedComponents/PostDialog.tsx
packages/maskbook/src/components/InjectedComponents/ToolboxHint.tsx
packages/maskbook/src/plugins/ITO/base.ts
packages/maskbook/src/plugins/RedPacket/base.ts
packages/plugin-infra/src/types.ts

feat: hide entries chain invalid

---

packages/web3-shared/src/hooks/useERC20TokenDetailed.ts
packages/web3-shared/src/hooks/useERC721TokenDetailed.ts

Fix: fetch token detailed on switched chain

fix: fetch token detailed

---

packages/cli/build/netlify.ts
packages/cli/tsconfig.json

fix: type declaration

---

packages/maskbook/src/extension/browser-action/UI.tsx

fix: hide the grant button if none persona was created

---

packages/maskbook/src/plugins/Wallet/services/assets.ts

fix: duplicate tokens in wallet assets table

---

packages/maskbook/src/extension/background-script/EthereumServices/network.ts
packages/maskbook/src/plugins/Wallet/SNSAdaptor/ConnectWalletDialog/index.tsx
packages/web3-shared/src/types/index.ts

fix: switch to ethereum mainnet

---

packages/maskbook/src/components/InjectedComponents/ToolboxHint.tsx
packages/maskbook/src/plugins/Wallet/SNSAdaptor/SelectProviderDialog/index.tsx

fix: clicking connect-wallet button should open wallet select dialog

---

packages/maskbook/src/plugins/VCent/base.ts

feat: enable vcent in stable mode

---

packages/maskbook/src/extension/options-page/DashboardComponents/WalletAssetsTable.tsx
packages/maskbook/src/web3/UI/EthereumChainBoundary.tsx
packages/web3-shared/src/pipes/index.ts
packages/web3-shared/src/utils/token.ts

fix: chain boundary

---

packages/maskbook/src/extension/background-script/EthereumServices/providers/MetaMask.ts
packages/maskbook/src/extension/background-script/EthereumServices/providers/WalletConnect.ts
packages/maskbook/src/extension/background-script/EthereumServices/send.ts
packages/maskbook/src/extension/options-page/DashboardDialogs/Wallet/DeleteConfirm.tsx
packages/maskbook/src/plugins/Wallet/SNSAdaptor/SelectWalletDialog.tsx
packages/maskbook/src/plugins/Wallet/services/account.ts
packages/maskbook/src/plugins/Wallet/services/chain.ts
packages/maskbook/src/plugins/Wallet/services/index.ts
packages/maskbook/src/plugins/Wallet/services/wallet.ts
packages/maskbook/src/web3/UI/EthereumChainBoundary.tsx

closes #3564
TODO: Fixed build errors.

refactor: no more global settings

---

README.md
docs/caveats.md
docs/dependencies.md

fix: markdown

---

packages/maskbook/package.json
pnpm-lock.yaml

chore: upgrade webextension-shim to fix mobile app issues

---

.circleci/config.yml
.github/workflows/build.yml
packages/dashboard/src/env.d.ts
packages/maskbook/src/env.d.ts
packages/maskbook/src/extension/background-script/EthereumServices/providers/Maskbook.ts
packages/maskbook/src/extension/options-page/DashboardRouters/Wallets.tsx
packages/maskbook/src/plugins/Trader/apis/balancer/index.ts
packages/maskbook/webpack.config.ts
packages/web3-constants/data/rpc.json
packages/web3-shared/src/assets/chains.json
packages/web3-shared/src/constants/index.ts
packages/web3-shared/src/constants/utils.ts
packages/web3-shared/src/utils/token.ts

refactor: add rpc.json

---

packages/maskbook/webpack.config.ts

fix: env error

---

packages/maskbook/src/plugins/Collectible/SNSAdaptor/Collectible.tsx

fix: check is valid date close #3644

---

packages/maskbook/src/plugins/VCent/SNSAdaptor/index.tsx

fix: vcent plugin does not render tweets

---

packages/maskbook/src/social-network-adaptor/facebook.com/collecting/posts.tsx
packages/maskbook/src/social-network/utils/create-post-context.ts
packages/shared/src/hooks/useValueRef.ts

fix: image payload not decryptable on facebook close #3284

---

packages/maskbook/src/extension/options-page/DashboardComponents/TokenInList.tsx

fix: unknown token in the token list

---

packages/maskbook/src/plugins/Wallet/apis/debank.ts
packages/maskbook/src/plugins/Wallet/hooks/useTransactions.ts
packages/maskbook/src/plugins/Wallet/pipes/index.ts
packages/maskbook/src/plugins/Wallet/services/assets.ts
packages/maskbook/src/plugins/Wallet/services/transactions.ts
packages/web3-shared/src/context/type.ts
packages/web3-shared/src/hooks/useAssetsFromProvider.ts
packages/web3-shared/src/pipes/index.ts

fix: debank & zerion api on multiple networks

---

packages/dashboard/src/web3/context.ts
packages/maskbook/src/web3/context.ts
packages/web3-shared/src/hooks/useAssetsFromChain.ts
packages/web3-shared/src/hooks/useERC20Tokens.ts
packages/web3-shared/src/hooks/useTrustedERC20Tokens.ts

fix: add token into DB

---

packages/maskbook/src/_locales/en/messages.json
packages/maskbook/src/_locales/ja/messages.json
packages/maskbook/src/_locales/ko/messages.json
packages/maskbook/src/_locales/zh/messages.json
packages/maskbook/src/components/InjectedComponents/PostDialog.tsx

fix: rp image pre text

---

packages/web3-shared/src/hooks/useERC20TokenDetailed.ts

fix: token address

---

docs/plugin-development-guide.md
packages/maskbook/src/database/Plugin/wrap-plugin-database.ts
packages/maskbook/src/plugins/Trader/Dashboard/index.tsx
packages/maskbook/src/plugins/Trader/SNSAdaptor/index.tsx
packages/maskbook/src/plugins/Trader/Worker/index.ts
packages/maskbook/src/plugins/Trader/base-deferred.ts
packages/maskbook/src/plugins/Trader/messages/TypedMessageCashTrending.tsx
packages/plugin-infra/src/manager/manage.ts
packages/plugin-infra/src/types.ts

- refactor: restructure files
- docs: rewrite plugin development guide
closes #3637

docs: rewrite plugin dev doc

---

docs/caveats.md
docs/css-in-js.md
docs/local-or-remote-dialog.md
docs/plugin-development-guide.md

chore: clean docs

---

packages/maskbook/src/plugins/Trader/apis/trader/index.ts

SUSHISWAP SASHIMISWAP does not support bsc. try bnb <=> usdt

chore: remove bsc swapper

---

packages/maskbook/src/plugins/Wallet/SNSAdaptor/ConnectWalletDialog/index.tsx
packages/maskbook/src/plugins/Wallet/SNSAdaptor/SelectProviderDialog/index.tsx

fix(Wallet): do not open the WalletStatusDialog after switching network

---

packages/maskbook/src/plugins/ITO/SNSAdaptor/ITO.tsx

fix: claim status

---

packages/maskbook/src/extension/options-page/DashboardComponents/FixedTokenList.tsx

fix: twitter can't  show token list in swap

---

packages/maskbook/src/plugins/ITO/SNSAdaptor/hooks/useAvailabilityComputed.ts

chore: remove unused code

---

packages/web3-constants/data/rpc.json

chore: update rpc for matic (dev mode only)

---

docs/plugin-development-guide.md

docs: add how to register plugin

---

packages/maskbook/src/social-network-adaptor/facebook.com/injection/PostInspector.tsx

fix: can't access property "querySelector", parentEle is null

---

packages/maskbook/src/extension/background-script/EthereumServices/network.ts
packages/web3-shared/src/hooks/useGetPastLogsParams.ts

fix: constants strict

---

packages/maskbook/src/plugins/PoolTogether/apis/index.ts
packages/maskbook/src/plugins/PoolTogether/contracts/usePoolTogetherPool.ts
packages/maskbook/src/plugins/PoolTogether/hooks/usePools.ts

fix: options maybe undefined in `usePools`

---

packages/maskbook/src/components/InjectedComponents/DecryptedPost/DecryptedPost.tsx
packages/maskbook/src/components/InjectedComponents/PostInspector.tsx
packages/maskbook/src/extension/background-script/CryptoServices/decryptFrom.ts

feat: allow public shared post decrypted when author is unknown

---

packages/maskbook/src/plugins/PoolTogether/apis/index.ts

fix: failed to load pool-together

---

packages/maskbook/src/extension/options-page/DashboardDialogs/Wallet/DeleteConfirm.tsx
packages/maskbook/src/plugins/Wallet/services/account.ts
packages/web3-shared/src/hooks/useWallet.ts

closes #3722
~~`null` vs empty-string, `null` would be better to represent **unset**.~~ (this breaks type-checking a lot)

fix(Wallet): properly delete acount

---

packages/maskbook/src/plugins/Trader/settings.ts

chore: the default trending data provider

---

packages/maskbook/src/_locales/en/messages.json
packages/maskbook/src/plugins/PoolTogether/UI/PoolTogetherView.tsx

fix: the color of text placeholder

---

packages/.eslintrc.json
tsconfig.json

per changes in #3747
BigInt still not allowed.

feat: enable es2020 syntax

---

packages/dashboard/package.json
packages/maskbook/package.json
packages/maskbook/src/social-network-adaptor/facebook.com/injection/Composition.tsx
packages/maskbook/src/social-network-adaptor/facebook.com/injection/SetupPrompt.tsx
packages/plugin-infra/package.json
packages/shared/package.json
packages/shared/src/UI/hooks/useImageFailOver.ts
pnpm-lock.yaml

feat: upgrade to holoflows-kit 0.9.0

---

packages/.eslintrc.json
tsconfig.json

See https://github.com/webpack/webpack/issues/12960

Revert "feat: enable es2020 syntax"

---

packages/maskbook/webpack.config.ts

revert: date-fns/esm alias

---

packages/cli/utils.ts
packages/theme/package.json
pnpm-lock.yaml

fix: build-ci failed exit-code always zero bug

---

packages/maskbook/src/plugins/dHEDGE/constants.ts

fix: dHedge plugin id

---

packages/maskbook/src/_locales/en/messages.json
packages/maskbook/src/extension/options-page/DashboardComponents/WalletAssetsTable.tsx
packages/maskbook/src/plugins/Wallet/apis/zerion.ts
packages/maskbook/src/plugins/Wallet/pipes/index.ts
packages/maskbook/src/plugins/Wallet/services/assets.ts
packages/maskbook/src/plugins/Wallet/services/transactions.ts

fix: some trivial bugs

---

packages/maskbook/src/plugins/ITO/SNSAdaptor/PoolInList.tsx

fix: ito token decimals

---

packages/maskbook/src/extension/options-page/DashboardComponents/CollectibleList/CollectibleCard.tsx
packages/maskbook/src/extension/options-page/DashboardRouters/Settings.tsx
packages/maskbook/src/extension/options-page/DashboardRouters/Wallets.tsx
packages/maskbook/src/plugins/Wallet/helpers.ts
packages/maskbook/src/plugins/Wallet/hooks/useERC1155Tokens.ts
packages/maskbook/src/plugins/Wallet/hooks/useERC721Tokens.ts
packages/maskbook/src/plugins/Wallet/hooks/useTransactions.ts
packages/maskbook/src/plugins/Wallet/hooks/useWallet.ts
packages/maskbook/src/plugins/Wallet/pipes/index.ts
packages/maskbook/src/plugins/Wallet/services/assets.ts
packages/maskbook/src/plugins/Wallet/services/transactions.ts
packages/maskbook/src/plugins/Wallet/settings.ts
packages/maskbook/src/plugins/Wallet/types/portfolio.ts
packages/web3-shared/src/pipes/index.ts

import from @masknet/web3-shared directly

refactor: remove re-export from @masknet/web3-shared

---

packages/maskbook/src/plugins/RedPacket/SNSAdaptor/RedPacketForm.tsx

closes #3781
This bug is caused by a newly added property `logoURI` from token List.

fix: rp img payload

---

packages/maskbook/src/extension/background-script/EthereumServices/network.ts

fix: failed to switch to etherum mainnet

---

packages/maskbook/src/_locales/en/messages.json
packages/maskbook/src/plugins/PoolTogether/UI/DepositDialog.tsx

fix: add post link as payload of shared tweet

---

packages/maskbook/webpack.config.ts
packages/scripts/src/extension/normal.ts

chore: show output when failed

---

packages/maskbook/src/_locales/en/messages.json
packages/maskbook/src/plugins/PoolTogether/UI/DepositDialog.tsx

Reverts DimensionDev/Maskbook#3788

revert: add post link as payload of shared tweet

---

packages/maskbook/src/social-network-adaptor/twitter.com/utils/selector.ts

since the DOM of twitter timeline got updated

fix(twitter): add a new postcontent selector for twitter

---

packages/maskbook/src/extension/options-page/DashboardComponents/ActionsBarFT.tsx
packages/maskbook/src/extension/options-page/DashboardComponents/WalletContent.tsx
packages/maskbook/src/plugins/Transak/SNSAdaptor/BuyTokenDialog.tsx
packages/maskbook/src/plugins/Transak/hooks/useTransakAllowanceCoin.ts
packages/maskbook/src/plugins/Transak/hooks/useTransakURL.ts

feat: expand transak allowance coins, not just eth

---

packages/maskbook/src/plugins/Snapshot/Worker/apis/index.ts

fix: snapshot break down

---

packages/maskbook/src/extension/background-script/EthereumServices/providers/WalletConnect.ts

fix: bridge is down

---

packages/maskbook/src/extension/options-page/DashboardRouters/Settings.tsx
packages/maskbook/webpack.config.ts

feat: enable new dashboard in beat

---

packages/maskbook/src/extension/browser-action/UI.tsx
packages/maskbook/src/extension/options-page/DashboardRouters/Settings.tsx
packages/maskbook/src/extension/options-page/Welcome/getWelcomePageURL.tsx
packages/maskbook/src/utils/flags.ts
packages/maskbook/webpack.config.ts

feature: replace enter to new dashboard in beta

---

packages/maskbook/src/plugins/Wallet/services/assets.ts

fix: show NaN in dashboard asset list

---

packages/.eslintrc.json
packages/maskbook/src/components/shared-settings/useSettingsUI.tsx
packages/maskbook/src/crypto/crypto-alpha-39.ts
packages/maskbook/src/extension/popups/ThirdPartyRequestPermission/index.tsx
packages/maskbook/src/plugins/Airdrop/hooks/useCheckCallback.ts
packages/maskbook/src/plugins/Collectible/hooks/useAsset.ts
packages/maskbook/src/plugins/GoodGhosting/utils.ts
packages/maskbook/src/plugins/ITO/SNSAdaptor/ITO_Card.tsx
packages/maskbook/src/plugins/ITO/SNSAdaptor/hooks/useBlockNumberOfChain.ts
packages/maskbook/src/plugins/ITO/Worker/apis/checkAvailability.ts
packages/maskbook/src/plugins/Trader/apis/LBP/index.ts
packages/maskbook/src/plugins/dHEDGE/apis/index.ts
packages/maskbook/src/utils/theme-tools.ts
packages/maskbook/src/utils/utils.ts
packages/web3-shared/src/hooks/useERC20TokenDetailed.ts

fix: parseint radix unset

---

e2e/commands/twitter.ts
packages/dashboard/src/pages/Settings/components/dialogs/BackupDialog.tsx
packages/maskbook/public/patches.js
packages/maskbook/src/components/InjectedComponents/PostDialog.tsx
packages/maskbook/src/components/InjectedComponents/TypedMessageRenderer.tsx
packages/maskbook/src/database/avatar.ts
packages/maskbook/src/database/helpers/avatar.ts
packages/maskbook/src/database/helpers/openDB.ts
packages/maskbook/src/extension/background-script/CryptoServices/decryptFrom.ts
packages/maskbook/src/extension/background-script/Jobs/InjectContentScripts.ts
packages/maskbook/src/extension/background-script/StorageService.ts
packages/maskbook/src/extension/debug-page/DatabaseOps.tsx
packages/maskbook/src/extension/injected-script/addEventListener.ts
packages/maskbook/src/plugins/Collectible/SNSAdaptor/CheckoutDialog.tsx
packages/maskbook/src/plugins/Collectible/SNSAdaptor/ListingByHighestBidCard.tsx
packages/maskbook/src/plugins/Collectible/SNSAdaptor/ListingByPriceCard.tsx
packages/maskbook/src/plugins/Collectible/SNSAdaptor/MakeOfferDialog.tsx
packages/maskbook/src/plugins/RedPacket/SNSAdaptor/hooks/useCreateCallback.ts
packages/maskbook/src/plugins/Wallet/SNSAdaptor/ImportWalletDialog/index.tsx
packages/maskbook/src/social-network-adaptor/facebook.com/utils/getProfileIdentifier.ts
packages/maskbook/src/utils/hooks/useQRCodeVideoScan.tsx
packages/maskbook/src/utils/hooks/useSuspense.ts
packages/maskbook/src/utils/memoize.ts
packages/maskbook/src/utils/type-transform/BackupFormat/JSON/DBRecord-JSON/WalletRecord.ts
packages/scripts/src/utils/process-lock.ts
packages/shared-base/src/serializer/index.ts
packages/shared-base/src/utils/pollingTask.ts
scripts/puppeteer-repl.js

chore: clean up  try-catch

---

packages/maskbook/src/extension/background-script/HelperService.ts
packages/maskbook/src/social-network-adaptor/twitter.com/collecting/post.ts
packages/maskbook/src/social-network-adaptor/twitter.com/utils/selector.ts

fix(twitter): tweet selector fails to get link-only tweet content

---

.eslintrc.json
packages/maskbook/src/plugins/GoodGhosting/UI/TimelineTimer.tsx

closes #
for https://github.com/DimensionDev/Maskbook/pull/3845#pullrequestreview-721825104

chore: add no-var rule

---

packages/maskbook/src/plugins/Wallet/settings.ts

fix: gasnow throw error on mobile

---

packages/maskbook/src/components/InjectedComponents/BreakdownDialog.tsx
packages/maskbook/src/components/InjectedComponents/ToolboxHint.tsx
packages/maskbook/src/components/custom-ui.d.ts
packages/maskbook/src/components/shared/InjectedDialog.tsx
packages/maskbook/src/components/shared/ProviderIcon.tsx
packages/maskbook/src/extension/options-page/DashboardComponents/DatabasePreviewCard.tsx
packages/maskbook/src/extension/options-page/DashboardComponents/FixedTokenList.tsx
packages/maskbook/src/extension/options-page/DashboardComponents/ProviderLine.tsx
packages/maskbook/src/extension/options-page/DashboardComponents/RestoreBox.tsx
packages/maskbook/src/extension/options-page/DashboardComponents/WalletAssetsTable.tsx
packages/maskbook/src/extension/options-page/DashboardRouters/Setup.tsx
packages/maskbook/src/plugins/Airdrop/SNSAdaptor/ClaimDialog.tsx
packages/maskbook/src/plugins/PoolTogether/UI/CountdownView.tsx
packages/maskbook/src/plugins/Trader/SNSAdaptor/trader/TradeSummary.tsx
packages/maskbook/src/plugins/Trader/SNSAdaptor/uniswap/TradeRoute.tsx
packages/maskbook/src/social-network/types.ts
packages/maskbook/src/web3/UI/EthereumAccountButton.tsx
packages/shared/src/UI/UIHelper/custom-ui-helper.tsx
packages/shared/src/UI/UIHelper/custom-ui.d.ts
packages/shared/src/UI/components/TokenIcon/index.tsx

fix: classes in code

---

packages/maskbook/src/plugins/RedPacket/SNSAdaptor/RedPacket.tsx

fix: rp compatible

---

packages/maskbook/src/_locales/ja/messages.json
packages/maskbook/src/_locales/ko/messages.json
packages/maskbook/src/_locales/zh/messages.json

fix: sync keys

---

packages/maskbook/src/plugins/PoolTogether/UI/PoolView.tsx

fix(PoolTogether): tokenFaucets[].apr could be null

---

packages/maskbook/src/plugins/GoodGhosting/hooks/useGameInfo.ts

fix: update deps list

---

packages/maskbook/src/plugins/Collectible/apis/opensea.ts

fix: the wrong url

---

packages/maskbook/src/plugins/PoolTogether/UI/AccountPool.tsx
packages/maskbook/src/plugins/PoolTogether/UI/PoolsView.tsx

fix(PoolTogether): ui wrap in Account tab

---

packages/maskbook/webpack.config.ts

See https://github.com/webpack/webpack/issues/13930

chore: remove hot in webpack config

---

packages/maskbook/src/_locales/en/messages.json
packages/maskbook/src/plugins/MaskbookPluginWrapper.tsx
packages/maskbook/src/plugins/Snapshot/SNSAdaptor/LoadingFailCard.tsx
packages/maskbook/src/plugins/VCent/SNSAdaptor/TweetDialog.tsx
packages/maskbook/src/plugins/VCent/SNSAdaptor/index.tsx
packages/maskbook/src/social-network-adaptor/twitter.com/collecting/post.ts
packages/maskbook/src/social-network-adaptor/twitter.com/utils/selector.ts

fix: dup decryped box

---

packages/maskbook/src/plugins/PoolTogether/hooks/useDepositCallback.ts
packages/maskbook/src/plugins/Trader/trader/uniswap/useTradeCallback.ts
packages/maskbook/src/plugins/dHEDGE/hooks/useInvestCallback.ts

fix: gas is undefined

---

packages/maskbook/src/extension/background-script/EthereumServices/tokenList.ts
packages/web3-shared/src/hooks/useAssetsByTokenList.ts
packages/web3-shared/src/hooks/useAssetsFromChain.ts

fix: token list has duplicate token and incorrect balance

---

packages/maskbook/src/plugins/ITO/SNSAdaptor/CompositionDialog.tsx
packages/maskbook/src/plugins/PoolTogether/SNSAdaptor/index.tsx
packages/maskbook/src/plugins/dHEDGE/SNSAdaptor/index.tsx

Fix "Each child in a list should have a unique "key" prop."
closes #

fix: show react list key error

---

packages/maskbook/src/extension/background-script/EthereumServices/wallet.ts
packages/maskbook/src/extension/options-page/DashboardDialogs/Wallet/Rename.tsx
packages/maskbook/src/extension/options-page/DashboardRouters/Setup.tsx
packages/maskbook/src/plugins/Transak/Dashboard/index.tsx
packages/maskbook/src/plugins/Wallet/SNSAdaptor/RenameWalletDialog.tsx
packages/maskbook/src/plugins/Wallet/SNSAdaptor/RiskWarningDialog/index.tsx
packages/maskbook/src/plugins/Wallet/hooks/useWalletRiskWarningDialog.ts
packages/maskbook/src/plugins/Wallet/services/cloud.ts
packages/maskbook/src/plugins/Wallet/services/wallet.ts

fix: the wrong context

---

packages/maskbook/src/plugins/PoolTogether/hooks/useAccountBalances.ts

fix: account is absent

---

packages/maskbook/src/_locales/en/messages.json
packages/maskbook/src/_locales/ja/messages.json
packages/maskbook/src/_locales/ko/messages.json
packages/maskbook/src/_locales/zh/messages.json
packages/maskbook/src/plugins/Wallet/SNSAdaptor/RiskWarningDialog/index.tsx

refactor: use promise button when send risk confirm request

---

packages/maskbook/src/plugins/GoodGhosting/hooks/useGameInfo.ts
packages/maskbook/src/web3/UI/EthereumChainBoundary.tsx

fix: invalid address in good ghosting when delete wallet

---

packages/maskbook/src/plugins/Trader/apis/trending/hotfix.ts

fix: mask token on polygon

---

packages/maskbook/src/extension/background-script/EthereumServices/provider.ts
packages/maskbook/src/extension/background-script/EthereumServices/providers/MetaMask.ts
packages/maskbook/src/plugins/Wallet/settings.ts
packages/maskbook/src/web3/UI/EthereumWalletConnectedBoundary.tsx

fix: unlock metamask

---

packages/maskbook/src/plugins/Wallet/SNSAdaptor/TransactionDialog.tsx

fix: format tx err msg

---

packages/maskbook/src/components/InjectedComponents/PostDialog.tsx

chore: post dialog plugin order

---

packages/maskbook/src/_locales/en/messages.json
packages/maskbook/src/_locales/ja/messages.json
packages/maskbook/src/_locales/ko/messages.json
packages/maskbook/src/_locales/zh/messages.json
packages/maskbook/src/extension/options-page/DashboardComponents/Drawer.tsx

feat: add join us link on dashboard

---

packages/maskbook/src/plugins/Wallet/services/cloud.ts

feat: add backend product link for risk confirm

---

packages/maskbook/src/plugins/Collectible/hooks/useAsset.ts

fix: absence name of collectilbe from opensea

---

packages/maskbook/src/plugins/ITO/SNSAdaptor/index.tsx

fix: ito add EthereumChainBoundary

---

packages/maskbook/src/_locales/en/messages.json
packages/maskbook/src/_locales/ja/messages.json
packages/maskbook/src/_locales/ko/messages.json
packages/maskbook/src/_locales/zh/messages.json
packages/maskbook/src/plugins/GoodGhosting/UI/GameActionDialog.tsx

Improve on previous [PR](https://github.com/DimensionDev/Maskbook/pull/3570) and [PR](https://github.com/DimensionDev/Maskbook/pull/3815) that close #3337 
Check that the wallet has sufficient balance before allowing the user to join a game or make a deposit

feat: add sufficient balance check to the good ghosting plugin

---

packages/maskbook/src/extension/options-page/DashboardComponents/FixedTokenList.tsx
packages/web3-constants/data/token.json
packages/web3-shared/src/utils/token.ts

feat: add mask token to matic and bsc

---

packages/theme/package.json
pnpm-lock.yaml

fix: css breaks

---

packages/scripts/src/locale-kit/utils.ts

fix: ci locale-kit

---

packages/maskbook/src/plugins/Trader/apis/trader/index.ts
packages/maskbook/src/plugins/Trader/settings.ts
packages/maskbook/src/plugins/Trader/trending/useCurrentTradeProvider.ts
packages/maskbook/src/utils/flags.ts
packages/web3-constants/data/red-packet.json
packages/web3-constants/data/trader.json

feat: uniswap v3 on arbitrum

---

packages/maskbook/src/plugins/Trader/apis/trader/index.ts
packages/maskbook/src/plugins/Trader/constants/uniswap.ts
packages/maskbook/src/plugins/Trader/settings.ts
packages/maskbook/src/plugins/Trader/trader/uniswap/useV2BestTrade.ts
packages/maskbook/src/plugins/Trader/trader/uniswap/useV3BestTrade.ts
packages/maskbook/src/plugins/Trader/trending/useCurrentTradeProvider.ts
packages/maskbook/src/utils/flags.ts
packages/web3-constants/data/ethereum.json
packages/web3-constants/data/red-packet.json
packages/web3-constants/data/trader.json
packages/web3-contracts/abis/Multicall.json
packages/web3-contracts/types/Multicall.d.ts
packages/web3-shared/src/hooks/useERC20TokenDetailed.ts
packages/web3-shared/src/hooks/useERC721TokenDetailed.ts
packages/web3-shared/src/hooks/useERC721TokensOfOwner.ts
packages/web3-shared/src/hooks/useMulticall.ts

+ [x] Deploy Contract on BSC
+ [x] Deploy Contract on Polygon

refactor: use uniswap multicall

---

packages/dashboard/src/pages/Wallets/components/TransactionIcon/index.tsx
packages/maskbook/src/extension/options-page/DashboardComponents/WalletContent.tsx
packages/maskbook/src/plugins/Wallet/pipes/index.ts
packages/maskbook/src/plugins/Wallet/services/transactions.ts
packages/web3-shared/src/types/index.ts

fix: transaction filter type is not working

---

packages/web3-shared/src/hooks/useERC20TokenDetailed.ts
packages/web3-shared/src/hooks/useERC721TokenDetailed.ts
packages/web3-shared/src/utils/call.ts
packages/web3-shared/src/utils/index.ts
pnpm-lock.yaml

refactor: useERC721TokenDetailed

---

packages/maskbook/src/utils/flags.ts

refactor: trun off arbitrum

---

packages/maskbook/src/social-network-adaptor/minds.com/base.ts

feat: enable minds.io under flag

---

packages/maskbook/src/plugins/Trader/apis/balancer/index.ts
packages/maskbook/src/plugins/Trader/trader/uniswap/useAllCommonPairs.ts
packages/maskbook/src/plugins/Trader/trader/useTradeContext.ts
packages/maskbook/src/plugins/Trader/types/trader.ts

fix: type error

---

packages/maskbook/src/plugins/Trader/helpers/uniswap.ts
packages/maskbook/src/web3/UI/TokenAmountPanel.tsx

fix: failed to input fraction number

---

packages/maskbook/src/plugins/Trader/SNSAdaptor/trader/SettingsDialog.tsx
packages/maskbook/src/plugins/Trader/constants/trader.ts

fix: the settings dialog

---

packages/maskbook/src/extension/browser-action/UI.tsx
packages/maskbook/src/utils/flags.ts
packages/maskbook/webpack.config.ts

chore: enable new dashboard under flag

---

netlify.toml
scripts/netlify.sh

fix: clean netlify cache

---

packages/maskbook/src/utils/native-rpc/Web.ts
packages/public-api/src/web.ts

fix: remove duplicated public-api
fix: modify `persona_disconnectProfile` method's params

Modify public-apis

---

packages/dashboard/src/components/FooterLine/index.tsx

refactor: improve footer line style in welcome page

---

packages/web3-contracts/compile-contracts.ts
pnpm-lock.yaml
scripts/netlify.sh

https://github.com/prettier/prettier/issues/6101
fix:
```
$ npx prettier --write * # cwd: packages/web3-contracts/types
[error] No parser could be inferred for file: .DS_Store
 ERROR  Command failed with exit code 2.
```

fix: prettier error

---

packages/maskbook/src/components/InjectedComponents/ToolboxHint.tsx
packages/maskbook/src/extension/background-script/EthereumServices/send.ts
packages/maskbook/src/locales/en-US.json
packages/maskbook/src/plugins/Wallet/hooks/useRecentTransactions.ts
packages/maskbook/src/plugins/Wallet/services/recentTransactions.ts
packages/plugins/Wallet/src/messages.ts

feat: reveal the count of pending transactions

---

packages/maskbook/src/extension/options-page/DashboardComponents/FixedTokenList.tsx
packages/web3-shared/src/hooks/useAssetsByTokenList.ts
packages/web3-shared/src/hooks/useERC20TokensDetailedFromTokenLists.ts
packages/web3-shared/src/utils/token.ts

feat: let the token picker loads tokens from DB

---

packages/maskbook/src/social-network-adaptor/twitter.com/injection/useEthereumName.ts

fix: update ens RegExp to match all valid ens address

---

packages/maskbook/src/social-network-adaptor/minds.com/injection/CommentBox.tsx
packages/maskbook/src/social-network-adaptor/minds.com/injection/PostDialogHint.tsx
packages/maskbook/src/social-network-adaptor/minds.com/injection/SetupPrompt.tsx
packages/maskbook/src/social-network-adaptor/minds.com/injection/ToolboxHint.tsx
packages/maskbook/src/social-network-adaptor/twitter.com/customization/custom.ts
packages/maskbook/src/social-network-adaptor/twitter.com/injection/PostDialogIcon.tsx
packages/maskbook/src/social-network-adaptor/twitter.com/injection/ToolboxHint.tsx
packages/maskbook/src/social-network-adaptor/twitter.com/ui-provider.ts
packages/maskbook/src/social-network/defaults/inject/CommentBox.tsx
packages/maskbook/src/social-network/defaults/inject/Comments.tsx
packages/maskbook/src/social-network/defaults/inject/PageInspector.tsx
packages/maskbook/src/social-network/defaults/inject/PostInspector.tsx
packages/maskbook/src/social-network/defaults/inject/PostReplacer.tsx
packages/maskbook/src/social-network/types.ts
packages/shared/src/UI/UIHelper/custom-ui-helper.tsx

refactor: migrate sns adaptors to new makeStyles

---

packages/maskbook/src/plugins/GoodGhosting/hooks/usePoolData.ts
packages/maskbook/src/plugins/ITO/SNSAdaptor/ITO.tsx
packages/maskbook/src/plugins/RedPacket/SNSAdaptor/RedPacketInHistoryList.tsx

chore: simplify big number

---

packages/maskbook/src/extension/background-script/EthereumServices/send.ts
packages/maskbook/src/plugins/Wallet/services/recentTransactions.ts
packages/maskbook/src/web3/helpers.ts
packages/web3-shared/src/contracts/useERC20TokenBytes32Contract.ts
packages/web3-shared/src/contracts/useERC20TokenContract.ts
packages/web3-shared/src/hooks/useContract.ts
packages/web3-shared/src/hooks/useERC20TokenDetailed.ts
packages/web3-shared/src/hooks/useWeb3.ts

+ Able to cache receipts for the recent transactions
+ Able to create read-only contract(s) (no need to sign the transaction)

refactor: the readonly contract

---

packages/maskbook/src/extension/popups/RequestPermission/utils.ts
packages/maskbook/src/extension/popups/SignRequest/utils.ts
packages/maskbook/src/extension/popups/ThirdPartyRequestPermission/utils.ts
packages/maskbook/src/extension/popups/components/InitialPlaceholder/index.tsx
packages/maskbook/src/extension/popups/components/PopupFrame/index.tsx
packages/maskbook/src/extension/popups/index.tsx
packages/maskbook/src/extension/popups/pages/Wallet/ImportWallet/index.tsx
packages/maskbook/src/extension/popups/pages/Wallet/SelectWallet/index.tsx
packages/maskbook/src/extension/popups/pages/Wallet/WalletSettings/index.tsx
packages/maskbook/src/extension/popups/pages/Wallet/components/AssetsList/index.tsx
packages/maskbook/src/extension/popups/pages/Wallet/components/StartUp/index.tsx
packages/maskbook/src/extension/popups/pages/Wallet/components/WalletAssets/index.tsx
packages/maskbook/src/extension/popups/pages/Wallet/components/WalletHeader/index.tsx
packages/maskbook/src/extension/popups/pages/Wallet/components/WalletInfo/index.tsx
packages/maskbook/src/extension/popups/pages/Wallet/index.tsx
packages/maskbook/src/extension/popups/render.tsx

refactor: rename DialogRoutes to PopupRoutes

---

packages/maskbook/src/extension/background-script/EthereumServices/network.ts
packages/maskbook/src/extension/background-script/EthereumServices/send.ts
packages/maskbook/src/plugins/Wallet/services/wallet.ts
packages/maskbook/src/utils/native-rpc/Web.ts
packages/public-api/src/mobile.ts
packages/public-api/src/types/index.ts
packages/public-api/src/web.ts
packages/web3-shared/src/hooks/useAccount.ts
packages/web3-shared/src/types/index.ts

+ add web3-core-helpers
+ flow RPC requests to the native app
closes #

feat: add send to the native apis

---

packages/dashboard/src/locales/index.ts
packages/maskbook/src/locales/index.ts
packages/maskbook/src/social-network-adaptor/twitter.com/locales/index.ts
packages/plugins/Wallet/src/locales/index.ts
packages/plugins/example/src/locales/index.ts
packages/scripts/src/locale-kit-next/index.ts
packages/shared/src/locales/index.ts

fix: language detect close #3446

---

packages/maskbook/src/social-network-adaptor/twitter.com/injection/useEthereumName.ts

fix(twitter): to avoid matching regular domain, ens regexp match common ens only

---

packages/dashboard/src/components/DashboardFrame/FeaturePromotions/index.tsx
packages/dashboard/src/pages/Labs/constants.ts

feat: improve dashboard feature promotions

---

packages/maskbook/src/social-network-adaptor/twitter.com/injection/EnhancedProfileTab.tsx

fix: wrong highlight color in DIM mode

---

packages/maskbook/src/database/post.ts
packages/maskbook/src/extension/background-script/CryptoServices/encryptTo.ts
packages/maskbook/src/extension/background-script/CryptoServices/getSharedListOfPost.ts
packages/maskbook/src/plugins/External/components/ExternalPluginRenderer.tsx
packages/maskbook/src/utils/type-transform/BackupFormat/JSON/DBRecord-JSON/PostRecord.ts
packages/maskbook/src/utils/type-transform/BackupFormat/JSON/version-2.ts

feat: add recipients everyone

---

packages/maskbook/src/extension/background-script/EthereumServices/send.ts
packages/maskbook/src/extension/background-script/HelperService.ts

feat: add open popups service function

---

packages/maskbook/src/components/CompositionDialog/Composition.tsx

regression introduced by #4074

fix: cannot open plugins from side bar

---

packages/web3-shared/src/assets/chains.json

feat: add arbitrum network logo

---

packages/maskbook/src/social-network-adaptor/twitter.com/utils/selector.ts

fix: 'nfts' tab shouldn't appear in notifications page

---

README.md
docs/i18n-guide.md

chore: add crowdin badge

---

packages/maskbook/src/extension/background-script/HelperService/index.ts
packages/maskbook/src/plugins/GoodGhosting/hooks/useGameInfo.ts
packages/maskbook/src/plugins/Wallet/apis/coingecko.ts

closes #4111 
fix GoodGhosting

fix(Firefox): use helper service fetch

---

packages/maskbook/src/plugins/GoodGhosting/utils.ts

fix(Firefox): gameAsset undefined

---

packages/dashboard/src/components/Restore/CodeValidation.tsx
packages/dashboard/src/components/Restore/steps/Commont.tsx
packages/dashboard/src/components/Restore/steps/EmailField.tsx
packages/dashboard/src/components/Restore/steps/PhoneField.tsx
packages/dashboard/src/components/Restore/steps/ValidationAccount.tsx
packages/dashboard/src/pages/Settings/api.ts
packages/dashboard/src/pages/Settings/components/dialogs/CloudBackupVerifyDialog.tsx
packages/dashboard/src/pages/Settings/components/dialogs/SettingEmailDialog.tsx
packages/dashboard/src/pages/Settings/components/dialogs/SettingPhoneNumberDialog.tsx
packages/dashboard/src/pages/Settings/type.ts

feat: add scenario & locale for send_code api

---

packages/dashboard/src/pages/Settings/components/dialogs/BackupDialog.tsx
packages/maskbook/src/extension/background-script/WelcomeService.ts

feat: encrypt local backup

---

packages/backup-format/README.md
packages/backup-format/package.json
packages/backup-format/src/BackupErrors.ts
packages/backup-format/src/container/index.ts
packages/backup-format/src/index.ts
packages/backup-format/src/v3-EncryptedJSON/index.ts
packages/backup-format/tsconfig.json
packages/empty/package.json
pnpm-lock.yaml
pnpm-workspace.yaml

feat: add encrypt backup

---

packages/web3-shared/src/assets/chains.json

feat: add xdai token icon

---

packages/maskbook/src/plugins/Trader/apis/trending/hotfix.ts
packages/maskbook/src/plugins/Trader/services.ts
packages/maskbook/src/utils/native-rpc/Web.ts
packages/web3-constants/data/token.json

fix: arbitrum

---

packages/maskbook/src/extension/options-page/DashboardComponents/TransactionList/Record.tsx
packages/maskbook/src/extension/options-page/DashboardRouters/Setup.tsx
packages/maskbook/src/plugins/Trader/SNSAdaptor/trending/TraderView.tsx
packages/maskbook/src/plugins/Trader/SNSAdaptor/trending/TrendingCard.tsx
packages/maskbook/src/web3/UI/SelectTokenChip.tsx
packages/shared/src/UI/components/TokenIcon/index.tsx

fix(ui): css injection seq changed

---

packages/maskbook/src/components/InjectedComponents/EnhancedProfile.tsx
packages/maskbook/src/plugins/ITO/SNSAdaptor/CompositionDialog.tsx
packages/maskbook/src/plugins/ITO/SNSAdaptor/SwapGuide.tsx
packages/maskbook/src/plugins/RedPacket/SNSAdaptor/RedPacketDialog.tsx
packages/maskbook/src/plugins/Transak/SNSAdaptor/BuyTokenDialog.tsx
packages/maskbook/src/social-network-adaptor/twitter.com/injection/EnhancedProfileTab.tsx
packages/maskbook/src/social-network-adaptor/twitter.com/ui-provider.ts

fix: some style bugs

---

packages/dashboard/src/web3/context.ts
packages/maskbook/src/extension/options-page/DashboardComponents/CollectibleList/index.tsx
packages/maskbook/src/extension/options-page/DashboardComponents/WalletAssetsTable.tsx
packages/maskbook/src/plugins/Wallet/services/assets.ts
packages/maskbook/src/web3/context.ts
packages/web3-shared/src/context/type.ts
packages/web3-shared/src/hooks/useAssetsFromChain.ts
packages/web3-shared/src/hooks/useAssetsFromProvider.ts

fix: assets list on arb

---

packages/maskbook/src/plugins/Trader/helpers/uniswap.ts

fix: uniswap error message

---

packages/maskbook/src/plugins/Snapshot/SNSAdaptor/VotesCard.tsx
packages/maskbook/src/plugins/Snapshot/Worker/apis/index.ts
packages/maskbook/src/plugins/Snapshot/types.ts

fix: snapshot api

---

packages/maskbook/src/plugins/RedPacket/SNSAdaptor/RedPacketForm.tsx
packages/maskbook/src/web3/UI/TokenAmountPanel.tsx

chore: token panel max

---

packages/maskbook/src/extension/background-script/EthereumServices/request.ts

refactor: simpliy request method

---

packages/maskbook/src/plugins/Trader/SNSAdaptor/trending/SearchResultInspector.tsx
packages/maskbook/src/plugins/Trader/SNSAdaptor/trending/TraderView.tsx
packages/maskbook/src/plugins/Trader/apis/trending/index.ts
packages/maskbook/src/plugins/Trader/trending/useCurrentCurrency.ts
packages/maskbook/src/plugins/Trader/trending/useCurrentDataProvider.ts
packages/maskbook/src/plugins/Trader/trending/useTrending.ts
packages/maskbook/src/settings/createSettings.ts
packages/maskbook/src/social-network-adaptor/twitter.com/utils/selector.ts

fix: dup requests

---

packages/maskbook/src/plugins/Collectible/SNSAdaptor/OfferTab.tsx
packages/maskbook/src/plugins/Collectible/SNSAdaptor/OrderRow.tsx
packages/maskbook/src/plugins/Collectible/hooks/useOrders.ts
packages/maskbook/src/plugins/Collectible/types/index.ts
packages/maskbook/src/plugins/Collectible/utils.ts

fix: collectibles plugin offers sorting and icon

---

packages/maskbook/src/plugins/Wallet/services/assets.ts

fix: the NFT filter logic

---

packages/injected-script/main/locationChange.ts
packages/maskbook/src/components/InjectedComponents/EnhancedProfile.tsx
packages/maskbook/src/components/InjectedComponents/EnhancedProfileTab.tsx
packages/maskbook/src/social-network-adaptor/twitter.com/injection/EnhancedProfileTab.tsx

fix: NFT wall on Firefox

---

packages/maskbook/src/components/InjectedComponents/EnhancedProfile.tsx
packages/maskbook/src/social-network-adaptor/twitter.com/injection/EnhancedProfileTab.tsx
packages/maskbook/src/social-network-adaptor/twitter.com/injection/useEthereumName.ts
packages/web3-shared/src/hooks/useResolveENS.ts
packages/web3-shared/src/hooks/useResolveUNS.ts

fix: resolve ENS when both an address exists

---

packages/maskbook/src/plugins/ITO/SNSAdaptor/ClaimAllDialog.tsx

chore: claim all xdai arbitrum

---

packages/maskbook/src/plugins/UnlockProtocol/SNSAdaptor/UnlockProtocolDialog.tsx
packages/maskbook/src/plugins/UnlockProtocol/Services.ts

fix: random chain lock select

---

packages/maskbook/src/plugins/Wallet/settings.ts

chore: add currentIsMaskWalletLockedSettings

---

packages/dashboard/src/locales/en-US.json
packages/dashboard/src/pages/Personas/components/PersonaCard/Row.tsx
packages/dashboard/src/pages/Personas/components/PersonaCard/index.tsx
packages/dashboard/src/pages/Personas/components/RenameDialog/index.tsx
packages/maskbook/src/database/Persona/helpers.ts

feat: rename persona

---

packages/maskbook/src/plugins/ITO/SNSAdaptor/SwapGuide.tsx
packages/web3-constants/data/ito.json

fix: ito style and typo

---

packages/web3-shared/src/hooks/useERC721TokenDetailedOwnerAllList.ts
packages/web3-shared/src/hooks/useERC721TokenDetailedOwnerList.ts

Fetch all assets from opensea rather than from one specific contract.

chore: useERC721TokenDetailedOwnerAllList

---

packages/dashboard/src/locales/en-US.json
packages/dashboard/src/pages/Personas/components/DisconnectProfileDialog/index.tsx
packages/dashboard/src/pages/Personas/components/PersonaCard/Row.tsx
packages/dashboard/src/pages/Personas/components/PersonaCard/index.tsx
packages/dashboard/src/pages/Personas/components/PersonaDrawer/index.tsx
packages/dashboard/src/pages/Personas/components/PersonaLine/index.tsx
packages/dashboard/src/pages/Personas/components/RenameDialog/index.tsx
packages/dashboard/src/pages/Personas/hooks/useConnectSocialNetwork.ts
packages/dashboard/src/pages/Personas/hooks/usePersonaContext.ts
packages/dashboard/src/pages/Settings/components/BackupSetting.tsx
packages/dashboard/stories/components/Persona/ConnectedPersonaLine.tsx
packages/maskbook/src/extension/background-script/SocialNetworkService.ts
packages/maskbook/src/social-network-adaptor/facebook.com/shared.ts
packages/maskbook/src/social-network-adaptor/instagram.com/shared.ts
packages/maskbook/src/social-network-adaptor/minds.com/shared.ts
packages/maskbook/src/social-network-adaptor/twitter.com/shared.ts
packages/maskbook/src/social-network/types.ts
packages/shared/src/utils/formatter.ts
packages/shared/src/utils/index.ts

1. Should show global backup submenu in persona setting menu
2. Persona tab bar add restore button
3. Show all twitter profile that had connected
4. Should open backup dialog when goto setting from persona global backup button

feat: should show global backup submenu in persona setting menu

---

packages/maskbook/src/locales/en-US.json
packages/maskbook/src/locales/ja-JP.json
packages/maskbook/src/locales/ko-KR.json
packages/maskbook/src/locales/qya-AA.json
packages/maskbook/src/locales/zh-TW.json
packages/maskbook/src/plugins/ITO/SNSAdaptor/PoolInList.tsx
packages/maskbook/src/plugins/RedPacket/SNSAdaptor/RedPacketInHistoryList.tsx
packages/maskbook/src/plugins/RedPacket/SNSAdaptor/hooks/useAvailabilityComputed.ts

fix: rp history check password

---

packages/scripts/src/bin/build.ts
packages/scripts/src/bin/dev.ts

fix: type check issue

---

packages/maskbook/src/extension/options-page/DashboardComponents/SearchInput.tsx
packages/maskbook/src/plugins/PoolTogether/UI/DepositDialog.tsx
packages/maskbook/src/plugins/Trader/trader/uniswap/useTradeParameters.ts
packages/maskbook/src/plugins/UnlockProtocol/SNSAdaptor/UnlockProtocolInPost.tsx
packages/maskbook/src/plugins/dHEDGE/UI/InvestDialog.tsx

fix: uniswap v3 & arbitrum

---

packages/maskbook/src/social-network-adaptor/twitter.com/injection/useEthereumName.ts
packages/maskbook/src/social-network-adaptor/twitter.com/utils/fetch.ts
packages/maskbook/src/social-network-adaptor/twitter.com/utils/user.ts

Test on https://twitter.com/AinuxA

fix: support non-ASCII ens

---

packages/maskbook/src/components/InjectedComponents/EnhancedProfile.tsx
packages/maskbook/src/extension/background-script/EthereumServices/providers/MetaMask.ts
packages/maskbook/src/extension/background-script/EthereumServices/send.ts
packages/maskbook/src/extension/background-script/EthereumServices/web3.ts
packages/maskbook/src/extension/options-page/DashboardComponents/CollectibleList/CollectibleCard.tsx
packages/maskbook/src/extension/options-page/DashboardComponents/CollectibleList/index.tsx
packages/maskbook/src/extension/options-page/DashboardDialogs/Wallet/TransferTab.tsx
packages/maskbook/src/plugins/Trader/SNSAdaptor/uniswap/TradeRoute.tsx
packages/maskbook/src/plugins/Trader/apis/0x/index.ts
packages/maskbook/src/plugins/Wallet/SNSAdaptor/ConnectWalletDialog/ConnectionProgress.tsx
packages/maskbook/src/plugins/Wallet/services/assets.ts
packages/maskbook/src/social-network-adaptor/twitter.com/injection/useEthereumName.ts

fix: trivial bugs

---

packages/dashboard/src/locales/en-US.json
packages/dashboard/src/pages/Personas/components/DeletePersonaDialog/index.tsx

feat: dashboard safe delete persona

---

packages/maskbook/src/extension/background-script/EthereumServices/send.ts

refactor: read-only methods

---

packages/dashboard/src/pages/Wallets/components/ReceiveDialog/index.tsx
packages/maskbook/src/plugins/Collectible/hooks/useEvents.ts
packages/maskbook/src/plugins/Collectible/pipes/index.ts
packages/maskbook/src/plugins/Trader/pipes.ts
packages/maskbook/src/plugins/Wallet/pipes/index.ts
packages/web3-shared/src/pipes/index.ts
packages/web3-shared/src/utils/chainDetailed.ts
packages/web3-shared/src/utils/enum.ts
packages/web3-shared/src/utils/index.ts

refactor: lookup table resolver

---

packages/dashboard/src/web3/context.ts
packages/maskbook/src/web3/context.ts

fix: listener leak

---

packages/dashboard/src/pages/Settings/components/BackupSetting.tsx
packages/dashboard/src/pages/Wallets/components/TokenTable/index.tsx
packages/dashboard/src/pages/Wallets/components/TokenTableRow/index.tsx
packages/dashboard/src/pages/Wallets/components/Transfer/index.tsx

feat: dashboard asset table operations

---

packages/maskbook/src/plugins/Wallet/SNSAdaptor/ConnectWalletDialog/index.tsx

fix: throw error if connection was rejected

---

packages/maskbook/src/components/CompositionDialog/useSubmit.ts
packages/maskbook/src/settings/settings.ts

fix: `useSubmit` should capture `whoAmI`

---

packages/dashboard/src/pages/Wallets/components/Transfer/index.tsx

fix: transfer type error

---

packages/maskbook/src/database/post.ts

feat: support post order by create time

---

packages/dashboard/src/components/PasswordField/index.tsx
packages/dashboard/src/pages/Settings/components/dialogs/SettingPasswordDialog.tsx
packages/theme/src/Components/TextField/index.tsx

feat: password visibility

---

packages/dashboard/src/components/DashboardFrame/Navigation.tsx
packages/dashboard/src/locales/en-US.json
packages/dashboard/src/pages/Wallets/components/HistoryTableRow/index.tsx
packages/dashboard/src/pages/Wallets/components/TokenAssets/index.tsx
packages/dashboard/src/pages/Wallets/components/TransactionIcon/index.tsx
packages/dashboard/src/pages/Wallets/components/Transfer/index.tsx
packages/dashboard/src/pages/Wallets/index.tsx
packages/dashboard/stories/components/Wallet/TransactionIcon.ts
packages/icons/general/Upload.tsx
packages/web3-shared/src/types/index.ts

feat: improve dashboard wallet history

---

packages/dashboard/src/pages/Settings/components/BackupContentSelector.tsx

refactor: update checkbox icons

---

packages/maskbook/src/plugins/RedPacket/SNSAdaptor/RedPacket.tsx
packages/maskbook/src/plugins/RedPacket/SNSAdaptor/RedPacketConfirmDialog.tsx

chore: rp maintain style

---

packages/maskbook/src/components/InjectedComponents/NFT/NFTAvatar.tsx
packages/maskbook/src/components/InjectedComponents/NFT/NFTBadge.tsx
packages/maskbook/src/extension/options-page/DashboardDialogs/Avatar/confirm.tsx
packages/maskbook/src/extension/options-page/DashboardDialogs/Avatar/index.tsx
packages/maskbook/src/extension/options-page/DashboardRouters/NFTAvatarList.tsx
packages/maskbook/src/extension/options-page/DashboardRouters/Settings.tsx
packages/maskbook/src/extension/options-page/Route.ts
packages/maskbook/src/extension/options-page/index.tsx
packages/maskbook/src/locales/en-US.json
packages/maskbook/src/social-network-adaptor/twitter.com/injection/NFT/NFTAvatarInTwitter.tsx
packages/maskbook/src/social-network/ui.ts

feat: show nft avatar whitelist

---

packages/maskbook/src/components/shared/InjectedDialog.tsx
packages/maskbook/src/social-network-adaptor/twitter.com/utils/selector.ts

fix(twitter): wrong colors on mobile mode

---

packages/maskbook/src/plugins/Collectible/apis/opensea.ts
packages/maskbook/src/plugins/Collectible/pipes/index.ts
packages/maskbook/src/plugins/Trader/trader/0x/useTrade.ts
packages/maskbook/src/plugins/Wallet/database/Plugin.db.ts
packages/maskbook/src/plugins/Wallet/database/decrypt.ts
packages/maskbook/src/plugins/Wallet/services/addressBook.ts
packages/maskbook/src/plugins/Wallet/services/recentTransactions/database.ts

refactor: database and code style

---

packages/dashboard/src/components/DashboardFrame/FeaturePromotions/index.tsx
packages/dashboard/src/pages/Wallets/components/TokenTableRow/index.tsx
packages/dashboard/src/pages/Wallets/components/WalletStateBar/index.tsx
packages/web3-shared/src/utils/chainDetailed.ts

fix: improve dashboard wallet

---

packages/dashboard/src/locales/en-US.json
packages/dashboard/src/pages/Wallets/components/Balance/index.tsx
packages/dashboard/src/pages/Wallets/components/HistoryTableRow/index.tsx
packages/dashboard/src/pages/Wallets/components/TokenTable/index.tsx
packages/dashboard/src/pages/Wallets/components/TransactionIcon/index.tsx
packages/dashboard/src/pages/Wallets/index.tsx
packages/dashboard/stories/components/Wallet/TokenTable.tsx
packages/maskbook/src/plugins/Wallet/services/assets.ts
packages/web3-shared/src/types/index.ts

feat: show asset in dashboard wallet by network

---

packages/maskbook/src/extension/options-page/DashboardComponents/InputBox.tsx
packages/maskbook/src/plugins/ITO/SNSAdaptor/ClaimAllDialog.tsx
packages/maskbook/src/plugins/ITO/SNSAdaptor/NftAirdropCard.tsx
packages/maskbook/src/plugins/ITO/SNSAdaptor/SwapGuide.tsx

fix: style

---

packages/dashboard/src/pages/Personas/hooks/useContacts.ts
packages/dashboard/src/pages/Personas/hooks/usePostHistory.ts

fix: should refresh post and contact when change persona

---

packages/maskbook/src/plugins/Trader/apis/trending/hotfix.ts

fix: arbitrum network id

---

packages/maskbook/src/extension/background-script/EthereumServices/request.ts

refactor: defer rpc result in confirmRequest

---

packages/dashboard/src/web3/context.ts
packages/maskbook/src/web3/context.ts

fix: subscription is not working

---

packages/maskbook/src/extension/background-script/EthereumServices/send.ts
packages/maskbook/src/plugins/Trader/trader/uniswap/useTradeCallback.ts
packages/web3-constants/data/token.json
packages/web3-shared/src/assets/chains.json

fix: uniswap v3 on arbitrum

---

packages/maskbook/src/extension/background-script/EthereumServices/send.ts
packages/maskbook/src/extension/popups/pages/Wallet/ContractInteraction/index.tsx
packages/maskbook/src/utils/flags.ts
packages/web3-shared/src/assets/chains.json
packages/web3-shared/src/hooks/useChainEIP1159Supported.ts
packages/web3-shared/src/types/index.ts
packages/web3-shared/src/utils/chainDetailed.ts
packages/web3-shared/src/utils/transaction.ts

fix: typo of EIP1559

---

packages/dashboard/src/pages/Settings/components/dialogs/SettingEmailDialog.tsx
packages/dashboard/src/pages/Settings/components/dialogs/SettingPhoneNumberDialog.tsx

fix: empty email & phone check

---

packages/maskbook/src/components/InjectedComponents/ToolboxHint.tsx
packages/maskbook/src/components/Welcomes/Banner.tsx
packages/maskbook/src/plugins/Wallet/services/account.ts
packages/maskbook/src/utils/native-rpc/Web.ts
packages/maskbook/src/web3/UI/EthereumChainBoundary.tsx
packages/public-api/src/mobile.ts
packages/public-api/src/web.ts

feat: add native apis

---

package-overrides/xhr2-cookies/index.cjs
package-overrides/xhr2-cookies/index.mjs
package-overrides/xhr2-cookies/package.json
package.json
packages/dashboard/.storybook/main.js
packages/dashboard/.storybook/preview.js
packages/dashboard/package.json
packages/theme/.storybook/main.cjs
packages/theme/.storybook/preview.js
packages/theme/package.json
packages/web3-shared/src/constants/index.ts
pnpm-lock.yaml

feat: upgrade sb to webpack 5

---

packages/maskbook/src/components/InjectedComponents/ToolboxHint.tsx

fix: do not open JS wallet dialog on mobile

---

packages/maskbook/src/database/post.ts

fix: post db

---

packages/dashboard/src/pages/Settings/components/BackupContentSelector.tsx
packages/dashboard/src/pages/Settings/components/dialogs/BackupDialog.tsx
packages/dashboard/src/pages/Settings/components/dialogs/SettingPasswordDialog.tsx

style: 16px margin between components

---

packages/maskbook/src/components/InjectedComponents/EnhancedProfile.tsx
packages/web3-shared/src/hooks/useResolveENS.ts
packages/web3-shared/src/hooks/useWeb3.ts

Error: ENS is not supported on network private at ENS.checkNetwork
https://github.com/ChainSafe/web3.js/issues/3787

fix: ens network

---

packages/web3-constants/data/rpc.json

chore: revert rpc

---

packages/maskbook/src/plugins/Wallet/apis/nftscan.ts

chore: api token id

---

packages/maskbook/package.json
packages/maskbook/webpack.config.ts
pnpm-lock.yaml

chore: replace `webpack-extension-manifest-plugin`

---

packages/maskbook/src/plugins/ITO/SNSAdaptor/hooks/useSpaceStationContractClaimCallback.ts

fix: nft airdrop

---

packages/dashboard/src/pages/Settings/components/dialogs/BackupDialog.tsx

fix: use PasswordField component

---

packages/maskbook/src/components/InjectedComponents/NFT/hooks/useNFT.ts
packages/maskbook/src/plugins/ITO/SNSAdaptor/NftAirdropCard.tsx

fix: too many requests emitted by NFT avatars

---

packages/dashboard/src/pages/Wallets/components/Transfer/TransferERC20.tsx

fix(Wallet): fix amount checking, compare to maxAmount

---

packages/maskbook/src/plugins/Gitcoin/SNSAdaptor/index.tsx

fix: gitcoin only works on mainnet

---

packages/maskbook/src/plugins/ITO/SNSAdaptor/ClaimAllDialog.tsx
packages/maskbook/src/plugins/ITO/SNSAdaptor/NftAirdropCard.tsx
packages/maskbook/src/web3/UI/EthereumWalletConnectedBoundary.tsx

Since there's an nft airdrop card under matic tab
closes #

chore: show switch button

---

packages/maskbook/src/plugins/ITO/SNSAdaptor/ClaimAllDialog.tsx

chore: nft airdrop text style

---

packages/dashboard/src/pages/Settings/components/dialogs/BackupModeSelectDialog.tsx
packages/theme/src/component-changes.ts

1. dialog background color
2. backup mode disabled style

style: dark mode dialog

---

packages/maskbook/src/social-network-adaptor/twitter.com/injection/useEthereumName.ts

fix: ens match

---

packages/dashboard/src/components/Restore/RestoreFromLocal.tsx
packages/maskbook/src/extension/background-script/WelcomeServices/restoreBackup.ts
packages/maskbook/src/plugins/Wallet/services/account.ts
packages/maskbook/src/plugins/Wallet/services/wallet/database/wallet.ts
packages/web3-shared/src/hooks/useWallet.ts

fix: wallet DB

---

packages/maskbook/src/plugins/Wallet/services/wallet/database/secret.ts

fix: decrypt secret error

---

packages/dashboard/src/pages/Wallets/components/WalletStateBar/index.tsx
packages/maskbook/src/extension/popups/components/PopupFrame/index.tsx
packages/maskbook/src/extension/popups/components/WalletStateBar/index.tsx
packages/maskbook/src/extension/popups/index.tsx
packages/maskbook/src/extension/popups/pages/Swap/SwapBox/index.tsx
packages/maskbook/src/extension/popups/pages/Swap/index.tsx
packages/maskbook/src/extension/popups/pages/Wallet/SelectWallet/index.tsx
packages/maskbook/src/extension/popups/render.tsx
packages/maskbook/src/locales/en-US.json
packages/maskbook/src/plugins/Trader/SNSAdaptor/trader/TradeForm.tsx
packages/maskbook/src/web3/context.ts
pnpm-lock.yaml

feat(popups): add Swap page

---

.github/workflows/bot.yml
.github/workflows/compile.yml
.github/workflows/linters.yml
.github/workflows/netlify.yml
.github/workflows/spell-checking.yml
cspell.json
packages/maskbook/src/plugins/Wallet/services/wallet/index.ts
packages/web3-shared/src/hooks/useWallet.ts

chore: update gh actions

---

packages/maskbook/webpack.config.ts

chore: create a shallow copy of manifest for modifying

---

packages/dashboard/src/pages/Personas/components/ContactTableRow/index.tsx
packages/dashboard/src/pages/Personas/components/ContactsTable/index.tsx
packages/dashboard/src/pages/Personas/components/EmptyContactPlaceholder/index.tsx
packages/dashboard/src/pages/Personas/components/PostHistory/index.tsx
packages/dashboard/src/pages/Personas/hooks/usePostHistory.ts
packages/maskbook/src/components/CompositionDialog/useSubmit.ts
packages/maskbook/src/database/Persona/Persona.db.ts
packages/maskbook/src/database/post.ts
packages/maskbook/src/extension/background-script/IdentityService.ts
packages/maskbook/src/social-network-adaptor/twitter.com/collecting/post.ts

feat: post history only show current profile network

---

packages/maskbook/src-workers/prepare.ts
packages/maskbook/src-workers/wallet.ts
packages/maskbook/src/plugins/Wallet/services/wallet/maskwallet/index.ts
packages/maskbook/tsconfig.json
packages/maskbook/tsconfig.worker.json

feat: run wasm in worker

---

packages/maskbook/src/components/InjectedComponents/ToolboxHint.tsx

fixup! feat: add a new custom snackbar (#4462)

---

packages/maskbook/src/extension/popups/pages/Wallet/GasSetting/GasSetting1559.tsx
packages/maskbook/src/extension/popups/pages/Wallet/GasSetting/Prior1559GasSetting.tsx
packages/maskbook/src/extension/popups/pages/Wallet/Transfer/Transfer1559.tsx

fix: the gas price usd in popup

---

packages/dashboard/src/pages/Wallets/components/Transfer/TransferERC20.tsx

fix: should change token when change network on transfer

---

packages/maskbook/src/extension/popups/components/WalletStateBar/index.tsx
packages/maskbook/src/extension/popups/pages/Swap/index.tsx

fix(ui): some small style

---

packages/maskbook/src/plugins/ITO/SNSAdaptor/ClaimAllDialog.tsx

fix: claim all box style

---

packages/maskbook/src/manifest.json
packages/maskbook/src/social-network-adaptor/browser-action/index.ts
packages/maskbook/src/utils/flags.ts

feat: enable popup in production

---

packages/maskbook/src/extension/options-page/DashboardComponents/InputBox.tsx
packages/maskbook/src/extension/popups/RequestPermission/RequestPermission.tsx
packages/maskbook/src/plugins/RedPacket/SNSAdaptor/SelectNftTokenDialog.tsx

fix: remove form tag

---

packages/maskbook/src/extension/popups/RequestPermission/RequestPermission.tsx
packages/maskbook/src/extension/popups/pages/Wallet/Unlock/index.tsx
packages/maskbook/src/extension/popups/pages/Wallet/components/DeriveWalletTable/index.tsx
packages/maskbook/src/extension/popups/pages/Wallet/index.tsx
packages/maskbook/src/plugins/Wallet/services/wallet/locker.ts

fix: popups bug

---

packages/maskbook/src/extension/background-script/HelperService/index.ts

firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1271047

fix: firefox popup position

---

packages/dashboard/src/pages/Settings/components/dialogs/SettingPhoneNumberDialog.tsx
packages/dashboard/src/pages/Settings/regexp.ts

fix: phone

---

packages/maskbook/src/social-network-adaptor/twitter.com/collecting/post.ts

fix: get conrrect identifier when colleting contact

---

packages/dashboard/src/components/DashboardFrame/FeaturePromotions/index.tsx
packages/dashboard/src/components/DashboardFrame/index.tsx
packages/dashboard/src/components/Restore/RestoreFromLocal.tsx
packages/dashboard/src/components/Restore/steps/ConfirmBackupInfo.tsx
packages/dashboard/src/pages/Settings/components/dialogs/VerifyPasswordDialog.tsx
packages/dashboard/src/pages/Wallets/components/WalletStateBar/useNetworkSelector.tsx
packages/maskbook/src/extension/popups/pages/Wallet/ImportWallet/index.tsx

fix: dashboard bug fix

---

packages/maskbook/src/social-network-adaptor/facebook.com/automation/pasteToCommentBoxFacebook.ts
packages/maskbook/src/social-network-adaptor/facebook.com/ui-provider.ts
packages/maskbook/src/social-network/defaults/inject/CommentBox.tsx

fix: fb comment box style, close #4390
fix: cannot auto paste fb comment, close #4389

fix: comment feature on facebook

---

packages/maskbook/src/social-network-adaptor/minds.com/automation/AttachImageToComposition.ts

fix: minds auto paste

---

packages/dashboard/src/components/Restore/steps/ValidationAccount.tsx
packages/dashboard/src/pages/Settings/api.ts

fix: backup phone number

---

packages/maskbook/src/UIRoot.tsx
packages/maskbook/src/components/InjectedComponents/AutoPasteFailedDialog.tsx
packages/maskbook/src/components/InjectedComponents/PageInspector.tsx
packages/maskbook/src/components/InjectedComponents/ToolboxHint.tsx
packages/maskbook/src/extension/options-page/DashboardComponents/DashboardSnackbar.tsx
packages/maskbook/src/extension/options-page/DashboardComponents/ShowcaseBox.tsx
packages/maskbook/src/extension/options-page/DashboardDialogs/Backup/Backup.tsx
packages/maskbook/src/extension/options-page/DashboardDialogs/Backup/ConfirmBackup.tsx
packages/maskbook/src/extension/options-page/DashboardDialogs/Backup/SelectBackup.tsx
packages/maskbook/src/extension/options-page/DashboardDialogs/Persona/Import.tsx
packages/maskbook/src/extension/options-page/DashboardRouters/NFTAvatarList.tsx
packages/maskbook/src/extension/options-page/DashboardRouters/Setup.tsx
packages/maskbook/src/extension/popups/pages/Wallet/ImportWallet/index.tsx
packages/maskbook/src/plugins/Collectible/SNSAdaptor/CheckoutDialog.tsx
packages/maskbook/src/plugins/Collectible/SNSAdaptor/ListingByHighestBidCard.tsx
packages/maskbook/src/plugins/Collectible/SNSAdaptor/ListingByPriceCard.tsx
packages/maskbook/src/plugins/Collectible/SNSAdaptor/MakeOfferDialog.tsx
packages/maskbook/src/plugins/FileService/SNSAdaptor/MainDialog.tsx
packages/maskbook/src/plugins/FileService/SNSAdaptor/components/UploadDropArea.tsx
packages/maskbook/src/plugins/ITO/SNSAdaptor/ClaimAllDialog.tsx
packages/maskbook/src/plugins/ITO/SNSAdaptor/NftAirdropCard.tsx
packages/maskbook/src/plugins/RedPacket/SNSAdaptor/RedPacketNft.tsx
packages/maskbook/src/plugins/RedPacket/SNSAdaptor/RedpacketNftConfirmDialog.tsx
packages/maskbook/src/plugins/Wallet/SNSAdaptor/RiskWarningDialog/index.tsx
packages/maskbook/src/social-network-adaptor/twitter.com/injection/NFT/NFTAvatarInTwitter.tsx
packages/maskbook/src/utils/shadow-root/MaskInShadow.tsx
packages/maskbook/src/web3/UI/EthereumERC20TokenApprovedBoundary.tsx
packages/maskbook/src/web3/UI/EthereumERC721TokenApprovedBoundary.tsx
packages/shared/src/hooks/useSnackbarCallback.tsx
packages/theme/src/Components/Snackbar/index.tsx

| On light mode | On dark mode |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/1141198/135034391-fd3dcdb8-1b9d-4c77-ba48-3add2ae25c20.png) | ![image](https://user-images.githubusercontent.com/1141198/135034372-ee7a274b-4c4a-48ce-ba78-2b66e6f5b5fd.png) |

fix: make the custom snackbar as default

---

packages/maskbook/src/social-network-adaptor/twitter.com/utils/fetch.ts
packages/maskbook/src/social-network-adaptor/twitter.com/utils/user.ts
packages/maskbook/src/utils/collectNodeText.ts

fix: read profile name in retweeted tweet

---

packages/dashboard/src/pages/Settings/components/dialogs/SettingEmailDialog.tsx
packages/dashboard/src/pages/Settings/components/dialogs/SettingPhoneNumberDialog.tsx

feat: reupload cloud backup after  email & phone change success

---

packages/maskbook/src/social-network-adaptor/twitter.com/collecting/post.ts

fix: results of reset quoted tweets run into the first one

---

packages/dashboard/src/hooks/useGasOptions.ts
packages/maskbook/src/extension/popups/pages/Wallet/ContractInteraction/index.tsx
packages/maskbook/src/extension/popups/pages/Wallet/GasSetting/Prior1559GasSetting.tsx
packages/maskbook/src/extension/popups/pages/Wallet/GasSetting/useGasOptions.ts
packages/maskbook/src/plugins/Wallet/SNSAdaptor/GasSettingDialog/Prior1559GasSetting.tsx
packages/maskbook/src/plugins/Wallet/apis/debank.ts

fix: debank doesn't support querying by chainId

---

packages/maskbook/src/database/Persona/Persona.db.ts
packages/maskbook/src/extension/background-script/Jobs/DatabaseCleanup/CleanProfileAndAvatar.ts
packages/maskbook/src/extension/background-script/Jobs/index_hmr.ts

fix: contact pagination

---

packages/dashboard/src/pages/Settings/components/dialogs/BackupDialog.tsx
packages/dashboard/src/pages/Settings/components/dialogs/CloudBackupMergeDialog.tsx
packages/dashboard/src/pages/Settings/components/dialogs/CloudBackupVerifyDialog.tsx
packages/dashboard/src/pages/Settings/components/dialogs/SettingEmailDialog.tsx
packages/dashboard/src/pages/Settings/components/dialogs/SettingPasswordDialog.tsx
packages/dashboard/src/pages/Settings/components/dialogs/SettingPhoneNumberDialog.tsx

refactor: change to useCustomSnackbar

---

packages/dashboard/src/components/LoadingButton/index.tsx
packages/dashboard/src/pages/Personas/components/LogoutPersonaDialog/index.tsx
packages/dashboard/src/pages/Wallets/index.tsx

feat: improve wallet navigation

---

packages/dashboard/src/pages/Settings/components/dialogs/BackupModeSelectDialog.tsx

fix: cloud backup mode disabled style

---

packages/dashboard/src/pages/Settings/hooks/UserContext.tsx

feat: encode backup password

---

packages/maskbook/src/database/Persona/Persona.db.ts
packages/maskbook/src/social-network-adaptor/facebook.com/utils/getProfileIdentifier.ts
packages/maskbook/src/social-network-adaptor/minds.com/collecting/post.ts
packages/maskbook/src/social-network-adaptor/twitter.com/collecting/post.ts
packages/maskbook/src/social-network-adaptor/utils.ts

feat: minds facebook relation

---

packages/dashboard/src/locales/en-US.json

fix: backup password set notification text

---

packages/theme/src/Components/Snackbar/index.tsx

refactor: snackbar style

---

packages/maskbook/src/components/GuideStep/index.tsx
packages/maskbook/src/components/InjectedComponents/SetupGuide.tsx
packages/maskbook/src/settings/settings.ts

1. fix can't scroll
2. use browser.storage instead of localStorage

fix: user guide 

---

packages/maskbook/src/extension/background-script/EthereumServices/providers/MetaMask.ts
packages/maskbook/src/plugins/Wallet/services/recentTransactions/database.ts

Blocked by https://github.com/MetaMask/metamask-extension/issues/9174.
Part of #4474.

feat: support EIP-2831

---

package.json
packages/maskbook/.webpack/config.ts
packages/maskbook/package.json
packages/maskbook/src/background-service.ts
packages/maskbook/src/background-worker.ts
packages/maskbook/src/polyfill/web-apis/secp256k1.ts
pnpm-lock.yaml

feat(mv3): webpack setup (not working)

---

packages/mask/.webpack/manifest.ts

Similar to https://github.com/DimensionDev/Maskbook/issues/4449

fix(build): duplicate items in manifest.json#web_accessible_resources

---

packages/mask/src/plugins/Wallet/SNSAdaptor/SelectProviderDialog/index.tsx

fix: connect to mm & wc

---

packages/mask/src/plugins/PoolTogether/UI/PoolView.tsx

style: adjust PoolTogether UI

---

packages/mask/src/plugins/dHEDGE/UI/PerformanceChart.tsx

style: adjust dHEDGE chart in light mode

---

packages/mask/src/plugins/Wallet/SNSAdaptor/SelectNftContractDialog.tsx
packages/mask/src/plugins/Wallet/apis/nftscan.ts
packages/mask/src/plugins/Wallet/hooks/useNFTscanFindAssets.ts
packages/mask/src/web3/UI/ERC721ContractSelectPanel.tsx

fix: stop useless nftscan api call

---

packages/maskbook/src/components/InjectedComponents/ToolboxUnstyled.tsx
packages/maskbook/src/components/shared/MaskApplicationBox.tsx
packages/maskbook/src/components/shared/WalletIcon.tsx
packages/maskbook/src/components/shared/WalletStatusBox.tsx
packages/maskbook/src/plugins/ITO/SNSAdaptor/ClaimAllDialog.tsx
packages/maskbook/src/web3/UI/EthereumChainBoundary.tsx
packages/web3-shared/evm/utils/chainDetailed.ts

chore: hide unused entry

---

packages/mask/src/plugins/PoolTogether/UI/DepositDialog.tsx

fix: style issue in PoolTogether

---

packages/mask/src/database/helpers/openDB.ts
packages/mask/src/utils/messages.ts
packages/mask/src/utils/native-rpc/Web.ts
packages/public-api/src/web.ts

feat: close all idb on app suspended

---

packages/mask/src/utils/native-rpc/Web.ts

fix: circular references

---

packages/mask/src/plugins/RedPacket/SNSAdaptor/hooks/useAvailability.ts
packages/mask/src/plugins/RedPacket/SNSAdaptor/hooks/useAvailabilityComputed.ts

fix: remove useless rpc call

---

packages/mask/src/components/InjectedComponents/AutoPasteFailedDialog.tsx
packages/mask/src/utils/native-rpc/Web.ts
packages/public-api/src/web.ts

feat: add `persona_logout` and `persona_getOwnedPersonaInformation`

---

packages/mask/src/extension/background-script/EthereumServices/provider.ts
packages/mask/src/plugins/Wallet/SNSAdaptor/WalletConnectQRCodeDialog/index.tsx

fix: walletconnect connection failure

---

packages/mask/src/social-network-adaptor/twitter.com/collecting/getSearchedKeyword.ts

closes #4765
kill the if condition  and its works fine

fix(*): fix issue #4765

---

packages/mask/src/plugins/MaskBox/SNSAdaptor/components/ArticlesTab.tsx
packages/mask/src/plugins/MaskBox/SNSAdaptor/components/CountdownText/index.tsx
packages/mask/src/plugins/MaskBox/SNSAdaptor/components/CountdownText/useCountdown.ts
packages/mask/src/plugins/MaskBox/SNSAdaptor/components/DrawDialog.tsx
packages/mask/src/plugins/MaskBox/SNSAdaptor/components/PreviewCard.tsx
packages/mask/src/plugins/MaskBox/hooks/useContext.ts
packages/mask/src/plugins/MaskBox/hooks/useMaskBoxCreationSuccessEvent.ts
packages/mask/src/plugins/MaskBox/type.ts

fix(maskbox): fix some ui issues of maskbox plugin

---

.circleci/config.yml
.github/workflows/linters.yml
.github/workflows/netlify.yml
packages/injected-script/package.json
packages/mask-sdk/package.json
packages/polyfills/builder.mjs
packages/polyfills/package.json
packages/scripts/src/netlify/index.ts
packages/scripts/src/utils/task.ts
pnpm-lock.yaml
scripts/netlify.sh

fix: build with corepack and Node 17

---

packages/web3-shared/evm/hooks/useBalance.ts

fix: too many requests

---

packages/injected-script/main/SolanaBridge/index.ts
packages/injected-script/main/SolanaBridge/methods.ts
packages/injected-script/main/communicate.ts
packages/injected-script/main/solana-injected.d.ts
packages/injected-script/sdk/bridgedSolana.ts
packages/injected-script/sdk/index.ts
packages/injected-script/sdk/tsconfig.json
packages/injected-script/sdk/utils.ts
packages/injected-script/shared/index.ts

chore: create SolanaBridge for solana injected provider

---

packages/mask/src/components/CompositionDialog/BadgeRenderer.tsx
packages/mask/src/plugins/Airdrop/SNSAdaptor/AirdropClaimCard.tsx
packages/mask/src/plugins/Pets/SNSAdaptor/tooltip.tsx
packages/theme/src/ShadowRoot/Portal.tsx

fix: invalid use of Tooltip component

---

packages/dashboard/src/pages/Wallets/hooks/useGasConfig.ts
packages/mask/src/extension/popups/pages/Wallet/Transfer/Prior1559Transfer.tsx
packages/mask/src/extension/popups/pages/Wallet/Transfer/Transfer1559.tsx

fix: fetch gas failures due to accuracy issues

---

packages/dashboard/src/pages/Labs/index.tsx

feat: remove swap settings in labs page

---

packages/shared/src/UI/components/ErrorBoundary/CrashUI.tsx

fix: insertBefore failed, close #4916

---

packages/mask/src/plugins/ITO/Worker/apis/checkAvailability.ts
packages/mask/src/plugins/RedPacket/Worker/apis/checkAvailability.ts

fix: firefox csp

---

.github/workflows/linters.yml
packages/mask/src/social-network-adaptor/facebook.com/utils/parse-username.ts

fix(facebook): postlink crash

---

packages/dashboard/src/pages/Wallets/components/WalletStateBar/index.tsx
packages/mask/src/components/InjectedComponents/ToolboxUnstyled.tsx

chore: open wallet dialog

---

packages/mask/src/extension/background-script/EthereumServices/rpc/abi.ts
packages/mask/src/extension/background-script/EthereumServices/send.ts
packages/mask/src/manifest.json
packages/mask/src/plugin-infra/register.ts
packages/mask/src/plugins/EVM/UI/components/ProviderIconClickBait.tsx
packages/mask/src/plugins/Wallet/services/transaction/helpers.ts
packages/mask/src/web3/UI/EthereumERC20TokenApprovedBoundary.tsx
packages/web3-shared/evm/types/index.ts

fix: C98 related issues

---

packages/dashboard/src/pages/Personas/components/PersonaCard/index.tsx
packages/dashboard/src/pages/Wallets/components/CollectibleList/index.tsx
packages/dashboard/src/pages/Wallets/components/TokenTable/index.tsx
packages/dashboard/src/pages/Wallets/hooks/useCollectibleOwners.ts
packages/mask/src/database/Persona/Persona.db.ts
packages/mask/src/extension/background-script/WelcomeServices/restoreBackup.ts
packages/mask/src/plugins/Wallet/services/assets.ts
packages/shared/src/UI/components/ERC20TokenList/ERC20TokenListItem.tsx
packages/shared/src/UI/components/ERC20TokenList/index.tsx
packages/shared/src/UI/components/TokenIcon/TokenIconSpecialIconList.json
packages/web3-constants/flow/auth.json
packages/web3-shared/evm/hooks/useAssetsByTokenList.ts
packages/web3-shared/evm/hooks/useTrustedERC20Tokens.ts
packages/web3-shared/evm/utils/token.ts

fix: token asset logo 

---

packages/mask/src/components/CompositionDialog/useSubmit.ts

fix: image payload

---

packages/dashboard/src/pages/Wallets/hooks/useGasConfig.ts

fix: incorrect hex string format

---

packages/mask/src/extension/popups/pages/Wallet/ImportWallet/index.tsx
packages/mask/src/plugins/Wallet/SNSAdaptor/ConnectWalletDialog/index.tsx

fix: select account when import wallet and no account

---

packages/mask/src/extension/popups/pages/Wallet/AddDeriveWallet/index.tsx
packages/mask/src/extension/popups/pages/Wallet/components/DeriveWalletTable/index.tsx

fix: incorrect derive wallet index

---

packages/mask/src/extension/background-script/EthereumServices/error.ts
packages/mask/src/extension/background-script/EthereumServices/send.ts

fix: error handling

---

packages/mask/src/plugins/ITO/SNSAdaptor/ClaimAllDialog.tsx

fix: show empty status text

---

packages/mask/src/plugins/RedPacket/SNSAdaptor/hooks/useCreateNftRedpacketCallback.ts

fix: add tx event for saving password

---

packages/dashboard/src/pages/Wallets/components/TokenTableRow/index.tsx
packages/mask/src/components/shared/WalletStatusBox.tsx
packages/mask/src/extension/popups/components/WalletStateBar/index.tsx
packages/mask/src/plugins/PoolTogether/UI/NetworkView.tsx
packages/mask/src/plugins/Profile/SNSAdaptor/WalletsPage.tsx

fix(popup): missing wallet icon in swap page

---

packages/mask/src/plugins/Wallet/pipes/index.ts

fix(dashboard): transaction history loading for Arbitrum

---

packages/mask/src/web3/UI/EthereumChainBoundary.tsx

fix: switch chain text color

---

packages/mask/src/plugins/Wallet/apis/nftscan.ts

fix: update nftscan api

---

packages/dashboard/src/pages/CreateMaskWallet/components/CreateMnemonic/index.tsx
packages/dashboard/src/pages/CreateMaskWallet/components/CreateWalletForm/index.tsx
packages/dashboard/src/pages/CreateMaskWallet/components/Welcome/index.tsx
packages/mask/shared/flags.ts
packages/mask/src/extension/popups/components/NetworkSelector/index.tsx
packages/mask/src/extension/popups/pages/Wallet/AddDeriveWallet/index.tsx
packages/mask/src/extension/popups/pages/Wallet/components/StartUp/index.tsx
packages/mask/src/extension/popups/pages/Wallet/index.tsx

close #4943 
close #4944 
hidden testnet in production env

fix: popup bugfix

---

packages/mask/shared-ui/locales/en-US.json
packages/mask/shared-ui/locales/ko-KR.json
packages/mask/shared-ui/locales/qya-AA.json
packages/mask/shared-ui/locales/zh-CN.json
packages/mask/src/components/CompositionDialog/CompositionContext.tsx
packages/mask/src/extension/background-script/EthereumServices/rpc/abi.ts
packages/mask/src/extension/background-script/EthereumServices/rpc/index.ts
packages/mask/src/extension/popups/components/WalletStateBar/index.tsx
packages/mask/src/plugins/ITO/SNSAdaptor/ClaimAllDialog.tsx
packages/mask/src/plugins/RedPacket/SNSAdaptor/NftRedPacketHistoryItem.tsx
packages/mask/src/plugins/RedPacket/SNSAdaptor/RedPacketNft.tsx
packages/mask/src/plugins/RedPacket/SNSAdaptor/RedpacketNftConfirmDialog.tsx
packages/mask/src/plugins/RedPacket/SNSAdaptor/SelectNftTokenDialog.tsx

fix: remove the dup snackbar

---

.github/workflows/compile.yml
.github/workflows/linters.yml
.github/workflows/netlify.yml

chore: typescript cachcing job is very slow, remove it

---

packages/mask/src/extension/popups/pages/Wallet/ImportWallet/index.tsx

fix: update mask account when import account

---

cspell.json
packages/mask/package.json
packages/mask/src/plugins/Profile/SNSAdaptor/DAOPage.tsx
packages/mask/src/plugins/Profile/SNSAdaptor/EnhancedProfile.tsx
packages/mask/src/plugins/Profile/SNSAdaptor/PageTag.tsx
packages/mask/src/plugins/Profile/SNSAdaptor/hooks/useDao.ts
packages/mask/src/plugins/Profile/types.ts
pnpm-lock.yaml

feat: web3 tab dao

---

packages/mask/src/extension/background-script/EthereumServices/send.ts
packages/mask/src/plugins/Collectible/SNSAdaptor/Account.tsx
packages/mask/src/plugins/Collectible/SNSAdaptor/ActionBar.tsx
packages/mask/src/plugins/Collectible/SNSAdaptor/ArticleTab.tsx
packages/mask/src/plugins/Collectible/SNSAdaptor/CheckoutDialog.tsx
packages/mask/src/plugins/Collectible/SNSAdaptor/HistoryTab/Row.tsx
packages/mask/src/plugins/Collectible/SNSAdaptor/ListingByHighestBidCard.tsx
packages/mask/src/plugins/Collectible/SNSAdaptor/ListingByPriceCard.tsx
packages/mask/src/plugins/Collectible/SNSAdaptor/MakeOfferDialog.tsx
packages/mask/src/plugins/Collectible/SNSAdaptor/OfferTab.tsx
packages/mask/src/plugins/Collectible/SNSAdaptor/PostListingDialog.tsx
packages/mask/src/plugins/Collectible/hooks/useAsset.ts
packages/mask/src/plugins/Profile/SNSAdaptor/PageTag.tsx
packages/mask/src/plugins/Trader/SNSAdaptor/balancer/TradeRouteHop.tsx
packages/mask/src/plugins/Trader/SNSAdaptor/trader/Trader.tsx
packages/mask/src/plugins/Trader/trader/0x/useTradeCallback.ts

fix: some urgent bugs

---

packages/injected-script/main/EventListenerPatch/capture.ts

fix: unable  to set nft avatar image

---

.github/workflows/compile.yml
.github/workflows/linters.yml
.github/workflows/netlify.yml

See https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies

chore: use offical github actions for pnpm cache support

---

docs/rfc/000-Payload-v37.md
docs/rfc/000-TypedMessage-binary-format.md
packages/shared-base/package.json
packages/shared-base/src/TypedMessage/base.ts
packages/shared-base/src/TypedMessage/binary-encode/decode.ts
packages/shared-base/src/TypedMessage/binary-encode/encode.ts
packages/shared-base/src/TypedMessage/binary-encode/type.ts
packages/shared-base/src/TypedMessage/core.ts
packages/shared-base/src/TypedMessage/extension.ts
packages/shared-base/src/TypedMessage/index.ts
packages/shared-base/src/TypedMessage/utils/index.ts
packages/shared-base/tests/__snapshots__/typed-message.ts.snap
packages/shared-base/tests/typed-message.ts
packages/shared-base/tsconfig.tests.json
pnpm-lock.yaml
tsconfig.json

feat: binary TypedMessage encoder/decoder

---

packages/mask/src/extension/popups/pages/Personas/Home/index.tsx
packages/mask/src/extension/popups/pages/Wallet/components/ActivityList/index.tsx
packages/mask/src/plugins/Avatar/SNSAdaptor/NFTAvatar.tsx
packages/mask/src/plugins/GoodGhosting/UI/TimelineTimer.tsx
packages/mask/src/plugins/Profile/SNSAdaptor/EnhancedProfile.tsx
packages/mask/src/plugins/RedPacket/SNSAdaptor/RedPacketERC20Form.tsx
packages/mask/src/plugins/Wallet/hooks/useWalletRiskWarningDialog.ts
packages/theme/.storybook/preview.js

chore: simplify state setter

---

packages/mask/src/extension/popups/pages/Wallet/DeleteWallet/index.tsx
packages/mask/src/plugins/Wallet/services/account.ts

fix: switch chain will drop the mask wallet

---

packages/injected-script/main/EventListenerPatch/capture.ts
packages/mask/src/UIRoot.tsx
packages/mask/src/components/InjectedComponents/PageInspector.tsx
packages/theme/src/Components/Snackbar/index.tsx

fix: the capture event

---

packages/mask/src/extension/options-page/DashboardComponents/CollectibleList/CollectibleCard.tsx

fix: nft wall image size

---

packages/mask/src/plugins/RedPacket/SNSAdaptor/hooks/useClaimCallback.ts
packages/mask/src/plugins/RedPacket/SNSAdaptor/index.tsx
packages/mask/src/plugins/RedPacket/types.ts
packages/mask/src/plugins/Snapshot/Worker/apis/index.ts

fix: some emergency small bugs

---

packages/mask/src/plugins/Trader/constants/dodo.ts

fix: replace dodo api to r2d2

---

packages/mask/src/components/shared/TokenPrice.tsx
packages/mask/src/plugins/MaskBox/SNSAdaptor/components/DrawDialog.tsx

disable quantity input if number is invalid

fix(Maskbox): fails to get price in usd

---

packages/mask/shared-ui/locales/en-US.json
packages/mask/src/components/InjectedComponents/SetupGuide.tsx
packages/mask/src/components/InjectedComponents/ToolboxUnstyled.tsx
packages/mask/src/database/Persona/helpers.ts
packages/mask/src/extension/background-script/SocialNetworkService.ts

feat: sidebar persona connect status

---

packages/mask/src/plugins/RedPacket/SNSAdaptor/RedPacket/index.tsx

fix: rp token symbol

---

packages/mask/src/plugins/Collectible/SNSAdaptor/HistoryTab/index.tsx
packages/mask/src/plugins/Collectible/SNSAdaptor/ListingTab.tsx
packages/mask/src/plugins/Collectible/SNSAdaptor/OfferTab.tsx

fix: remove useless pagination in collectible

---

packages/mask/src/plugins/Wallet/apis/debank.ts
packages/mask/src/plugins/Wallet/services/assets.ts
packages/mask/src/plugins/Wallet/types/debank.ts

fix: Debank balance api changed

---

packages/dashboard/src/pages/Wallets/components/Transfer/TransferERC721.tsx
packages/dashboard/src/pages/Wallets/hooks/useGasConfig.ts
packages/mask/src/plugins/Wallet/SNSAdaptor/GasSettingDialog/Prior1559GasSetting.tsx
packages/web3-shared/evm/hooks/useGasPrice.ts

fix: dashboard transfer gas fee incorrect when change network

---

packages/mask/src/components/shared/ApplicationBoard.tsx

feat: should hide some applications on flow

---

packages/mask/src/plugins/FindTruman/SNSAdaptor/FindTruman.tsx

fix: lint error

---

packages/mask/src/extension/popups/pages/Wallet/AddDeriveWallet/index.tsx
packages/mask/src/extension/popups/pages/Wallet/ImportWallet/index.tsx

fix: derive wallet bug

---

packages/mask/src/plugins/EVM/base.ts
packages/mask/src/plugins/EVM/constants.ts
packages/plugin-infra/src/types.ts
packages/plugin-infra/src/web3-types.ts
packages/plugins/Flow/src/UI/Web3UI/index.tsx
packages/plugins/Flow/src/base.ts

+ declare applications
+ declare application categories
closes #

refactor: extent plugin definition

---

packages/mask/src/plugins/Trader/apis/trending/hotfix.ts

To force define the ID of each network on CMC & CoinGecko.
closes #

refactor: type-safe

---

packages/dashboard/src/pages/Wallets/components/Transfer/TransferERC20.tsx
packages/dashboard/src/pages/Wallets/components/Transfer/TransferERC721.tsx
packages/dashboard/src/pages/Wallets/components/WalletStateBar/index.tsx
packages/mask/src/components/shared/WalletStatusBox.tsx

fix: ens ui

---

packages/dashboard/src/locales/en-US.json
packages/mask/src/plugins/Trader/SNSAdaptor/trader/TradeForm.tsx
packages/mask/src/plugins/Trader/SNSAdaptor/trader/Trader.tsx

fix: swap bugfix

---

packages/mask/src/plugins/FindTruman/SNSAdaptor/FindTruman.tsx

fix: the visiblity of hero image

---

packages/mask/shared-ui/locales/en-US.json
packages/mask/src/plugins/Profile/SNSAdaptor/NFTPage.tsx

refactor(ui): the tooltip ui

---

packages/mask/src/plugins/RedPacket/SNSAdaptor/RedpacketNftConfirmDialog.tsx

fix: show compose dialog

---

packages/mask/src/plugins/Trader/SNSAdaptor/trader/TradeForm.tsx
packages/mask/src/plugins/Trader/SNSAdaptor/trader/Trader.tsx
packages/mask/src/plugins/Trader/trader/uniswap/useTradeGasLimit.ts
packages/mask/src/plugins/Trader/trader/useAllTradeComputed.ts

fix: pancakeswap can't display

---

packages/mask/src/plugins/Profile/SNSAdaptor/DAOPage.tsx
packages/mask/src/plugins/Profile/SNSAdaptor/EnhancedProfile.tsx
packages/mask/src/plugins/Profile/SNSAdaptor/hooks/useDao.ts

fix: rm useless api call

---

packages/dashboard/src/pages/Wallets/components/Transfer/TransferERC20.tsx
packages/mask/src/extension/popups/pages/Wallet/ContractInteraction/index.tsx
packages/mask/src/extension/popups/pages/Wallet/Transfer/Prior1559Transfer.tsx
packages/mask/src/extension/popups/pages/Wallet/Transfer/Transfer1559.tsx
packages/mask/src/plugins/Collectible/helpers.ts
packages/mask/src/plugins/Gitcoin/SNSAdaptor/DonateDialog.tsx
packages/mask/src/plugins/ITO/SNSAdaptor/ITO.tsx
packages/mask/src/plugins/ITO/SNSAdaptor/PoolInList.tsx
packages/mask/src/plugins/ITO/SNSAdaptor/SwapDialog.tsx
packages/mask/src/plugins/ITO/SNSAdaptor/UnlockDialog.tsx
packages/mask/src/plugins/ITO/SNSAdaptor/hooks/useFill.ts
packages/mask/src/plugins/PoolTogether/UI/DepositDialog.tsx
packages/mask/src/plugins/RedPacket/SNSAdaptor/RedPacketERC20Form.tsx
packages/mask/src/plugins/Trader/SNSAdaptor/trader/ConfirmDialog.tsx
packages/mask/src/plugins/Trader/SNSAdaptor/trader/TradeForm.tsx
packages/mask/src/plugins/Trader/apis/bancor/calculateMinimumReturn.ts
packages/mask/src/plugins/Trader/apis/dodo/index.ts
packages/mask/src/plugins/Trader/trader/bancor/useTrade.ts
packages/mask/src/plugins/Trader/trader/bancor/useTradeComputed.ts
packages/mask/src/plugins/Trader/trader/dodo/useTradeComputed.ts
packages/mask/src/plugins/Wallet/services/assets.ts
packages/mask/src/plugins/Wallet/services/transactions.ts
packages/mask/src/plugins/dHEDGE/UI/InvestDialog.tsx
packages/web3-shared/evm/utils/formatter.ts

closes #
see https://mikemcl.github.io/bignumber.js/#shift

chore: simplify big number (pow10 to shiftedby)

---

packages/web3-shared/evm/hooks/useERC721ContractDetailed.ts

fix: opensea incorrect data

---

packages/mask/src/plugins/Trader/apis/coingecko/index.ts
packages/mask/src/plugins/Trader/apis/trending/index.ts

fix: coingecko api duplicated data

---

packages/mask/src/plugins/Gitcoin/SNSAdaptor/index.tsx
packages/mask/src/plugins/Gitcoin/base.ts
packages/web3-constants/evm/gitcoin.json

feat: gitcoin donation on Polygon

---

packages/mask/src/plugins/Gitcoin/SNSAdaptor/DonateDialog.tsx
packages/mask/src/plugins/Gitcoin/SNSAdaptor/PreviewCard.tsx
packages/mask/src/plugins/Gitcoin/messages.ts

fix: add share link

---

packages/dashboard/src/pages/Wallets/components/WalletStateBar/index.tsx
packages/mask/src/extension/popups/pages/Wallet/WalletRename/index.tsx
packages/mask/src/extension/popups/pages/Wallet/hooks/useSetWalletNameForm.ts
packages/mask/src/plugins/Trader/SNSAdaptor/trader/InputTokenPanel.tsx
packages/mask/src/plugins/Trader/SNSAdaptor/trader/TradeForm.tsx
packages/mask/src/plugins/Trader/SNSAdaptor/trader/TradeView.tsx
packages/mask/src/plugins/Trader/SNSAdaptor/trader/Trader.tsx
packages/mask/src/plugins/Trader/SNSAdaptor/trader/TraderDialog.tsx
packages/mask/src/plugins/Trader/SNSAdaptor/trader/TraderInfo.tsx
packages/mask/src/plugins/Trader/SNSAdaptor/trending/TraderView.tsx
packages/mask/src/plugins/Trader/trader/useTargetChainIdContext.ts
packages/mask/src/plugins/Trader/trader/useTradeApproveComputed.ts
packages/mask/src/plugins/Wallet/services/account.ts
packages/web3-shared/evm/utils/token.ts

fix: replace wallet name with provider name when connect 3rd wallet

---

packages/.eslintrc.json
packages/dashboard/src/locales/en-US.json
packages/dashboard/src/locales/ja-JP.json
packages/dashboard/src/locales/zh-CN.json
packages/dashboard/src/pages/Wallets/components/HistoryTable/index.tsx
packages/dashboard/src/pages/Wallets/components/HistoryTableRow/index.tsx

feat: dashboard history wording

---

packages/mask/shared-ui/locales/en-US.json
packages/mask/shared-ui/locales/ko-KR.json
packages/mask/shared-ui/locales/qya-AA.json
packages/mask/shared-ui/locales/zh-CN.json
packages/mask/shared-ui/locales/zh-TW.json
packages/mask/src/components/DataSource/useActivatedUI.ts
packages/mask/src/plugins/RedPacket/SNSAdaptor/RedPacket/index.tsx
packages/mask/src/plugins/RedPacket/SNSAdaptor/RedPacket/useStyles.ts
packages/mask/src/social-network-adaptor/facebook.com/ui-provider.ts
packages/mask/src/social-network-adaptor/minds.com/ui-provider.ts
packages/mask/src/social-network-adaptor/twitter.com/ui-provider.ts

Fix [mask-376](https://mask.atlassian.net/jira/software/c/projects/MASK/boards/11?selectedIssue=MASK-376)

chore: remove currentSelectedIdentity

---

packages/mask/src/database/Plugin/wrap-plugin-database.ts

https://mask.atlassian.net/browse/MASK-379

fix: backup process lost some wallet

---

packages/mask/src/plugins/EVM/UI/components/ProviderIconClickBait.tsx
packages/mask/src/plugins/EVM/base.ts
packages/mask/src/plugins/EVM/constants.ts
packages/plugin-infra/src/types.ts
packages/plugin-infra/src/web3-types.ts
packages/plugins/Flow/src/base.ts

chore: enable network and wallets

---

packages/dashboard/src/locales/en-US.json

fix: sync password tip

---

packages/.eslintrc.json
packages/dashboard/src/pages/Wallets/components/Balance/index.tsx
packages/encryption/src/payload_internal/version-37.parser.ts
packages/mask/src/components/CompositionDialog/CompositionUI.tsx
packages/mask/src/network/gun/version.2/gun2.ts
packages/mask/src/plugins/EVM/utils/token.ts
packages/mask/src/plugins/Furucombo/UI/InvestmentsView.tsx
packages/mask/src/plugins/Snapshot/SNSAdaptor/ResultCard.tsx
packages/mask/src/plugins/UnlockProtocol/Services.ts
packages/mask/src/social-network-adaptor/facebook.com/utils/parse-username.ts
packages/mask/src/social-network-adaptor/twitter.com/encoding.ts
packages/web3-shared/evm/utils/token.ts

refactor: improve number practice

---

packages/dashboard/src/components/Restore/RestoreFromPrivateKey.tsx
packages/dashboard/src/pages/Personas/components/LogoutPersonaDialog/index.tsx

fix: zero persona snackbar in dashboard

---

packages/mask/src/social-network-adaptor/facebook.com/injection/Composition.tsx

fix: incorrect inject position when try to post in group

---

packages/mask/src/plugins/MaskBox/SNSAdaptor/components/DrawDialog.tsx

fix(maskbox): purchase limited to 255 by contract

---

packages/mask/src/extension/popups/pages/Swap/SwapBox/index.tsx
packages/mask/src/extension/popups/pages/Swap/index.tsx

fix: swap box crash

---

packages/dashboard/src/pages/Wallets/components/Transfer/NFTCard.tsx
packages/mask/src/extension/options-page/DashboardComponents/CollectibleList/CollectibleCard.tsx
packages/mask/src/extension/options-page/DashboardDialogs/Wallet/TransferNFT.tsx
packages/mask/src/plugins/Avatar/SNSAdaptor/NFTAvatar.tsx
packages/mask/src/plugins/Avatar/SNSAdaptor/NFTImage.tsx
packages/mask/src/plugins/Avatar/utils/index.ts
packages/mask/src/plugins/EVM/UI/Web3State/getAssetsFn.ts
packages/mask/src/plugins/MaskBox/SNSAdaptor/components/TokenCard.tsx
packages/mask/src/plugins/RedPacket/SNSAdaptor/NftList.tsx
packages/mask/src/plugins/RedPacket/SNSAdaptor/RedPacketERC721Form.tsx
packages/mask/src/plugins/RedPacket/SNSAdaptor/RedPacketNft.tsx
packages/mask/src/plugins/RedPacket/SNSAdaptor/RedpacketNftConfirmDialog.tsx
packages/mask/src/plugins/RedPacket/SNSAdaptor/SelectNftTokenDialog.tsx
packages/mask/src/plugins/Wallet/services/assets.ts
packages/mask/src/social-network-adaptor/twitter.com/injection/NFT/ProfileNFTAvatar.tsx
packages/web3-shared/evm/hooks/useERC721TokenDetailed.ts
packages/web3-shared/evm/hooks/useERC721TokenDetailedOwnerList.ts
packages/web3-shared/evm/types/index.ts

fix(maskbox): support video NFTs on draw result dialog

---

packages/mask/src/plugins/Wallet/SNSAdaptor/TransactionSnackbar/index.tsx
packages/mask/src/plugins/Wallet/services/transaction/helpers.ts
packages/mask/src/plugins/Wallet/services/transaction/index.ts
packages/mask/src/plugins/Wallet/services/transaction/watcher.ts
packages/web3-shared/evm/types/index.ts

fix: transaction timeout

---

packages/mask/src/plugins/Collectible/SNSAdaptor/MakeOfferDialog.tsx

fix: incorrect payment token when place bid on collectible

---

packages/mask/src/extension/options-page/DashboardComponents/CollectibleList/CollectibleCard.tsx
packages/mask/src/extension/options-page/DashboardComponents/CollectibleList/index.tsx

fix: nft loading style & count

---

packages/mask/src/plugins/Avatar/SNSAdaptor/NFTAvatarRing.tsx

fix: nft avatar display problem

---

packages/mask/src/plugins/EVM/UI/components/FortmaticProviderBridge.tsx
packages/mask/src/plugins/EVM/UI/components/InjectedProviderBridge.tsx
packages/plugin-infra/src/web3/useAssetType.ts
packages/plugin-infra/src/web3/useChainId.ts
packages/plugin-infra/src/web3/useCollectibleType.ts
packages/plugin-infra/src/web3/useCurrencyType.ts
packages/plugin-infra/src/web3/useNameType.ts
packages/plugin-infra/src/web3/useNetworkType.ts
packages/plugin-infra/src/web3/useProviderType.ts
packages/plugin-infra/src/web3/useTransactionType.ts

To change account or switch network will lead the page to refresh. As Dapp, we need to re-request if the current provider is C98.
To ensure that the connection is healthy.
closes #

fix: c98 & fortmatic auto-connect

---

packages/mask/src/extension/popups/pages/Wallet/components/WalletInfo/index.tsx
packages/mask/src/plugins/EVM/UI/Web3State/index.ts

fix: zero ens domain address

---

packages/mask/src/plugins/ITO/SNSAdaptor/ConfirmDialog.tsx
packages/mask/src/plugins/ITO/SNSAdaptor/CreateForm.tsx
packages/mask/src/plugins/ITO/SNSAdaptor/ITO.tsx

[MASK-377](https://mask.atlassian.net/jira/software/c/projects/MASK/boards/15?modal=detail&selectedIssue=MASK-377)

fix: limit amount by decimal

---

packages/mask/src/plugins/ITO/SNSAdaptor/hooks/useFill.ts

chore: ito gas estimate

---

packages/mask/src/components/shared/InjectedDialog.tsx
packages/mask/src/components/shared/WalletStatusBox.tsx
packages/mask/src/plugins/EVM/UI/components/ProviderIconClickBait.tsx
packages/mask/src/plugins/Trader/SNSAdaptor/trader/ConfirmDialog.tsx
packages/mask/src/plugins/Trader/SNSAdaptor/trader/Gas1559Settings.tsx
packages/mask/src/plugins/Trader/SNSAdaptor/trader/GasPrior1559Settings.tsx
packages/mask/src/plugins/Trader/SNSAdaptor/trader/InputTokenPanel.tsx
packages/mask/src/plugins/Trader/SNSAdaptor/trader/TradeForm.tsx
packages/mask/src/plugins/Trader/SNSAdaptor/trader/TraderDialog.tsx
packages/mask/src/plugins/Trader/SNSAdaptor/trader/TraderInfo.tsx
packages/mask/src/web3/context.ts
packages/shared-base/src/utils/detect.ts
packages/shared-base/src/utils/index.ts

refactor: add isDashboard & isPoup

---

packages/dashboard/src/pages/Settings/components/LanguageSetting.tsx

feat: toggle zh cn in production

---

packages/encryption/src/encryption/DecryptionTypes.ts
packages/mask/background/database/persona/db.ts
packages/mask/background/database/post/helper.ts
packages/mask/background/database/post/index.ts
packages/mask/src/extension/background-script/WelcomeServices/restoreBackup.ts
packages/mask/utils-pure/crypto/index.ts

chore: pick some small changes from #5208

---

packages/mask/src/social-network-adaptor/twitter.com/utils/selector.ts

fix: twitter popup selector

---

packages/mask/src/extension/popups/components/PopupFrame/index.tsx

fix: recover wallet when wallet be locked

---

packages/mask/src/plugins/Wallet/services/transactions.ts
packages/mask/src/plugins/Wallet/types/debank.ts

fix: debank history api

---

packages/mask/src/plugins/MaskBox/hooks/useContext.ts
packages/mask/src/plugins/MaskBox/type.ts

fix: the remaining/total numbers

---

packages/mask/.webpack/config.ts
packages/shared-base/src/crypto/secp256k1.ts

fix: onInstall not triggered

---

packages/dashboard/src/web3/context.ts
packages/mask/src/extension/background-script/EthereumServices/providers/Fortmatic.ts
packages/mask/src/extension/background-script/EthereumServices/providers/Injected.ts
packages/mask/src/extension/background-script/SettingsService.ts
packages/mask/src/plugins/EVM/UI/components/FortmaticProviderBridge.tsx
packages/mask/src/plugins/EVM/UI/components/InjectedProviderBridge.tsx
packages/mask/src/plugins/Wallet/SNSAdaptor/ConnectWalletDialog/index.tsx
packages/mask/src/plugins/Wallet/services/transaction/helpers.ts
packages/mask/src/plugins/Wallet/settings.ts
packages/mask/src/web3/UI/EthereumChainBoundary.tsx
packages/mask/src/web3/context.ts

+ [x] Longer timeout delay when waiting for connection confirmation.
+ [x] Switch networks between Flow and EVM on the plugin panel.
+ [ ] Co-exist of accounts on the front page and dashboard page.
closes #

fix: switch network problems

---

packages/mask/src/plugins/Trader/trader/uniswap/useTradeGasLimit.ts

refactor: toHex

---

packages/dashboard/src/pages/Wallets/components/Transfer/TransferERC20.tsx
packages/mask/src/plugins/EVM/UI/Web3State/index.ts

fix: valid address and domain when transfer erc20 with ens

---

packages/mask/src/social-network-adaptor/twitter.com/utils/selector.ts

fix: twitter comment selector

---

packages/mask/src/plugins/Avatar/Services/rss3.ts

fix: add cache expiration

---

packages/mask/src/plugins/Profile/SNSAdaptor/EnhancedProfile.tsx

fix: reset page tag when identifier be changed

---

packages/dashboard/src/pages/Wallets/index.tsx

fix(dashboard): get balance by chain from debank

---

packages/mask/src/extension/popups/components/PopupFrame/index.tsx
packages/mask/src/extension/popups/pages/Wallet/Unlock/index.tsx

closes MASK-478
closes MASK-479

fix: show persona tab in unlock page

---

packages/mask/background/services/helper/fetch.ts

chore: improve fetch json

---

packages/.eslintrc.json
packages/dashboard/src/pages/Labs/index.tsx
packages/mask/src/extension/options-page/DashboardComponents/ActionsBarNFT.tsx
packages/mask/src/plugins/UnlockProtocol/SNSAdaptor/SelectRecipientsUnlockDialog.tsx
packages/mask/src/protocols/typed-message/debugger.tsx
packages/shared/src/hooks/useMenu.tsx

Learn more: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-key.md
closes #

refactor: eslint react/jsx-key

---

packages/mask/src/plugins/Trader/apis/uniswap-v2-subgraph/index.ts
packages/mask/src/plugins/Trader/apis/uniswap/index.ts
packages/mask/src/plugins/Trader/types/trending.ts
packages/mask/src/web3/UI/EthereumBlockie.tsx
packages/shared/src/UI/components/TokenIcon/index.tsx

fix: uppercase or lowercase

---

packages/mask/src/plugins/Profile/SNSAdaptor/components/FootprintCard.tsx

refactor: lint error

---

.pnpmfile.cjs

chore: lock opensea-js dependencies

---

packages/web3-shared/evm/hooks/useERC721TokenDetailed.ts
packages/web3-shared/evm/hooks/useERC721TokenDetailedCallback.ts

refactor: code style

---

packages/mask/src/extension/background-script/EthereumServices/send.ts

fix: GET_TRANSACTION_RECEIPT of nativeSend

---

.github/pull_request_template.md

docs: add sub list

---

packages/mask/src/plugins/EVM/UI/components/ProviderIconClickBait.tsx
packages/plugins/Flow/src/base.ts

refactor: trun on switches

---

.github/semantic.yml

https://github.com/zeke/semantic-pull-requests#configuration

chore: enable semantic

---

packages/mask/src/plugins/Avatar/SNSAdaptor/NFTAvatarRing.tsx
packages/mask/src/social-network-adaptor/twitter.com/injection/NFT/NFTAvatarInTwitter.tsx

fix: hidden rainbow when nft avatar isn't exist

---

packages/web3-shared/evm/utils/address.ts

fix: currySameAddress

---

packages/web3-providers/src/opensea/index.ts

fix: opensea contract image

---

packages/mask/src/plugins/EVM/services/Asset/index.ts
packages/mask/src/plugins/EVM/services/NFT/index.ts
packages/mask/src/plugins/Wallet/services/assets.ts
packages/web3-providers/src/NFTScan/index.ts
packages/web3-providers/src/opensea/index.ts
packages/web3-providers/src/rarible/index.ts
packages/web3-providers/src/types.ts

- [x ] I have commented on my code, particularly in hard-to-understand areas.

feat: web3 provider api support page size in response

---

packages/mask/src/plugins/MaskBox/hooks/useContext.ts
packages/mask/src/plugins/MaskBox/hooks/useHeartBeat.ts
packages/web3-shared/evm/hooks/useTransactionCallback.ts

refactor: compact code

---

packages/web3-providers/src/opensea/index.ts

fix: contract address

---

packages/mask/src/extension/background-script/WelcomeService.ts

https://date-fns.org/v2.27.0/docs/format

chore: simplify format date

---

packages/mask/src/extension/background-script/WelcomeService.ts

fix: backup name

---

.github/workflows/bot.yml
.github/workflows/compile.yml
.github/workflows/linters.yml
.github/workflows/netlify.yml
.github/workflows/spell-checking.yml

ci: cancel previous workflows when starting a new one

---

packages/mask/src/extension/options-page/DashboardComponents/CollectibleList/index.tsx
packages/mask/src/plugins/EVM/services/NFT/index.ts
packages/mask/src/plugins/Wallet/services/assets.ts
packages/web3-providers/src/opensea/index.ts
packages/web3-shared/evm/hooks/useCollectibles.ts

fix: nft wall

---

packages/mask/src/components/DataSource/usePostInfo.ts
packages/mask/src/components/InjectedComponents/DecryptedPost/DecryptedPost.tsx
packages/mask/src/components/InjectedComponents/DecryptedPost/DecryptedPostDebug.tsx
packages/mask/src/components/InjectedComponents/PostComments.tsx
packages/mask/src/components/InjectedComponents/PostInspector.tsx
packages/mask/src/components/InjectedComponents/PostReplacer.tsx
packages/mask/src/plugins/Collectible/SNSAdaptor/index.tsx
packages/mask/src/plugins/CryptoartAI/SNSAdaptor/index.tsx
packages/mask/src/plugins/FindTruman/SNSAdaptor/index.tsx
packages/mask/src/plugins/Furucombo/SNSAdaptor/index.tsx
packages/mask/src/plugins/Gitcoin/SNSAdaptor/index.tsx
packages/mask/src/plugins/GoodGhosting/SNSAdaptor/index.tsx
packages/mask/src/plugins/MaskBox/SNSAdaptor/index.tsx
packages/mask/src/plugins/PoolTogether/SNSAdaptor/index.tsx
packages/mask/src/plugins/RedPacket/SNSAdaptor/RedPacketInPost.tsx
packages/mask/src/plugins/Snapshot/SNSAdaptor/index.tsx
packages/mask/src/plugins/VCent/SNSAdaptor/index.tsx
packages/mask/src/plugins/dHEDGE/SNSAdaptor/index.tsx
packages/mask/src/social-network-adaptor/facebook.com/collecting/posts.tsx
packages/mask/src/social-network-adaptor/facebook.com/injection/PostInspector.tsx
packages/mask/src/social-network-adaptor/instagram.com/injection/post-inspector.ts
packages/mask/src/social-network-adaptor/twitter.com/collecting/post.ts
packages/mask/src/social-network-adaptor/twitter.com/injection/MaskIcon.tsx
packages/mask/src/social-network/defaults/inject/CommentBox.tsx
packages/mask/src/social-network/defaults/inject/PostInspector.tsx
packages/mask/src/social-network/defaults/inject/PostReplacer.tsx
packages/mask/src/social-network/utils/create-post-context.ts
packages/plugin-infra/src/PostContext.ts

refactor: rename props

---

packages/web3-providers/src/opensea/index.ts

fix: add default in return result

---

packages/mask/.webpack/plugins/manifest.ts
packages/mask/dashboard/pages/PrivacyPolicy/en.html

chore: fix some typos in comments

---

packages/mask/swap/webgl/TickerManager.ts

fix function name
