- src/components/DataSource/PeopleRef.ts
- src/components/InjectedComponents/CommentBox.tsx
- src/components/InjectedComponents/DecryptedPost.tsx
- src/components/InjectedComponents/PostComments.tsx
- src/crypto/crypto-alpha-40.ts
- src/extension/background-script/CryptoService.ts
- src/extension/content-script/injections/MyUsername.ts
- src/extension/content-script/injections/Posts.tsx
- src/extension/content-script/injections/Posts/PostInspector.tsx
- src/extension/content-script/injections/Welcome.tsx
- src/extension/service.ts
- src/stories/Injections.tsx
- src/tests/1to1.ts
- src/tests/1toN.ts
- src/tests/comment.ts
- src/tests/friendship-discover.ts
- src/tests/sign&verify.ts
- src/utils/components/AsyncComponent.tsx
- src/utils/hooks/useCapturedEvents.ts
- src/utils/hooks/useValueRef.ts
- src/utils/jss/renderInShadowRoot.tsx
- src/utils/utils.ts
> feature: encrypt & decrypt comment ( close #62 )

- src/components/Welcomes/QRScanner/ShapeDetectionPolyfill.ts
- src/utils/hooks/useQRCodeScan.tsx
- src/utils/hooks/useRequestCamera.ts
+ fix request camera permission twice
+ fix create multiple workers
> fix(firefox): request camera permission twice #100

- README.md
> doc(readme): now even more clickable

- src/components/Welcomes/0.tsx
- src/components/Welcomes/1a1a.tsx
- src/components/Welcomes/1a1b.tsx
- src/components/Welcomes/1a2.tsx
- src/components/Welcomes/1b1.tsx
- src/components/Welcomes/2.tsx
- src/components/Welcomes/Navigation/Navigation.tsx
- src/extension/options-page/Welcome/index.tsx
- src/stories/Welcome.tsx
+ extracted nav component
+ on clicking close/finish button, close the popup dialog instead of closing the tab
+ close the vide o track when it should be
Please test:
+ mobile
> Chore related to option page's UI

- just.config.js
- package.json
> fixes yarn remove not hooking

- README.md
- config-overrides.js
- just.config.js
- package.json
- webpack.config.js
- yarn.lock
Limited by extension, HMR not available for now. You will need a F5 to reload the extension,
> development script update

- .git-utils/test4bis.sh
this tool is as simple as it sounds! i wonder if i can put it inside npm scripts as a one-liner
* * *
misaka was trying to find bug #118 when i wrote this. turns out 10 commits is perfectly do-able by human quicksect (i.e. random splitting)
> chore(git-utils): test4bis, a quick thing for easier bisect

- .circleci/config.yml
- .gitignore
- config-overrides.js
- just.config.js
- package.json
- yarn.lock
> toolchain for android/firefox

- README.md
> doc: make icons shorter; make the newline work

- .gitignore
- commitlint.config.js
- config-overrides/SSRPlugin.js
- config-overrides/index.js
- package.json
- scripts/lint.js
- scripts/postinstall.js
- scripts/spawn.js
- webpack.config.js
- yarn.lock
did someone forget to run prettier?
> fix(toolchain): keep the profile and do argparse right

- src/utils/jss/ConstructableStyleSheetsRenderer.ts
previous commit does cause troubles.
> fix: polyfill not injecting css

- src/_locales/en/messages.json
- src/_locales/zh/messages.json
- src/components/InjectedComponents/AdditionalPostBox.tsx
- src/components/InjectedComponents/AdditionalPostContent.tsx
- src/components/Welcomes/1b1.tsx
- src/components/Welcomes/Banner.tsx
- src/components/Welcomes/QRScanner/index.tsx
- src/components/shared/NotSetupYetPrompt.tsx
- src/extension/options-page/Welcome/index.tsx
- src/index.tsx
- src/setup.ssr.js
- src/social-network-provider/facebook.com/ui-provider.ts
- src/social-network-provider/twitter.com/ui/index.ts
- src/stories/Injections.tsx
- src/stories/Welcome.tsx
- src/stories/shared.tsx
- src/utils/hooks/useQRCodeScan.tsx
- src/utils/theme.ts
Fix QR scanning on Firefox and #161 (by SunriseFox)
A dialog for requesting permissions (by SunriseFox and Jack):
Theme switched to indigo (400) and orange (800) (by Jack)
Switch to more standard Material (by Jack):
Better CJK fonts (by Jack):
> fix(qr): QR scanning on firefox not working

- src/background-service.ts
- src/components/InjectedComponents/AdditionalPostBox.tsx
- src/components/InjectedComponents/DecryptedPost.tsx
- src/components/InjectedComponents/PostInspector.tsx
- src/crypto/crypto-alpha-38.ts
- src/crypto/crypto-alpha-39.ts
- src/crypto/crypto-alpha-40.ts
- src/database/post.ts
- src/extension/background-script/CryptoServices/appendShareTarget.ts
- src/extension/background-script/CryptoServices/decryptFrom.ts
- src/extension/background-script/CryptoServices/encryptTo.ts
- src/extension/background-script/CryptoServices/getSharedListOfPost.ts
- src/extension/background-script/WelcomeService.ts
- src/extension/background-script/prepareOthersKeyForEncryption.ts
- src/network/gun/version.2/hash.ts
- src/network/gun/version.2/post.ts
- src/social-network-provider/facebook.com/shared-provider.ts
- src/social-network-provider/twitter.com/index.ts
- src/social-network/shared.ts
- src/social-network/ui.ts
- src/social-network/worker.ts
- src/tests/1to1.ts
- src/utils/type-transform/Payload.ts
1. Introduce a new -38 payload
2. Apply the stable hash fix on the -38 version
```ts
// ? payload is 🎼4/4|AESKeyEncrypted|iv|encryptedText|signature|publicShared:||
// ? if publicShared is true, that means AESKeyEncrypted is shared with public
```
> Introduce new payload -38 to fix a critical hash problem

- config-overrides/index.js
- yarn.lock
This pr is making changes on the `master-android` branch into master.
> Sync master-android => master

- src/extension/options-page/Empty.tsx
- src/index.tsx
> fix: empty page should not display in developer page #293

- package.json
- src/components/Welcomes/1a3a.tsx
- src/components/Welcomes/Banner.tsx
- src/components/shared/SelectPeopleAndGroups/PersonOrGroupInList.tsx
- src/extension/background-script/WelcomeService.ts
- src/extension/options-page/Developer.tsx
- src/extension/options-page/Welcome/index.tsx
- src/extension/popup-page/index.tsx
- src/index.tsx
- src/social-network-provider/facebook.com/UI/injectOptionsPageLink.tsx
- src/social-network-provider/facebook.com/UI/injectWelcomeBanner.tsx
- src/social-network-provider/facebook.com/ui-provider.ts
- src/social-network-provider/facebook.com/worker-provider.ts
- src/social-network-provider/twitter.com/worker/index.ts
- src/social-network/defaults/emptyDefinition.ts
- src/social-network/defaults/shared.ts
- src/social-network/defaults/shouldDisplayWelcome.ts
- src/social-network/defaults/ui.ts
- src/social-network/ui.ts
- src/social-network/worker.ts
- src/stories/Welcome.tsx
- yarn.lock
> feature: better UI on mobile device

- README.md
- src/components/MobileImportExport/Export.tsx
- src/components/Welcomes/1b1.tsx
- src/components/Welcomes/QRScanner/index.tsx
- src/extension/background-script/WelcomeService.ts
- src/extension/options-page/Welcome/index.tsx
- src/utils/type-transform/BackupFileShortRepresentation.ts
- src/utils/type-transform/SECP256k1-Compression.ts
Must merge after
- Gun upgrade #271
- Better UI on mobile #282  
close #232
> introduce the mobile version close #232

- src/components/shared/SelectPeopleAndGroups/resolveSpecialGroupName.ts
- src/utils/SSRRenderer.ts
- src/utils/jss/renderInShadowRoot.tsx
See: https://reactjs.org/docs/strict-mode.html
> Enable React's strict mode

- src/utils/jss/renderInShadowRoot.tsx
> warning on unmount react components

- src/components/InjectedComponents/AddToKeyStore.tsx
- src/components/InjectedComponents/AdditionalPostBox.tsx
- src/components/InjectedComponents/AdditionalPostContent.tsx
- src/components/InjectedComponents/CommentBox.tsx
- src/components/InjectedComponents/DecryptedPost.tsx
- src/components/InjectedComponents/PostComments.tsx
- src/components/InjectedComponents/PostInspector.tsx
- src/components/InjectedComponents/SelectPeopleDialog.tsx
- src/components/custom-ui-helper.tsx
- src/components/custom-ui.d.ts
- src/components/shared/ChooseIdentity.tsx
- src/components/shared/NotSetupYetPrompt.tsx
- src/components/shared/SelectPeopleAndGroups/PersonOrGroupInChip.tsx
- src/components/shared/SelectPeopleAndGroups/PersonOrGroupInList.tsx
- src/components/shared/SelectPeopleAndGroups/SelectPeopleAndGroupsUI.tsx
- src/components/shared/qrcode.tsx
- src/extension/options-page/DeveloperComponents/DecryptPost.tsx
- src/social-network/defaults/injectCommentBox.tsx
- src/social-network/defaults/injectComments.tsx
- src/social-network/defaults/injectPostInspector.tsx
- src/social-network/defaults/ui.ts
- src/social-network/ui.ts
- src/stories/Injections.tsx
- src/utils/jss/renderInShadowRoot.tsx
- yarn.lock
How to use it: https://github.com/DimensionDev/Maskbook/wiki/Customizable-UI
> Customizable ui

- src/social-network-provider/facebook.com/tasks/uploadToPostBox.ts
- src/social-network-provider/twitter.com/ui/tasks.ts
- src/social-network-provider/twitter.com/utils/fetch.ts
- src/utils/utils.ts
- yarn.lock
+ auto downloading encoded image but manually uploading is required in twitter;
+ auto decoding all images founded in twitter timeline and append result into `postContent`;
> Support publishing steganographic posts in twitter

- package.json
- yarn.lock
Reverts DimensionDev/Maskbook#379
> Revert "chore(deps): bump @material-ui/core from 4.5.1 to 4.6.0"

- src/components/InjectedComponents/AdditionalPostBox.tsx
> Reset composition box after requesting post

- src/social-network-provider/twitter.com/encoding.ts
> Make twitter payload adhere the spec #198

- src/social-network-provider/twitter.com/utils/selector.ts
> Fix: Inject compose box in Twitter DM by mistake

- src/components/InjectedComponents/AdditionalPostBox.tsx
- src/social-network-provider/twitter.com/utils/selector.ts
close #437
Screenshot after fixed:
> Renew self info regexps

- .github/ISSUE_TEMPLATE/rfc.md
Added "Later Updated By" field in Metadata section
> Updated issue template "RFC"

- src/social-network-provider/twitter.com/encoding.ts
> Fix malformed twitter payload

- .github/ISSUE_TEMPLATE/demand.md
Added "Corresponding Pull Request" and "Completion Version" fields in Metadata section.
> Updated "Demand" template

- src/social-network-provider/twitter.com/utils/selector.ts
> Fail to decode payload in tweet detail page

- src/components/InjectedComponents/AdditionalPostContent.tsx
> Stop event propagation in twitter

- src/_locales/en/messages.json
- src/_locales/zh/messages.json
- src/components/InjectedComponents/CommentBox.tsx
+ Change placeholder text for comment box
+ Mimic placeholder style of facebook comment box
Related Demand:
#462
Forward Refactor?
+ Move facebook only styles out from `CommentBox` component
> [UX] Improvement comment box UI

- src/social-network/defaults/GroupsValueRef.ts
> Update user groups immediately

- src/_locales/en/messages.json
- src/_locales/zh/messages.json
- src/index.tsx
> Dashboard mobile link & translation for 'source code' 

- src/_locales/en/messages.json
- src/_locales/zh/messages.json
- src/components/InjectedComponents/AdditionalPostContent.tsx
- src/components/InjectedComponents/PersonKnown.tsx
- src/social-network-provider/facebook.com/UI/injectKnownIdentity.tsx
- src/social-network-provider/twitter.com/encoding.ts
- src/social-network-provider/twitter.com/ui/injectKnownIdentity.tsx
> Add a tip under bio editor both twitter and facebook

- src/_locales/en/messages.json
- src/_locales/zh/messages.json
- src/extension/options-page/DashboardInitSteps/Step1R.tsx
- src/extension/options-page/Home.tsx
This is some supplement of #369 
Close #369
> Dashboard stage 2 supplement, restore database by text

- src/components/shared/SelectRecipients/GroupInChip.tsx
- src/components/shared/SelectRecipients/SelectRecipientsDialog.tsx
> Filter out no maskbook user in recipient list

- src/components/shared/qrcode.tsx
- src/setup.ssr.js
> feat: cache generated qr code in sessionStorage

- src/_locales/en/messages.json
- src/_locales/zh/messages.json
- src/components/InjectedComponents/AdditionalPostBox.tsx
- src/components/InjectedComponents/PostDialog.tsx
> Add timestamp into post text

- src/extension/background-script/CryptoServices/verifyOthersProve.ts
> fix: connect profile failed if bio contains publickey

- package.json
- yarn.lock
Reverts DimensionDev/Maskbook#559
> Revert "chore(deps): bump webcrypto-liner from 1.0.2 to 1.1.2"

- src/components/InjectedComponents/PostInspector.tsx
> Fix calling writeProfileOnGun too many times

- src/database/Persona/Persona.db.ts
> fix: emit profilesChanged on profile deleted

- src/social-network-provider/twitter.com/ui/injectPostDialogHint.tsx
- src/social-network-provider/twitter.com/utils/selector.ts
> Add hint button under popup dialog

- src/social-network-provider/options-page/index.ts
> fix: filter out profiles without fingerprint

- src/components/shared/SelectRecipients/SelectRecipients.tsx
- src/components/shared/SelectRecipients/SelectRecipientsDialog.tsx
> Filter out myself & no maskbook user from recipient profiles

- src/_locales/en/messages.json
- src/_locales/zh/messages.json
- src/components/InjectedComponents/PostDialog.tsx
- src/components/shared/SelectRecipients/SelectRecipients.tsx
- src/social-network-provider/twitter.com/ui/injectPostDialog.tsx
- src/social-network-provider/twitter.com/utils/theme.ts
> Add only myself switch under compose dialog

- src/social-network-provider/twitter.com/ui/index.ts
> Remove placeholder brackets from twitter payload

- src/components/shared/qrcode.tsx
- src/extension/options-page/DashboardDialogs/DialogBase.tsx
- src/extension/options-page/DashboardDialogs/Persona.tsx
- src/extension/options-page/DashboardInitSteps/Step1R.tsx
- src/utils/hooks/useQRCodeScan.tsx
- src/utils/hooks/useRequestCamera.ts
> feat: qr import

- src/extension/options-page/DashboardDialogs/Persona.tsx
`btoa` does not work on non-latin1 characters.
> fix: base64 encode error

- src/database/Persona/helpers.ts
> fix: update persona with the same key

- src/social-network-provider/twitter.com/utils/selector.ts
> Can not decrypt tweet in tread view

- src/social-network-provider/twitter.com/utils/fetch.ts
- src/social-network-provider/twitter.com/utils/selector.ts
> Get twitter post id from current url

- src/components/InjectedComponents/AdditionalPostBox.tsx
- src/components/InjectedComponents/ImmersiveSetup/SetupStepper.tsx
- src/components/InjectedComponents/PostDialogHint.tsx
- src/extension/content-script/tasks.ts
- src/extension/options-page/DashboardComponents/ProfileBox.tsx
- src/social-network-provider/facebook.com/UI/injectWelcomeBanner.tsx
- src/utils/hooks/useConnectingStatus.ts
+ keep immersive setup status after refresh
+ do not render `you have not set up...` banner if connecting
> feat: keep immersive setup status after refresh

- src/social-network-provider/twitter.com/ui/custom.ts
> Add default background

- src/plugins/Wallet/real.ts
> Update contract addr

- src/plugins/Wallet/UI/Dashboard/Dialogs/Wallet.tsx
- src/plugins/Wallet/formatter.ts
+ source: https://github.com/ethjs/ethjs-unit/blob/master/src/index.js
+ tools: https://web3-tools.netlify.com/
> Copy impl from ethjs-unit lib

- src/social-network-provider/twitter.com/ui/fetch.ts
- src/social-network-provider/twitter.com/utils/fetch.ts
- src/social-network-provider/twitter.com/utils/selector.ts
+ fix fail to parse tweet in quoteblock
+ fix can not decrypt when translation link displayed
> Fix tweet selector

- src/plugins/Wallet/formatter.ts
TEST CASE:
```formatBalance(0n, 1)```
> Keep tail zeros

- package.json
- src/manifest.json
- src/social-network-provider/twitter.com/encoding.ts
- src/social-network-provider/twitter.com/utils/fetch.ts
this should be included in 1.10.1
> fix: twitter url decode

- src/components/InjectedComponents/PersonKnown.tsx
- src/social-network-provider/facebook.com/UI/injectKnownIdentity.tsx
- src/social-network-provider/twitter.com/ui/injectKnownIdentity.tsx
> Fix PersonKnown component did not update in time

- src/social-network-provider/twitter.com/encoding.ts
- src/social-network-provider/twitter.com/utils/fetch.ts
+ Fix #725 Remove backtracking regexp.
+ Fix fail to decrypt retweet payload.
+ <del>Remove compatiable code for leacy twitter.</del>
> Fix twitter related bugs

- src/_locales/en/messages.json
- src/_locales/zh/messages.json
- src/components/InjectedComponents/PostDialog.tsx
- src/components/shared/SelectPeopleAndGroups/resolveSpecialGroupName.ts
> Update name of groups

- src/social-network-provider/twitter.com/utils/selector.ts
> Adjust injection position of hint component

- src/_locales/en/messages.json
- src/_locales/zh/messages.json
- src/components/shared-settings/useSettingsUI.tsx
- src/extension/options-page/Debug.tsx
- src/extension/options-page/Settings/settings.tsx
- src/index.tsx
- src/plugins/Wallet/UI/Developer/SelectEthereumNetwork.tsx
- src/stories/Settings.tsx
- src/stories/index.tsx
- src/stories/shared.tsx
> feat: impl settings

- src/components/shared/SelectRecipients/SelectRecipients.tsx
- src/components/shared/SelectRecipients/SelectRecipientsDialog.tsx
> [not master] fix: seperate groups when select recipients, close #639 

- src/social-network-provider/twitter.com/ui/custom.ts
- src/social-network-provider/twitter.com/ui/fetch.ts
- src/social-network-provider/twitter.com/ui/index.ts
- src/social-network-provider/twitter.com/utils/selector.ts
This PR includes some UX improvements:
+ constraint post collector skip tweets which unknown to Maskbook
+ syncing theme color happens immediately, no more flash of white in Dark Mode
+ <del>reduce updating times of identitifer listener</del>
+ <del>refactor `applyAdoptedStyleSheets`</del>
+ <del>maintain a cached style node and append it to shadow root with clone instead of create a new one every times</del>
+ <del>apply single shadow root should not update all living shadows</del>
#751
> Improvement Twitter UX

- src/components/shared/SelectRecipients/SelectRecipients.tsx
> Restore select specific recipients in normal mode

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/demand.md
- .github/ISSUE_TEMPLATE/task.md
Now using ISO week day for date notation per the advice by @septs.
> Update issue templates

- package.json
- src/background-service.ts
- webpack.config.js
- yarn.lock
> Add build-info to background page

- src/components/InjectedComponents/CommentBox.tsx
- src/utils/__tests__/hooks/useCaptureEvents.tsx
- src/utils/hooks/useCapturedEvents.ts
For more details [here](https://github.com/facebook/react/issues/14387#issuecomment-503616820) and [here](https://reactjs.org/docs/hooks-faq.html#how-can-i-measure-a-dom-node).
This PR fixed a bug which prevents user entering stuff before any recipents  selected (master branch).
> Trigger re-render when ref changs

- .vscode/settings.json
- package.json
- scripts/ci-build.ts
- scripts/postinstall.ts
Reverts DimensionDev/Maskbook#839
> Revert "Refactor workflow [part-2]"

- src/components/shared/SelectRecipients/SelectRecipients.tsx
> Selected count consistency

- src/components/InjectedComponents/ImmersiveSetup/DraggableDiv.tsx
- src/components/InjectedComponents/ImmersiveSetup/DraggablePaper.tsx
- src/components/InjectedComponents/ImmersiveSetup/SetupStepper.tsx
- src/social-network/defaults/taskStartImmersiveSetupDefault.tsx
- src/stories/Immersive-Setup.tsx
Known Issues: 
The outline of the draggable paper is removed for a smoother transition. It may affect the overall identifiability in the dark palette.
> chore: minimizable stepper

- src/components/InjectedComponents/PostDialog.tsx
- src/extension/options-page/DashboardComponents/AbstractTab.tsx
- src/social-network/ui.ts
> Update prelude of text payload

- src/social-network-provider/facebook.com/UI/collectPosts.tsx
> Fix can not decrypt comments

- src/components/InjectedComponents/PostDialogIcon.tsx
- src/components/Welcomes/Banner.tsx
- src/social-network-provider/twitter.com/ui/inject.tsx
- src/social-network-provider/twitter.com/ui/injectPostDialogIcon.tsx
- src/social-network-provider/twitter.com/utils/selector.ts
- src/social-network-provider/twitter.com/utils/theme.ts
> Add a maskbook icon in post dialog for mobile twitter

- package.json
- src/extension/background-script/SteganographyService.ts
- src/extension/mock-service.ts
- src/manifest.json
- src/social-network-provider/facebook.com/UI/collectPosts.tsx
- src/social-network-provider/facebook.com/tasks/uploadToPostBox.ts
- src/social-network-provider/twitter.com/ui/tasks.ts
- src/social-network-provider/twitter.com/utils/fetch.ts
- src/utils/__tests__/image.ts
- src/utils/image.ts
- src/utils/type-transform/String-ArrayBuffer.ts
> Hotfix for 1.10.11

- src/components/InjectedComponents/PostInspector.tsx
- src/database/Persona/Persona.db.ts
- src/database/__tests__/post.ts
- src/database/post.ts
- src/database/type.ts
- src/extension/background-script/CryptoServices/appendShareTarget.ts
- src/extension/background-script/CryptoServices/encryptTo.ts
- src/extension/background-script/CryptoServices/prepareOthersKeyForEncryption.ts
- src/extension/background-script/CryptoServices/prepareRecipientDetail.ts
- src/extension/background-script/Jobs/AutoShareToFriends.ts
- src/social-network-provider/twitter.com/ui/fetch.ts
- src/utils/messages.ts
- src/utils/type-transform/BackupFormat/JSON/DBRecord-JSON/PostRecord.ts
- src/utils/type-transform/BackupFormat/JSON/version-2.ts
> Adjust the way of current auto share impl

- src/components/DataSource/independent.ts
- src/components/DataSource/useActivatedUI.ts
- src/extension/options-page/DashboardInitSteps/Step2S.tsx
- src/extension/options-page/Home.tsx
- src/plugins/Wallet/UI/Dashboard/Wallets.tsx
- src/plugins/Wallet/wallet.ts
- src/social-network-provider/options-page/index.ts
- src/social-network/defaults/ui.ts
- src/social-network/ui.ts
> chore: move wallets and personas to independent data source

- src/components/shared-settings/createSettings.tsx
- yarn.lock
> Fix render in shadow settings not resolved

- src/_locales/en/messages.json
- src/_locales/zh/messages.json
| Original | New text |
| -------- | --------- |
| Database | Database without Wallet |
| 數據庫 | 資料庫（不含錢包）|
Reference:
https://wiki.mbalib.com/zh-tw/%E6%95%B0%E6%8D%AE%E5%BA%93
> chore: update copywrite

- src/database/Persona/helpers.ts
- src/plugins/Wallet/database/types.ts
- src/plugins/Wallet/wallet.ts
https://github.com/DimensionDev/Maskbook-Talks/issues/30
> if empty wallets then create a default wallet else noop

- src/_locales/en/messages.json
- src/_locales/zh/messages.json
- src/extension/options-page/DashboardDialogs/Persona.tsx
- src/extension/options-page/DashboardInitSteps/Step1S.tsx
> Prevent from creating persona if name or password absent

- src/social-network/defaults/taskStartImmersiveSetupDefault.tsx
- src/utils/jss/renderInShadowRoot.tsx
> Immersive setup popup cannot unmount

- src/extension/options-page/Home.tsx
Fix the auto-redirect not working.
More: [Workflow 1B: Core Init / Restore Backup](https://confluence.dimension.chat/pages/viewpage.action?pageId=2064444)
> Auto-redirect is not working

- src/extension/options-page/DashboardDialogs/Persona.tsx
- src/extension/options-page/DashboardInitSteps/Step1S.tsx
> The error UI of the persona form

- scripts/webextensiom-shim-prebuilt.ts
chore: reduce iOS build size, close #988
> chore: reduce iOS build size, close #988

- src/components/shared-settings/createSettings.tsx
> The ready promise of settings not resolved for the first time

- src/components/InjectedComponents/PostDialog.tsx
- src/extension/background-script/SteganographyService.ts
- src/plugins/Wallet/UI/Dashboard/Components/RedPacket.tsx
- src/plugins/Wallet/erc20.ts
- src/plugins/Wallet/erc20/mainnet.json
- src/plugins/Wallet/wallet.ts
- src/social-network/ui.ts
- src/stories/RedPackets.tsx
+ [x] Add [USDK](https://etherscan.io/token/0x1c48f86ae57291F7686349F12601910BD8D470bb) into token selection list
+ [x] Add [OKB](https://etherscan.io/token/0x75231f58b43240c9718dd58b4967c5114342a86c) as built-in ERC20 token
+ [x] Add OKB base image for post payload
Close #1028
> Add ERC20 token OKB

- src/extension/popup-page/index.tsx
- src/social-network-provider/twitter.com/ui/injectPostDialog.tsx
- src/social-network-provider/twitter.com/utils/theme.ts
Close #974
Pick the corresponding patch from the `feature/dashboard` branch.
> Fix popup UX

- package.json
- src/_locales/en/messages.json
- src/_locales/zh/messages.json
- src/manifest.json
- src/social-network-provider/twitter.com/ui/index.ts
- src/social-network-provider/twitter.com/ui/tasks.ts
EN: https://twitter.com/differui/status/1260128788517543936
ZH: https://twitter.com/differui/status/1260129165442822145
close #1067
> Update text payload

- package.json
- src/manifest.json
- src/social-network-provider/twitter.com/utils/fetch.ts
> Fix obsolete selector for twitter

- package.json
- src/_locales/en/messages.json
- src/_locales/zh/messages.json
- src/manifest.json
- src/plugins/Wallet/UI/Dashboard/Dialogs/Wallet.tsx
- src/social-network-provider/twitter.com/ui/index.ts
- src/social-network-provider/twitter.com/ui/tasks.ts
> OKB 1.10.16 (DO NOT MERGE ON GITHUB)

- .github/workflows/workflow.yml
> Add setup job for dependiences installing

- src/manifest.json
- src/social-network-provider/twitter.com/ui/fetch.ts
- src/social-network-provider/twitter.com/ui/index.ts
- src/social-network-provider/twitter.com/ui/injectMaskbookIcon.tsx
- src/social-network-provider/twitter.com/utils/selector.ts
- yarn.lock
See https://www.figma.com/file/xKe7ox6o2tchhifrqIEO2n/small-logos-in-twitter?node-id=0%3A1
> feat: impl add icon in twitter

- package.json
- src/manifest.json
- src/social-network-provider/facebook.com/tasks/pasteIntoPostBox.ts
> Fix auto pasting not working on Facebook

- package.json
- src/components/InjectedComponents/PostDialog.tsx
- src/components/shared-settings/createSettings.tsx
- src/components/shared-settings/settings.ts
- src/extension/content-script/tasks.ts
- src/manifest.json
- src/utils/browser.storage.ts
> Maskbook v1.10.20

- src/utils/type-transform/BackupFileShortRepresentation.ts
> Sanitize granted permissions

- src/_locales/en/messages.json
- src/_locales/zh/messages.json
- src/components/InjectedComponents/PersonKnown.tsx
> chore: fix #1255 remove seen in maskbook banner

- package.json
- src/background-service.ts
- src/components/DataSource/useExtensionPermission.ts
- src/components/InjectedComponents/PostDialog.tsx
- src/extension/background-script/ProviderService.ts
- src/extension/background-script/WelcomeService.ts
- src/extension/options-page/DashboardRouters/Settings.tsx
- src/extension/options-page/DashboardRouters/Setup.tsx
- src/extension/options-page/Welcome/getWelcomePageURL.tsx
- src/plugins/Wallet/UI/RedPacket/RedPacketInDecryptedPost.tsx
- src/settings/settings.ts
- src/social-network-provider/facebook.com/UI/injectOptionsPageLink.tsx
- src/utils/notification.ts
- webpack.config.js
- yarn.lock
> Fix dashboard bugs on Android

- src/_background_loader.1.ts
- src/_locales/en/messages.json
- src/_locales/zh/messages.json
- src/components/InjectedComponents/AdditionalPostContent.tsx
- src/components/InjectedComponents/DecryptedPost/DecryptedPost.tsx
- src/components/InjectedComponents/DecryptedPost/DecryptedPostDebug.tsx
- src/components/InjectedComponents/PostDialog.tsx
- src/components/InjectedComponents/PostInspector.tsx
- src/components/InjectedComponents/TypedMessageRenderer.tsx
- src/crypto/__tests__/crypto-alpha-38-test.ts
- src/crypto/crypto-alpha-38.ts
- src/crypto/crypto-alpha-40.ts
- src/extension/background-script/CryptoService.ts
- src/extension/background-script/CryptoServices/__tests__/encryptTo.ts
- src/extension/background-script/CryptoServices/decryptFrom.ts
- src/extension/background-script/CryptoServices/utils.ts
- src/extension/options-page/DeveloperComponents/DecryptPost.tsx
- src/extension/service.ts
- src/social-network-provider/facebook.com/UI/collectPosts.tsx
- src/social-network-provider/twitter.com/ui/fetch.ts
- src/social-network-provider/twitter.com/utils/fetch.ts
- src/social-network/PostInfo.ts
- src/stories/Injections.tsx
- src/stories/Plugin-RedPackets.tsx
**NOTE: This PR clean the barriers for #1338**
> Decrypt multiple payloads

- src/plugins/Wallet/erc20/mainnet.json
rm tokens duplicate w/ MetaMask's token list
> rm tokens duplicate w/ MetaMask's token list

- src/_locales/ja/messages.json
> Fix Japanese Locale

- package.json
- src/components/InjectedComponents/TypedMessageRenderer.tsx
- src/components/shared/Image.tsx
- src/protocols/typed-message/debugger.tsx
- src/protocols/typed-message/factory.ts
- src/protocols/typed-message/helpers.ts
- src/protocols/typed-message/types.ts
- src/setup.ui.ts
- src/social-network-provider/facebook.com/UI/collectPosts.tsx
- src/social-network-provider/twitter.com/ui/fetch.ts
- src/social-network/PostInfo.ts
- yarn.lock
> feature: parse original post as TypedMessage

- src/plugins/Trader/UI/ScreenModal.tsx
- src/plugins/Trader/define.tsx
- src/plugins/plugin.ts
> The Trader Plugin (View Price History)

- .git-utils/.gitflow-rc.json
- package.json
- yarn.lock
> chore: remove @nice-labs/git-flow-init

- src/plugins/Wallet/api.ts
The [`DECIMAL_PLACES`](https://mikemcl.github.io/bignumber.js/#decimal-places) about BigNumber.js.
> Avoid stringify big number into scientific format

- package.json
> chore: remove unused packages

- scripts/locale-kit.ts
Support
```tsx
const message = 'message'
const message1 = 'message1'
const message2 = 'message2'
t(message)
t(isTrue ? message1 : message2)
<UIComponent i18nKey={message}>
```
> chore: improve locale kit

- src/_locales/ja/messages.json
> Fix translation

- src/components/InjectedComponents/PostDialog.tsx
- src/stories/Injections.tsx
> feat: impl char limit close gh-1094

- .vscode/settings.json
see https://code.visualstudio.com/updates/v1_49#_only-format-modified-text
> chore: format on modified area

- src/components/shared/qrcode.tsx
> fix: cache qrcode

- src/social-network-provider/facebook.com/UI/injectPostBox.tsx
> chore(new facebook): post box inject right place

- src/social-network-provider/facebook.com/tasks/pasteIntoPostBox.ts
Fix bug, paste to the post box rather than comment box.
> fix: paste to postbox

- src/components/InjectedComponents/ImmersiveGuide/SetupGuide.tsx
- src/database/Persona/Persona.db.ts
> fix: setup identity ref after initializing persona (new facebook)

- src/_locales/en/messages.json
- src/_locales/ja/messages.json
- src/_locales/zh/messages.json
- src/components/DebugModeUI/DebugList.tsx
- src/components/InjectedComponents/DecryptedPost/DecryptedPost.tsx
- src/components/InjectedComponents/DecryptedPost/DecryptedPostDebug.tsx
- src/components/InjectedComponents/DecryptedPost/DecryptedPostSuccess.tsx
- src/components/InjectedComponents/PostInspector.tsx
- src/database/type.ts
- src/extension/background-script/CryptoServices/decryptFrom.ts
- src/network/gun/version.2/post.ts
> Fix: [Bug] Feature "View & Modify Recipients" gone

- src/social-network-provider/facebook.com/UI/collectPosts.tsx
- src/social-network-provider/facebook.com/UI/injectPostInspector.tsx
> fix: click expand button before read post node

- src/components/shared/EthereumAccountChip.tsx
- src/components/shared/SelectWallet/WalletInList.tsx
add avatar in uniswap trade view
fix wrong wallet icon after default wallet change in popup
> Feature: add avatar in uniswap trade view

- src/extension/options-page/DashboardDialogs/Wallet.tsx
- src/plugins/RedPacket/constants.ts
- src/plugins/RedPacket/state-machine.ts
- src/plugins/RedPacket/types.ts
> Red packet history service

- scripts/import-linter.ts
- scripts/locale-kit.ts
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-a-warning-message
> chore: add warning in gh-actions result

- src/components/InjectedComponents/CommentBox.tsx
- src/social-network-provider/facebook.com/UI/collectPosts.tsx
> fix: add comment box (new facebook)

- src/_locales/ja/messages.json
[Task] Japanese l10n Copywriting Review https://github.com/DimensionDev/Maskbook/issues/1569
> (1/2)review and fix /src/_locales/ja/messages.json

- src/utils/hooks/useMatchXS.ts
> feat: distinguish ui by platform

- src/components/shared/SelectRecipients/SelectRecipientsDialog.tsx
Close https://github.com/DimensionDev/Maskbook/issues/1311
> feat: add search for select specific contacts

- src/extension/options-page/DashboardDialogs/Contact.tsx
> chore: show userId when nickname absent

- src/components/shared/SelectRecipients/SelectRecipientsDialog.tsx
Make the height of List fixed as its initialization, won't change when searching.
> chore: improve special contacts list

- src/extension/options-page/DashboardDialogs/Contact.tsx
- src/extension/options-page/DashboardRouters/Contacts.tsx
https://github.com/vercel/swr/discussions/686
> chore: swr deprecated revalidate

- src/extension/options-page/DashboardDialogs/Base.tsx
> fix: mobile dialog width

- src/social-network-provider/facebook.com/tasks/pasteIntoPostBox.ts
> fix: fb emit autoPasteFailed

- src/web3/constants/index.ts
More: https://github.com/DimensionDev/Maskbook/runs/1246497304
> Use a different infura key in test mode

- src/components/InjectedComponents/PostDialog.tsx
https://github.com/DimensionDev/Maskbook/issues/1668
> chore: hide poll entrace on mobile

- src/extension/options-page/DashboardComponents/WalletContent.tsx
- src/extension/options-page/DashboardRouters/Wallets.tsx
close https://github.com/DimensionDev/Maskbook/issues/1702
> fix: mobile hide activity icon when no current wallet

- src/components/shared-settings/useSettingsUI.tsx
> fix: mobile settings page ui

- .github/ISSUE_TEMPLATE/demand.md
- src/plugins/Trader/UI/trending/PriceChart.tsx
- src/plugins/Trader/UI/trending/TrendingView.tsx
- src/plugins/Trader/constants/trending.ts
Close https://github.com/DimensionDev/Maskbook/issues/1726
> feat: link to cmc token

- src/social-network-provider/facebook.com/UI/injectPostBox.tsx
close https://github.com/DimensionDev/Maskbook/issues/1735
> fix: fb compose box disappear

- src/_locales/en/messages.json
- src/_locales/ja/messages.json
- src/_locales/zh/messages.json
- src/extension/options-page/DashboardComponents/WalletContent.tsx
- src/extension/options-page/DashboardDialogs/Persona.tsx
- src/extension/options-page/DashboardDialogs/Wallet.tsx
- src/utils/constants.ts
- src/utils/utils.ts
Close https://github.com/DimensionDev/Maskbook/issues/1130#issuecomment-710355154
> feat: limit persona and wallet name length

- src/social-network-provider/twitter.com/utils/selector.ts
> Fix injectMaskbookIcon

- src/_locales/en/messages.json
- src/_locales/ja/messages.json
- src/_locales/zh/messages.json
- src/components/InjectedComponents/AutoPasteFailedDialog.tsx
- src/components/InjectedComponents/PageInspector.tsx
- src/components/shared/DraggableDiv.tsx
close https://github.com/DimensionDev/Maskbook/issues/1751
> feat: mobile add auto copy failed button

- src/_locales/en/messages.json
- src/_locales/ja/messages.json
- src/_locales/zh/messages.json
- src/extension/options-page/DashboardDialogs/Base.tsx
- src/web3/UI/EthereumAccountChip.tsx
close https://github.com/DimensionDev/Maskbook/issues/1750
> chore: snackbar text

- .storybook/preview.js
- src/_locales/en/messages.json
- src/_locales/ja/messages.json
- src/_locales/zh/messages.json
- src/components/InjectedComponents/DecryptedPost/DecryptPostAwaiting.tsx
- src/components/InjectedComponents/DecryptedPost/DecryptPostFailed.tsx
- src/components/InjectedComponents/DecryptedPost/DecryptedPost.tsx
- src/components/InjectedComponents/DecryptedPost/DecryptedPostSuccess.tsx
- src/components/InjectedComponents/DecryptedPost/authorDifferentMessage.tsx
- src/extension/background-script/CryptoServices/encryptTo.ts
- src/extension/options-page/DeveloperComponents/DecryptPost.tsx
- src/stories/Injections.tsx
- src/utils/type-transform/Payload.ts
> feature: add author id in payload

- src/_locales/en/messages.json
- src/_locales/ja/messages.json
- src/_locales/zh/messages.json
- src/components/shared/ErrorBoundary.tsx
- src/extension/options-page/index.tsx
- src/utils/SSRRenderer.tsx
- src/utils/shadow-root/ShadowRootDialog.tsx
- src/utils/shadow-root/renderInShadowRoot.tsx
> feat: add more error boundaries to prevent whole app crash out of response

- package.json
- src/env.d.ts
- src/extension/options-page/DashboardComponents/TokenIcon.tsx
- src/web3/UI/EthereumBlockie.tsx
- src/web3/hooks/useBlockie.ts
- yarn.lock
Learn more: [ethereum-blockies](https://www.npmjs.com/package/ethereum-blockies)
> Add blockie for token icon

- package.json
- src/_locales/en/messages.json
- src/_locales/ja/messages.json
- src/_locales/zh/messages.json
- src/env.d.ts
- src/extension/options-page/DashboardComponents/WalletContent.tsx
- src/plugins/RedPacket/UI/RedPacket.tsx
- src/plugins/Trader/UI/uniswap/TradeForm.tsx
- src/plugins/Transak/UI/BuyTokenDialog.tsx
- src/plugins/Transak/UI/Transak.tsx
- src/plugins/Transak/constants.ts
- src/plugins/Transak/define.tsx
- src/plugins/Transak/hooks/useTransak.ts
- src/plugins/Transak/messages.ts
- src/plugins/plugin.ts
- src/utils/flags.ts
- yarn.lock
> Buy CryptoCurrency with Transak

- src/plugins/Trader/UI/trending/PriceChart.tsx
- src/plugins/Trader/UI/trending/TrendingView.tsx
close https://github.com/DimensionDev/Maskbook/issues/1726
> fix: only cmc jump

- packages/maskbook/src/components/InjectedComponents/PayloadReplacer.tsx
- packages/maskbook/src/components/InjectedComponents/TypedMessageRenderer.tsx
close https://github.com/DimensionDev/Maskbook/issues/1749
> chore: important color for link 

- packages/maskbook/src/components/InjectedComponents/PostDialog.tsx
- packages/maskbook/src/components/shared/DebugMetadataInspector.tsx
- packages/maskbook/src/components/shared/DebugTreeView.tsx
- packages/maskbook/src/components/shared/SelectRecipients/ClickableChip.tsx
- packages/maskbook/src/components/shared/SelectRecipients/SelectRecipients.tsx
- packages/maskbook/src/plugins/FileService/MainDialog.tsx
- packages/maskbook/src/plugins/Polls/UI/PollsDialog.tsx
- packages/maskbook/src/plugins/RedPacket/UI/RedPacketDialog.tsx
- packages/maskbook/src/protocols/typed-message/metadata.ts
- packages/maskbook/src/social-network/ui.ts
- packages/maskbook/src/utils/shadow-root/ShadowRootPopper.tsx
Entrance (only visible when debug mode is on)
Inspector
Auto completion
Validation
View / edit current metadata
> feat: add metadata inspector

- packages/maskbook/src/plugins/Wallet/services/wallet.ts
> chore: update wallet for same account

- packages/maskbook/src/plugins/RedPacket/theme.ts
> chore: redpacket input color

- packages/maskbook/src/plugins/Trader/contracts/usePairContract.ts
- packages/maskbook/src/web3/helpers.ts
- packages/maskbook/src/web3/hooks/useContract.ts
- packages/maskbook/src/web3/hooks/useMulticall.ts
Use [Mutlicall Contract](https://etherscan.io/address/0xeefba1e63905ef1d7acba5a8513c70307c1ce441#contracts) as hooks.
Learn more [multicall](https://github.com/makerdao/multicall).
> Add multicall hooks

- packages/maskbook/src/components/InjectedComponents/AdditionalPostContent.tsx
- packages/maskbook/src/components/InjectedComponents/TypedMessageRenderer.tsx
close https://github.com/DimensionDev/Maskbook/issues/1210
> chore: hint link color and text size

- packages/maskbook/src/components/InjectedComponents/PostDialog.tsx
> feat: resolve #1810

- package.json
- src/manifest.json
- src/web3/hooks/useTokensDetailedCallback.ts
> [Release] Hotfix 1.18.3 => 1.18.4 (patch) 

- package.json
- packages/maskbook/src/manifest.json
- packages/maskbook/src/plugins/Election2020/hooks/useMintCallback.ts
P.S. may fix a bug feedback from https://twitter.com/webbovich/status/1324227363660460032
> [Release] Hotfix 1.19.3 (patch) 

- packages/maskbook/src/components/shared/SelectRecipients/SelectRecipientsDialog.tsx
close https://github.com/DimensionDev/Maskbook/issues/1853
> fix: show select recipient search

- packages/maskbook/src/components/InjectedComponents/SelectPeopleDialog.tsx
close https://github.com/DimensionDev/Maskbook/issues/1852
> fix: unable to use close button

- package.json
- packages/maskbook/src/extension/options-page/DashboardDialogs/About.tsx
- packages/maskbook/src/manifest.json
- packages/maskbook/src/network/gun-servers.ts
- packages/maskbook/src/utils/hooks/useShareLink.ts
> [Release] Hotfix 1.19.5 (patch) 

- packages/maskbook/src/extension/background-script/PluginService.ts
- packages/maskbook/src/plugins/Election2020/helpers.ts
- packages/maskbook/src/plugins/Election2020/hooks/useMintCallback.ts
- packages/maskbook/src/plugins/Gitcoin/UI/Gitcoin.tsx
- packages/maskbook/src/plugins/Gitcoin/constants.ts
- packages/maskbook/src/plugins/Gitcoin/define.tsx
- packages/maskbook/src/plugins/Polls/UI/PollsDialog.tsx
- packages/maskbook/src/plugins/Polls/UI/PollsInPost.tsx
- packages/maskbook/src/plugins/Polls/utils.ts
- packages/maskbook/src/plugins/RedPacket/UI/RedPacketDialog.tsx
- packages/maskbook/src/plugins/RedPacket/UI/RedPacketInPost.tsx
- packages/maskbook/src/plugins/RedPacket/helpers.ts
- packages/maskbook/src/plugins/RedPacket/hooks/useClaimCallback.ts
- packages/maskbook/src/plugins/RedPacket/hooks/useRedPacket.ts
- packages/maskbook/src/plugins/Trader/UI/PageInspector.tsx
- packages/maskbook/src/plugins/Trader/messages.ts
- packages/maskbook/src/plugins/Trader/messages/TypedMessageCashTrending.tsx
- packages/maskbook/src/plugins/Trader/trending/useAvailableDataProviders.ts
- packages/maskbook/src/plugins/Trader/trending/useCurrentCurrency.ts
- packages/maskbook/src/plugins/Trader/trending/usePriceStats.ts
- packages/maskbook/src/plugins/Trader/trending/useTrending.ts
> Migrate all plugins (besides Wallet) to new RPC API

- .github/auto_assign.yml
see https://probot.github.io/apps/auto-assign/
> chore: add auto assign bot

- packages/maskbook/src/_locales/en/messages.json
- packages/maskbook/src/_locales/ja/messages.json
- packages/maskbook/src/_locales/zh/messages.json
- packages/maskbook/src/extension/background-script/EthereumServices/providers/MetaMask.ts
- packages/maskbook/src/plugins/RedPacket/UI/RedPacket.tsx
- packages/maskbook/src/plugins/Wallet/settings.ts
- packages/maskbook/src/web3/types.ts
> feat: lock metamask red packet

- packages/maskbook/src/extension/options-page/DashboardComponents/ProviderLine.tsx
- packages/maskbook/src/utils/flags.ts
part of https://github.com/DimensionDev/Maskbook/issues/1896
> chore: mobile connected user link

- packages/maskbook/src/extension/options-page/DashboardRouters/Contacts.tsx
- packages/maskbook/src/extension/options-page/DashboardRouters/Container.tsx
- packages/maskbook/src/extension/options-page/DashboardRouters/Nav.tsx
- packages/maskbook/src/extension/options-page/DashboardRouters/Personas.tsx
- packages/maskbook/src/extension/options-page/DashboardRouters/Wallets.tsx
- packages/maskbook/src/utils/flags.ts
- webpack.config.ts
part of https://github.com/DimensionDev/Maskbook/issues/1896
The UI details will be decided later.
> feat: mobile replace menu with fab

- packages/maskbook/src/components/DataSource/useMyPersonas.ts
> feat: mobile check persona

- packages/maskbook/src/extension/background-script/EthereumServices/providers/MetaMask.ts
https://docs.metamask.io/guide/ethereum-provider.html#networkchanged-deprecated
> chore: networkChanged to chainChanged

- packages/maskbook/src/components/Welcomes/Banner.tsx
> fix: mobile setup button

- packages/maskbook/src/background-service.ts
> feat: mobile launch page

- packages/maskbook/src/extension/options-page/DashboardRouters/Container.tsx
- packages/maskbook/src/extension/options-page/DashboardRouters/Wallets.tsx
- packages/maskbook/src/web3/UI/EthereumAccountButton.tsx
> feat: mobile connect wallet fab

- packages/maskbook/src/_locales/en/messages.json
- packages/maskbook/src/_locales/ja/messages.json
- packages/maskbook/src/_locales/zh/messages.json
- packages/maskbook/src/components/InjectedComponents/PostDialogHint.tsx
- packages/maskbook/src/components/InjectedComponents/PostDialogIcon.tsx
- packages/maskbook/src/components/Welcomes/Banner.tsx
- packages/maskbook/src/social-network-provider/facebook.com/UI/injectSetupPrompt.tsx
> chore: mobile compose entry ui

- packages/maskbook/src/components/InjectedComponents/AutoPasteFailedDialog.tsx
- packages/maskbook/src/extension/background-script/HelperService.ts
- packages/maskbook/src/extension/background-script/WelcomeService.ts
close https://github.com/DimensionDev/Maskbook/issues/1952
> fix: mobile file download error

- packages/maskbook/src/extension/options-page/DashboardComponents/ShowcaseBox.tsx
close https://github.com/DimensionDev/Maskbook/issues/1962
> feat: click copy backup text

- packages/maskbook/src/components/InjectedComponents/DecryptedPost/DecryptPostAwaiting.tsx
- packages/maskbook/src/components/InjectedComponents/DecryptedPost/DecryptedPost.tsx
- packages/maskbook/src/components/InjectedComponents/PostComments.tsx
- packages/maskbook/src/extension/background-script/CryptoServices/decryptFrom.ts
- packages/maskbook/src/social-network/PostInfo.ts
- packages/maskbook/src/social-network/defaults/injectCommentBox.tsx
- packages/maskbook/src/stories/Injections.tsx
close https://github.com/DimensionDev/Maskbook/issues/1957
> fix: fb decrypt image iv

- e2e/commands/facebook.ts
- e2e/commands/twitter.ts
- e2e/fixtures/post/post_backup_twitter.com.json
- e2e/integration/post/create.ts
- e2e/types/SNS.ts
- packages/maskbook/src/_locales/en/messages.json
- packages/maskbook/src/_locales/ja/messages.json
- packages/maskbook/src/_locales/zh/messages.json
- packages/maskbook/src/components/Welcomes/Banner.tsx
+ fix: the dom tree is shaking when the Maskbook icon was injected
+ fix: the selector of the hint button
> Fix the E2E failure caused by revamped composition UI

- package.json
- packages/maskbook/src/manifest.json
- packages/maskbook/src/plugins/Trader/UI/trader/TradeForm.tsx
- packages/maskbook/src/plugins/Trader/constants/0x.ts
- packages/maskbook/src/plugins/Trader/trader/0x/useTrade.ts
- packages/maskbook/src/plugins/Wallet/UI/WalletStatusDialog.tsx
+ Invoke swap API with `{ "affiliateAddress": "0x934B510D4C9103E6a87AEf13b816fb080286D649" }`
+ The browser treats the `<form />` element's buttons as submit buttons.
close #2012
> Release v1.20.1

- package.json
- packages/maskbook/src/manifest.json
- packages/maskbook/src/plugins/Gitcoin/UI/DonateDialog.tsx
- packages/maskbook/src/plugins/Trader/UI/trader/TradeView.tsx
- packages/maskbook/src/plugins/Trader/UI/trader/Trader.tsx
- packages/maskbook/src/plugins/Trader/UI/trending/PriceChart.tsx
- packages/maskbook/src/plugins/Trader/UI/trending/TrendingView.tsx
- packages/maskbook/src/plugins/Trader/UI/trending/TrendingViewDeck.tsx
- packages/maskbook/src/plugins/Trader/trader/uniswap/useAllCommonPairs.ts
- packages/maskbook/src/plugins/Trader/trader/uniswap/usePairs.ts
- packages/maskbook/src/plugins/Trader/trader/uniswap/useV2Trade.ts
- packages/maskbook/src/plugins/Wallet/UI/SelectWalletDialog.tsx
- packages/maskbook/src/plugins/Wallet/UI/WalletConnectQRCodeDialog/QRCodeModel.tsx
- packages/maskbook/src/plugins/Wallet/services/wallet.ts
- packages/maskbook/src/web3/hooks/useERC20TokenAllowance.ts
- packages/maskbook/src/web3/hooks/useERC20TokenApproveCallback.ts
> Release 1.20.2

- packages/maskbook/src/components/InjectedComponents/AutoPasteFailedDialog.tsx
- packages/maskbook/src/extension/background-script/HelperService.ts
- packages/maskbook/src/extension/background-script/WelcomeService.ts
- packages/maskbook/src/extension/options-page/DashboardDialogs/Backup.tsx
close https://github.com/DimensionDev/Maskbook/issues/1952
> fix: android download button

- package-lock.json
- package.json
- packages/maskbook/src/_locales/en/messages.json
- packages/maskbook/src/_locales/ja/messages.json
- packages/maskbook/src/_locales/zh/messages.json
- packages/maskbook/src/manifest.json
- packages/maskbook/src/plugins/Trader/UI/trader/TradeForm.tsx
- packages/maskbook/src/plugins/Trader/UI/trader/TradeSummary.tsx
- packages/maskbook/src/plugins/Trader/apis/trending/index.ts
- packages/maskbook/src/plugins/Trader/constants/trader.ts
- packages/maskbook/src/plugins/Trader/constants/uniswap.ts
- packages/maskbook/src/plugins/Trader/pipes.ts
- packages/maskbook/src/plugins/Trader/trader/uniswap/usePriceImpactWarningLevel.ts
- packages/maskbook/src/plugins/Trader/types/uniswap.ts
- packages/maskbook/src/utils/flags.ts
+ Turn on transak in prod mode.
+ Enhance the price impact of uniswap.
> Release 1.21.2

- scripts/locale-kit.ts
https://github.com/microsoft/TypeScript/pull/40325
> chore: simplify locale kit

- package-lock.json
- package.json
- packages/maskbook/src/manifest.json
- packages/maskbook/src/plugins/Trader/UI/trader/TradeSummary.tsx
- packages/maskbook/src/plugins/Trader/UI/trending/TrendingViewDeck.tsx
- packages/maskbook/src/plugins/Trader/apis/index.ts
- packages/maskbook/src/plugins/Trader/apis/uniswap/index.ts
- packages/maskbook/src/plugins/Trader/constants/uniswap.ts
- packages/maskbook/src/plugins/Trader/trader/uniswap/usePairs.ts
+ [ ] close #2029
+ [x] close #2033
+ [x] close #2048
> Release 1.21.3

- packages/maskbook/src/extension/options-page/DashboardDialogs/About.tsx
close https://github.com/DimensionDev/Maskbook/issues/2088
> chore: update about page

- packages/maskbook/src/plugins/Trader/trending/useSearchedKeyword.ts
close https://github.com/DimensionDev/Maskbook/issues/2087
> fix: click hashtag show trend

- packages/maskbook/src/plugins/Trader/trending/useSearchedKeyword.ts
fix https://github.com/DimensionDev/Maskbook/pull/2089
> fix: hashtag trending

- packages/maskbook/src/components/InjectedComponents/DecryptedPost/DecryptPostAwaiting.tsx
- packages/maskbook/src/components/InjectedComponents/DecryptedPost/DecryptedPost.tsx
- packages/maskbook/src/components/InjectedComponents/PostInspector.tsx
- packages/maskbook/src/extension/background-script/CryptoServices/decryptFrom.ts
- packages/maskbook/src/social-network/PostInfo.ts
> chore: set payload when decrypt img

- packages/maskbook/src/database/Plugin/wrap-plugin-database.ts
- packages/maskbook/src/plugins/RedPacket/database.ts
> fix: duplicate RedPacketRecord into db

- packages/maskbook/src/components/InjectedComponents/PostDialog.tsx
> chore: improve compose select recipients ux

- packages/maskbook/src/plugins/Wallet/formatter.ts
close https://github.com/DimensionDev/Maskbook/issues/2119
> fix: display small token price

- packages/maskbook/src/extension/options-page/DashboardDialogs/Wallet.tsx
> fix: wallet add token text

- README.md
- packages/maskbook/src/manifest.json
close https://github.com/DimensionDev/Maskbook/issues/2134
> chore: rename extension name

- packages/maskbook/src/plugins/Trader/UI/trending/TrendingViewDeck.tsx
- packages/maskbook/src/plugins/Transak/hooks/useTransakAllowanceCoin.ts
close https://github.com/DimensionDev/Maskbook/issues/2110
> chore: transak allow list

- package-lock.json
- package.json
- public/patches.js
https://github.com/crimx/webpack-target-webextension/issues/9
> chore: remove hacks on publicPath

- packages/maskbook/src/plugins/ITO/hooks/useClaimCallback.ts
> feat: check the remaining before sending the swap transaction

- packages/maskbook/src/extension/options-page/DashboardComponents/TransferDialog.tsx
- packages/maskbook/src/extension/options-page/DashboardComponents/WalletAssetsTable.tsx
- packages/maskbook/src/extension/options-page/DashboardComponents/WalletContent.tsx
- packages/maskbook/src/extension/options-page/DashboardRouters/Wallets.tsx
- packages/maskbook/src/web3/hooks/useAssetsDetailedCallback.ts
- packages/maskbook/src/web3/hooks/useAssetsDetailedChain.ts
- packages/maskbook/src/web3/hooks/useAssetsDetailedDebank.ts
- packages/maskbook/src/web3/hooks/useTokensBalance.ts
> fix: refresh wallet list after tx

- packages/maskbook/src/plugins/ITO/UI/ClaimDialog.tsx
- packages/maskbook/src/plugins/ITO/UI/ClaimGuide.tsx
- packages/maskbook/src/plugins/ITO/UI/ShareDialog.tsx
close #2213 
Tested, Make two swaps at the same time, one of them will swap less.
> fix: show actual swap amount

- packages/maskbook/src/plugins/Transak/hooks/useTransakAllowanceCoin.ts
> fix: transak should only support Ethereum cryptocurrencies #2189

- packages/maskbook/src/plugins/RedPacket/hooks/useCreateCallback.ts
- packages/maskbook/src/plugins/Trader/UI/trader/Trader.tsx
- packages/maskbook/src/plugins/Trader/UI/trending/SearchResultView.tsx
- packages/maskbook/src/plugins/Trader/UI/trending/TrendingView.tsx
- packages/maskbook/src/plugins/Trader/apis/trending/index.ts
- packages/maskbook/src/plugins/Trader/apis/trending/mirrored.json
- packages/maskbook/src/plugins/Trader/constants/trader.ts
- packages/maskbook/src/plugins/Trader/trader/useTradeState.ts
- packages/maskbook/src/plugins/Trader/types/trending.ts
> Swap mirrored tokens

- packages/maskbook/src/extension/options-page/DashboardComponents/TransferDialog.tsx
- packages/maskbook/src/plugins/COTM/UI/TokenPacket.tsx
- packages/maskbook/src/plugins/Election2020/UI/ElectionPacket.tsx
- packages/maskbook/src/plugins/Ethereum/UI/SelectERC20TokenDialog.tsx
- packages/maskbook/src/plugins/Ethereum/UI/TransactionDialog.tsx
- packages/maskbook/src/plugins/Ethereum/constants.ts
- packages/maskbook/src/plugins/Ethereum/define.tsx
- packages/maskbook/src/plugins/Ethereum/messages.ts
- packages/maskbook/src/plugins/Ethereum/services.ts
- packages/maskbook/src/plugins/Gitcoin/UI/DonateDialog.tsx
- packages/maskbook/src/plugins/ITO/UI/ClaimDialog.tsx
- packages/maskbook/src/plugins/ITO/UI/CreateGuide.tsx
- packages/maskbook/src/plugins/ITO/UI/ExchangeTokenPanel.tsx
- packages/maskbook/src/plugins/ITO/UI/ITO.tsx
- packages/maskbook/src/plugins/PluginUI.ts
- packages/maskbook/src/plugins/RedPacket/UI/RedPacket.tsx
- packages/maskbook/src/plugins/RedPacket/UI/RedPacketForm.tsx
- packages/maskbook/src/plugins/Trader/UI/trader/Trader.tsx
- packages/maskbook/src/plugins/Trader/UI/trending/TrendingPopper.tsx
- packages/maskbook/src/plugins/Wallet/define.tsx
- packages/maskbook/src/plugins/Wallet/messages.ts
- packages/maskbook/src/stories/Plugin-Gitcoin.tsx
- packages/maskbook/src/utils/flags.ts
- packages/maskbook/src/web3/hooks/useERC20TokenApproveCallback.ts
- packages/maskbook/src/web3/hooks/useTransactionDialog.ts
Move messages and dialogs from `WalletPlugins` to `EthereumDialog`.
> Add Ethereum Plugin

- packages/maskbook/src/extension/options-page/DashboardDialogs/Persona.tsx
When the  length of useMyPersonas return array is 1, use location.reload() refresh
close #2157
> feat: jump to setup screen when last persona is removed

- packages/maskbook/src/plugins/NFT/README.md
- packages/maskbook/src/plugins/NFT/UI/NFTCardUI.tsx
- packages/maskbook/src/plugins/NFT/UI/NFTInPost.tsx
- packages/maskbook/src/plugins/NFT/constants.ts
- packages/maskbook/src/plugins/NFT/define.tsx
- packages/maskbook/src/plugins/NFT/types.ts
- packages/maskbook/src/plugins/NFT/utils.ts
- packages/maskbook/src/plugins/PluginUI.ts
- packages/maskbook/src/protocols/typed-message/types.ts
> feat: add nft plugin

- packages/maskbook/src/plugins/Trader/UI/trending/SearchResultView.tsx
close #2238 The bug is due to there're some tokens which has data on DataProvider but nothing on chain. In this situation, we should fallback to use DataProvider.
fixed:
> fix: trending view keep loading without content

- packages/maskbook/src/extension/options-page/DashboardComponents/WalletAssetsTable.tsx
- packages/maskbook/src/extension/options-page/DashboardRouters/Wallets.tsx
- packages/maskbook/src/web3/hooks/useAssetsDetailedDebank.ts
- packages/maskbook/src/web3/hooks/useAssetsStableCoinDetailedDebank.ts
> fix:  hide small balance token in wallet #2117

- package-lock.json
- package.json
- packages/maskbook/src/extension/options-page/DashboardComponents/TokenIcon.tsx
- packages/maskbook/src/utils/hooks/useImageFailover.ts
close #2229 
https://raw.githubusercontent can't be reached on some v2ray servers.
https://rawcdn.githack is always reachable.
> feat: token icon source failover

- packages/maskbook/src/extension/background-script/EthereumServices/providers/MetaMask.ts
> fix: parse chainId

- packages/maskbook/src/database/Persona/Persona.db.ts
- packages/maskbook/src/extension/background-script/WelcomeServices/restoreBackup.ts
- packages/maskbook/src/extension/options-page/DashboardDialogs/Wallet.tsx
- packages/maskbook/src/plugins/Wallet/UI/SelectWalletDialog.tsx
- packages/maskbook/src/plugins/Wallet/helpers.ts
- packages/maskbook/src/plugins/Wallet/services/wallet.ts
> fix: select wallet from restoring DB

- packages/maskbook/src/social-network-provider/twitter.com/ui/fetch.ts
- packages/maskbook/src/social-network-provider/twitter.com/utils/fetch.ts
- packages/maskbook/src/social-network-provider/twitter.com/utils/selector.ts
> fix: the selector of quoted tweet (close #2230)

- packages/maskbook/src/plugins/Trader/UI/trending/TrendingView.tsx
Same as https://github.com/DimensionDev/Maskbook/pull/2240
> fix: hover trending view keep loading without content

- packages/maskbook/src/_locales/en/messages.json
- packages/maskbook/src/_locales/ja/messages.json
- packages/maskbook/src/_locales/zh/messages.json
- packages/maskbook/src/extension/background-script/EthereumServices/chainState.ts
- packages/maskbook/src/plugins/Trader/UI/trader/TradeForm.tsx
- packages/maskbook/src/plugins/Trader/UI/trader/Trader.tsx
- packages/maskbook/src/plugins/Trader/trader/uniswap/usePairs.ts
- packages/maskbook/src/utils/shadow-root/ShadowRootComponents.tsx
- packages/maskbook/src/utils/shadow-root/usePortalShadowRoot.tsx
- packages/maskbook/src/utils/utils.ts
- packages/maskbook/src/web3/UI/EthereumBlockNumber.tsx
> fix: the double refreshing problem

- packages/maskbook/src/_locales/en/messages.json
- packages/maskbook/src/_locales/ja/messages.json
- packages/maskbook/src/_locales/zh/messages.json
- packages/maskbook/src/extension/options-page/DashboardComponents/TransferDialog.tsx
- packages/maskbook/src/web3/UI/TokenAmountPanel.tsx
> chore: transfer input max button

- .husky/pre-commit
- package.json
see https://prettier.io/docs/en/precommit.html
> chore: minimize prettier check range

- packages/maskbook/src/extension/options-page/DashboardComponents/FixedTokenList.tsx
- packages/maskbook/src/plugins/Ethereum/UI/SelectERC20TokenDialog.tsx
- packages/maskbook/src/plugins/ITO/UI/ClaimDialog.tsx
> fix: ito swap token list empty

- packages/theme/src/Components/ButtonGroupTab/ButtonGroupTab.tsx
- packages/theme/src/Components/ButtonGroupTab/ButtonGroupTabList.tsx
- packages/theme/src/Components/ButtonGroupTab/index.ts
- packages/theme/src/Components/index.ts
- packages/theme/stories/atoms/Button.stories.tsx
- packages/theme/stories/atoms/Checkbox.stories.tsx
- packages/theme/stories/atoms/Dialog.stories.tsx
- packages/theme/stories/atoms/DialogExample.tsx
- packages/theme/stories/atoms/Input.stories.tsx
- packages/theme/stories/atoms/Radio.stories.tsx
- packages/theme/stories/atoms/Switch.stories.tsx
- packages/theme/stories/components/ButtonGroupTab.stories.tsx
- packages/theme/stories/components/CrashUI.stories.tsx
You can preview it in the https://deploy-preview-2364--compassionate-northcutt-326a3a.netlify.app/storybook-static/theme/?path=/story/components-button-group-tab--button-group-tab
> feat(theme): add button group tab

- packages/maskbook/src/utils/flags.ts
> hide chain network change setting on mobile

- package.json
- pnpm-lock.yaml
This is NOT HURRY. Merge this when we're free
> chore: upgrade react

- packages/maskbook/src/plugins/ITO/UI/ClaimDialog.tsx
fix slider undraggable bug
fix the bug set tokenAmount by click max button not equal to slide to the max.
> fix: token amount convert precision

- .eslintrc.json
- package.json
- packages/.eslintrc.json
- pnpm-lock.yaml
> chore: add import lodash error

- packages/maskbook/src/extension/options-page/DashboardDialogs/Wallet.tsx
> fix: correct the "create" wallet button title

- packages/maskbook/abis/HappyRedPacket.json
- packages/maskbook/src/contracts/HappyRedPacket.d.ts
- packages/maskbook/src/plugins/RedPacket/hooks/useAvailabilityComputed.ts
This addresses red packet claimed status issue, https://twitter.com/elivenC/status/1360882616484864000
after claim:
> chore: revert redpacket abi

- packages/maskbook/src/extension/options-page/DashboardComponents/WalletAssetsTable.tsx
close https://github.com/DimensionDev/Maskbook/issues/2396
> chore: not to display token name twice

- packages/maskbook/src/extension/options-page/DashboardComponents/WalletContent.tsx
> fix: add back menu button in mobile app

- packages/maskbook/src/plugins/ITO/UI/ExchangeTokenPanel.tsx
> fix: ito disable sell eth

- packages/maskbook/src/plugins/RedPacket/UI/RedPacketForm.tsx
- packages/maskbook/src/web3/UI/TokenAmountPanel.tsx
> fix: redpacket create form UI

- packages/maskbook/src/plugins/Trader/UI/trader/Trader.tsx
- packages/maskbook/src/plugins/Trader/UI/trending/SearchResultView.tsx
- packages/maskbook/src/plugins/Trader/UI/trending/TrendingView.tsx
close https://github.com/DimensionDev/Maskbook/issues/2393
> chore: switch provider keep same token

- packages/maskbook/src/_locales/en/messages.json
- packages/maskbook/src/extension/options-page/DashboardComponents/TransferDialog.tsx
- packages/maskbook/src/plugins/Gitcoin/UI/DonateDialog.tsx
- packages/maskbook/src/plugins/RedPacket/UI/RedPacketForm.tsx
- packages/maskbook/src/plugins/Trader/UI/trader/TradeForm.tsx
- packages/maskbook/src/plugins/Trader/UI/trader/Trader.tsx
- packages/maskbook/src/web3/UI/EthereumERC20TokenApprovedBoundary.tsx
- packages/maskbook/src/web3/UI/TokenAmountPanel.tsx
+ [x] the over-length token balance.
+ [x] the height of approve button.
> fix(ui): several UI problems 

- packages/maskbook/src/components/InjectedComponents/ToolbarAtTwitter.tsx
> fix: hide toolbar twitter photo page

- packages/maskbook/src/extension/options-page/DashboardComponents/TokenIcon.tsx
- packages/maskbook/src/plugins/Trader/apis/trending/hotfix.ts
- packages/maskbook/src/plugins/Trader/apis/trending/index.ts
- packages/maskbook/src/web3/constants/index.ts
> feat: mask network integration

- packages/maskbook/src/extension/options-page/DashboardContexts/BlurContext.tsx
fix: change chainId would close modal dialog, but background remains blur
> fix: ui modal unblur

- packages/maskbook/src/components/InjectedComponents/ToolbarAtTwitter.tsx
> chore: shrink tool bar

- packages/maskbook/src/extension/popup-page/UI.tsx
> fix: popup ui

- packages/maskbook/src/plugins/ITO/UI/CompositionDialog.tsx
- packages/maskbook/src/plugins/ITO/types.ts
1. click send in history.
2. enter ito dialog
> fix: create ito dialog tab

- packages/maskbook/src/components/InjectedComponents/ToolbarAtTwitter.tsx
Expand or shrink tool bar should not re-fetch token.
> chore: ui optimise toolbar shrink

- .github/workflows/linters.yml
see https://prettier.io/docs/en/cli.html#--list-different
> chore: improve prettier on ci

- packages/maskbook/src/extension/options-page/DashboardComponents/ContactLine.tsx
- packages/maskbook/src/extension/options-page/DashboardComponents/ERC20TokenActionsBar.tsx
- packages/maskbook/src/extension/options-page/DashboardComponents/PersonaCard.tsx
- packages/maskbook/src/extension/options-page/DashboardComponents/TokenActionsBar.tsx
- packages/maskbook/src/extension/options-page/DashboardComponents/WalletAssetsTable.tsx
- packages/maskbook/src/extension/options-page/DashboardComponents/WalletContent.tsx
- packages/maskbook/src/extension/options-page/DashboardDialogs/Wallet.tsx
- packages/maskbook/src/utils/hooks/useMenu.tsx
> refactor: mobile wallet table token action menu

- packages/cli-dev-build/netlify.js
- packages/dashboard/package.json
- packages/dashboard/public/index.html
- packages/dashboard/snowpack.config.js
- packages/dashboard/src/index.tsx
- packages/maskbook/miscs/manifest-modifiers.ts
- packages/maskbook/src/extension/background-script/Jobs/IsolatedDashboardBridge.ts
- packages/maskbook/src/extension/options-page/DashboardRouters/Settings.tsx
- packages/maskbook/src/settings/settings.ts
- packages/netlify/index.html
> feat: add dashboard build

- packages/maskbook/src/components/InjectedComponents/ToolbarAtTwitter.tsx
> fix: toolbar ui

- packages/maskbook/src/web3/hooks/useAssetsDetailedChain.ts
> fix: testnet wallet table ui

- packages/maskbook/src/components/InjectedComponents/ToolbarAtTwitter.tsx
> fix: tool bar ui

- packages/maskbook/src/plugins/RedPacket/UI/RedPacketForm.tsx
> fix: redpacket approve amount

- packages/maskbook/src/plugins/Gitcoin/define.tsx
- packages/maskbook/src/social-network-provider/facebook.com/worker-provider-next.ts
- packages/maskbook/src/social-network-provider/facebook.com/worker-provider.ts
close https://github.com/DimensionDev/Maskbook/issues/2565
> fix: gitcoin parse url

- packages/maskbook/src/extension/options-page/DashboardComponents/CollectibleList/Card.tsx
- packages/maskbook/src/extension/options-page/DashboardComponents/CollectibleList/index.tsx
- packages/maskbook/src/extension/options-page/DashboardComponents/TransactionList/Record.tsx
- packages/maskbook/src/extension/options-page/DashboardComponents/TransactionList/Row.tsx
- packages/maskbook/src/extension/options-page/DashboardComponents/TransactionList/index.tsx
- packages/maskbook/src/extension/options-page/DashboardComponents/TransactionList/types.ts
- packages/maskbook/src/extension/options-page/DashboardComponents/WalletAssetsTable.tsx
- packages/maskbook/src/extension/options-page/DashboardComponents/WalletContent.tsx
- packages/maskbook/src/plugins/Wallet/apis/debank.ts
- packages/maskbook/src/plugins/Wallet/apis/index.ts
- packages/maskbook/src/plugins/Wallet/apis/opensea.ts
- packages/maskbook/src/plugins/Wallet/hooks/useCollectibles.ts
- packages/maskbook/src/plugins/Wallet/services/assets.ts
- packages/maskbook/src/plugins/Wallet/services/index.ts
- packages/maskbook/src/plugins/Wallet/services/transactions.ts
- packages/maskbook/src/plugins/Wallet/types.ts
> feat: add collectibles list

- package.json
- pnpm-lock.yaml
https://github.com/plantain-00/type-coverage/issues/88
> chore: simplify type-coverage configuration

- packages/dashboard/src/components/Balance/index.tsx
- packages/dashboard/src/locales/en.json
- packages/dashboard/src/locales/zh.json
- packages/dashboard/stories/Balance.tsx
figma: https://www.figma.com/file/xxHFHHzRgN2E90xCOB83ae/Dashboard?node-id=2687%3A275943
preview:
> feat: balance card

- packages/maskbook/src/utils/shadow-root/renderInShadowRoot.tsx
> fix: setup close

- packages/maskbook/src/plugins/Trader/UI/trending/PopperView.tsx
- packages/maskbook/src/plugins/Trader/UI/trending/SearchResultView.tsx
> fix: the wrong loading condition

- packages/maskbook/src/extension/options-page/DashboardComponents/TransferDialog.tsx
- packages/maskbook/src/web3/hooks/useERC20TokenTransferCallback.ts
- packages/maskbook/src/web3/hooks/useEtherTransferCallback.ts
> refactor: transfer callback

- packages/maskbook/src/extension/options-page/DashboardComponents/WalletContent.tsx
close https://github.com/DimensionDev/Maskbook/issues/2594
> chore: wallet tab sub router

- packages/maskbook/src/components/InjectedComponents/PostDialog.tsx
- packages/maskbook/src/components/InjectedComponents/PostInspector.tsx
- packages/maskbook/src/components/InjectedComponents/SetupGuide.tsx
- packages/maskbook/src/extension/injected-script/CustomEvents.ts
- packages/maskbook/src/extension/injected-script/addEventListener.ts
- packages/maskbook/src/extension/injected-script/index.ts
- packages/maskbook/src/extension/injected-script/instagramUpload.ts
- packages/maskbook/src/extension/injected-script/user-agent.ts
- packages/maskbook/src/extension/injected-script/utils.ts
- packages/maskbook/src/social-network-adaptor/index.ts
- packages/maskbook/src/social-network-adaptor/instagram.com/base.ts
- packages/maskbook/src/social-network-adaptor/instagram.com/collecting/identity-provider.ts
- packages/maskbook/src/social-network-adaptor/instagram.com/collecting/posts.ts
- packages/maskbook/src/social-network-adaptor/instagram.com/index.ts
- packages/maskbook/src/social-network-adaptor/instagram.com/injection/Entry.tsx
- packages/maskbook/src/social-network-adaptor/instagram.com/injection/newPostComposition.tsx
- packages/maskbook/src/social-network-adaptor/instagram.com/injection/post-inspector.ts
- packages/maskbook/src/social-network-adaptor/instagram.com/shared.ts
- packages/maskbook/src/social-network-adaptor/instagram.com/ui-provider.ts
- packages/maskbook/src/social-network-adaptor/instagram.com/worker-provider.ts
- packages/maskbook/src/social-network/types.ts
- packages/maskbook/src/social-network/ui.ts
- packages/maskbook/src/social-network/worker.ts
- packages/maskbook/webpack.config.ts
> feat: support instagram

- packages/maskbook/src/plugins/Trader/UI/trending/PopperView.tsx
- packages/maskbook/src/plugins/Trader/UI/trending/PriceChart.tsx
- packages/maskbook/src/plugins/Trader/UI/trending/SearchResultView.tsx
- packages/maskbook/src/plugins/Trader/trending/usePriceStats.ts
close [#2677 ](https://github.com/DimensionDev/Maskbook/issues/2677)
> feat: add refresh button for trending graph

- packages/maskbook/src/extension/options-page/DashboardComponents/WalletAssetsTable.tsx
> fix: hide the expand button if nothing to view in expanded mode 

- packages/maskbook/src/plugins/Trader/UI/trending/LBPPanel.tsx
- packages/maskbook/src/plugins/Trader/UI/trending/LBPPriceChart.tsx
- packages/maskbook/src/plugins/Trader/UI/trending/PopperView.tsx
- packages/maskbook/src/plugins/Trader/UI/trending/PriceChart.tsx
- packages/maskbook/src/plugins/Trader/UI/trending/SearchResultView.tsx
- packages/maskbook/src/plugins/hooks/usePriceLineChart.ts
close [#2693 ](https://github.com/DimensionDev/Maskbook/issues/2693)
> feat: format PriceChart tooltip's currency value

- packages/maskbook/package.json
- packages/maskbook/src/plugins/FileService/arweave/remote-signing.ts
- pnpm-lock.yaml
> chore: upgrade arweave

- package.json
https://github.com/typicode/husky#usage
```console
$ pnpm install
Scope: all 9 workspace projects
Lockfile is up-to-date, resolution step is skipped
Already up-to-date
. prepare$ husky install
│ husky - Git hooks installed
└─ Done in 130ms
```
> chore: automate install husky

- packages/maskbook/src/plugins/NFT/constants.ts
- packages/maskbook/src/plugins/NFT/define.tsx
- packages/maskbook/src/plugins/NFT/utils.ts
- packages/maskbook/src/social-network-adaptor/twitter.com/collecting/post.ts
- packages/maskbook/src/social-network-adaptor/twitter.com/utils/selector.ts
> chore: inspect nft post

- packages/cli/build/build.ts
- packages/cli/build/dev.ts
- packages/cli/build/typescript.ts
- packages/shared/src/index.ts
- packages/storybook-shared/story-of.tsx
> fix: pre-build does not fail on ci

- packages/maskbook/src/extension/options-page/DashboardComponents/TransactionList/Row.tsx
- packages/maskbook/src/extension/options-page/DashboardComponents/TransactionList/index.tsx
> fix: transaction history ui error

- packages/maskbook/src/components/InjectedComponents/ToolboxHint.tsx
- packages/maskbook/src/resources/MaskbookIcon.tsx
- packages/maskbook/src/social-network-adaptor/twitter.com/injection/ToolboxHint.tsx
- packages/maskbook/src/utils/hooks/useMenu.tsx
> fix: improve toolbox in Twitter

- .vscode/settings.json
3rd-party (bounty) developer always forget to format files
> chore: format on save mode as file

- packages/maskbook/src/plugins/Wallet/hooks/useTransactions.ts
close [#2762 ](https://github.com/DimensionDev/Maskbook/issues/2762)
> fix: transaction refresh

- packages/maskbook/src/extension/options-page/DashboardComponents/CollectibleList/index.tsx
- packages/maskbook/src/extension/options-page/DashboardComponents/TransactionList/index.tsx
- packages/maskbook/src/utils/flags.ts
Add the paging flag of the transaction list
> feat: transaction pagination flag

- package.json
> chore: improve lint-staged

- .github/ISSUE_TEMPLATE/add-locale.md
- .github/ISSUE_TEMPLATE/bounty.md
- docs/README.md
- docs/bounty-guide.md
- docs/i18n-guide.md
> chore(docs): normalization bounty task

- packages/maskbook/src/social-network-adaptor/twitter.com/collecting/post.ts
- packages/maskbook/src/social-network-adaptor/twitter.com/utils/fetch.ts
> fix: cannot decrypt image payload

- packages/maskbook/src/social-network-adaptor/twitter.com/collecting/post.ts
Note: this is a workaround (but maybe it is even better than `MutationObserverWatcher`?)
> fix: post timeline not update

- packages/maskbook/src/_locales/ja/messages.json
- packages/maskbook/src/_locales/zh/messages.json
- packages/maskbook/src/extension/options-page/DashboardComponents/PersonaCard.tsx
- packages/maskbook/src/extension/options-page/DashboardRouters/Personas.tsx
A row can be fully filled
| before | after |
| -- | -- |
|  ![image](https://user-images.githubusercontent.com/1141198/114165193-c4a42780-995e-11eb-97e0-863bf6e0cc73.png) | ![image](https://user-images.githubusercontent.com/1141198/114167065-1057d080-9961-11eb-888e-53b48c0f4ce3.png) |
Shadow of the card shows now
| before | after |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/1141198/114165146-b48c4800-995e-11eb-8e71-5e50e807eeb2.png) | ![image](https://user-images.githubusercontent.com/1141198/114164988-89a1f400-995e-11eb-99c7-7106b789dc33.png) |
> fix: improve layout of persona list

- packages/maskbook/src/_locales/en/messages.json
- packages/maskbook/src/_locales/ja/messages.json
- packages/maskbook/src/_locales/zh/messages.json
- packages/maskbook/src/extension/options-page/DashboardComponents/FooterLine.tsx
> chore: add bounty list

- .github/ISSUE_TEMPLATE/bug.md
> docs: make bug template more dense

- docs/caveats.md
> docs: update caveats

- packages/maskbook/src/extension/options-page/DashboardComponents/WalletContent.tsx
- packages/maskbook/src/extension/options-page/DashboardRouters/Container.tsx
- packages/maskbook/src/extension/options-page/DashboardRouters/Personas.tsx
> chore(ui): expand content area

- packages/maskbook/src/social-network-adaptor/facebook.com/ui-provider.ts
- packages/maskbook/src/social-network-adaptor/twitter.com/ui-provider.ts
- packages/shared/src/Identifier/type.ts
> fix: use settings might be empty as source of truth of identity close #2807

- packages/cli/build/netlify.ts
- packages/shared/src/ShadowRoot/Portal.tsx
> fix: usePortalShadowRoot performance problem

- packages/maskbook/src/components/InjectedComponents/BreakdownDialog.tsx
- packages/maskbook/src/components/InjectedComponents/ToolboxHint.tsx
> fix: remove Mask Airdrop Functionality

- packages/maskbook/src/_locales/ja/messages.json
- packages/maskbook/src/_locales/zh/messages.json
- packages/maskbook/src/extension/options-page/DashboardComponents/CollectibleList/index.tsx
- packages/maskbook/src/extension/options-page/DashboardComponents/TransactionList/Row.tsx
- packages/maskbook/src/extension/options-page/DashboardComponents/TransactionList/index.tsx
- packages/maskbook/src/extension/options-page/DashboardComponents/WalletAssetsTable.tsx
- packages/maskbook/src/plugins/ITO/UI/ExchangeTokenPanel.tsx
- packages/maskbook/src/plugins/RedPacket/UI/RedPacket.tsx
- packages/maskbook/src/plugins/Wallet/apis/opensea.ts
- packages/maskbook/src/plugins/Wallet/apis/zerion.ts
- packages/maskbook/src/plugins/Wallet/hooks/useCollectibles.ts
- packages/maskbook/src/plugins/Wallet/hooks/useTransactions.ts
- packages/maskbook/src/plugins/Wallet/services/assets.ts
- packages/maskbook/src/plugins/Wallet/services/transactions.ts
- packages/maskbook/src/utils/flags.ts
> feat: wallet list pagination

- packages/maskbook/src/manifest.json
- packages/maskbook/src/plugins/PluginUI.ts
- packages/maskbook/src/utils/flags.ts
#2843 was closed by bot. So I have to create another one.
> Merge 1.30.3 to master

- packages/cli/build/dev.ts
- packages/maskbook/src/extension/options-page/DashboardRouters/Settings.tsx
- packages/maskbook/webpack.config.ts
> chore: optimizations on new dashboard dev

- packages/maskbook/src/plugins/Wallet/pipes/index.ts
> fix: opensea link

- docs/caveats.md
- packages/maskbook/src/content-script.ts
- packages/maskbook/src/extension/content-script/hmr.ts
- packages/maskbook/src/extension/content-script/index.tsx
- packages/maskbook/webpack.config.ts
> feat: hmr no longer requires https now

- packages/maskbook/src/extension/background-script/ProviderService.ts
- packages/maskbook/src/extension/options-page/DashboardRouters/Wallets.tsx
> refactor: lead the user to create a wallet

- packages/maskbook/src/_locales/en/messages.json
- packages/maskbook/src/extension/options-page/DashboardComponents/ProfileBox.tsx
- packages/maskbook/src/extension/popup-page/UI.tsx
- packages/maskbook/src/social-network-adaptor/facebook.com/base.ts
- packages/maskbook/src/social-network-adaptor/facebook.com/ui-provider.ts
- packages/maskbook/src/social-network-adaptor/instagram.com/base.ts
- packages/maskbook/src/social-network-adaptor/instagram.com/ui-provider.ts
- packages/maskbook/src/social-network-adaptor/options-page/index.ts
- packages/maskbook/src/social-network-adaptor/popup-page/index.ts
- packages/maskbook/src/social-network-adaptor/twitter.com/base.ts
- packages/maskbook/src/social-network-adaptor/twitter.com/shared.ts
- packages/maskbook/src/social-network-adaptor/twitter.com/ui-provider.ts
- packages/maskbook/src/social-network-adaptor/twitter.com/utils/isMobile.ts
- packages/maskbook/src/social-network/types.ts
- packages/maskbook/src/social-network/ui.ts
- packages/maskbook/src/social-network/utils/permissions.ts
- packages/maskbook/src/utils/type-transform/BackupFormat/JSON/latest.ts
- packages/maskbook/src/utils/type-transform/BackupFormat/JSON/version-2.ts
>  fix: add migration of missing permission close gh-2680

- packages/cli/build/netlify.ts
- packages/icons/.gitignore
- packages/icons/index.html
- packages/icons/package.json
- packages/icons/snowpack.config.cjs
- packages/icons/tsconfig.json
- packages/icons/utils/dev.tsx
- packages/icons/utils/previewer.tsx
- packages/icons/utils/ssr.tsx
- packages/netlify/index.html
> fix: netlify close gh-2876

- packages/maskbook/src/resources/tool-icon/index.ts
> fix: resolve gh-2891

- packages/maskbook/src/plugins/Airdrop/hooks/useClaimCallback.ts
- packages/maskbook/src/plugins/Gitcoin/hooks/useDonateCallback.ts
- packages/maskbook/src/plugins/ITO/hooks/useClaimCallback.ts
- packages/maskbook/src/plugins/ITO/hooks/useDestructCallback.ts
- packages/maskbook/src/plugins/ITO/hooks/useFillCallback.ts
- packages/maskbook/src/plugins/ITO/hooks/useSwapCallback.ts
- packages/maskbook/src/plugins/RedPacket/hooks/useClaimCallback.ts
- packages/maskbook/src/plugins/RedPacket/hooks/useCreateCallback.ts
- packages/maskbook/src/plugins/RedPacket/hooks/useRefundCallback.ts
- packages/maskbook/src/plugins/Trader/trader/0x/useTradeCallback.ts
- packages/maskbook/src/plugins/Trader/trader/balancer/useTradeCallback.ts
- packages/maskbook/src/plugins/Trader/trader/uniswap/useTradeCallback.ts
- packages/maskbook/src/web3/helpers.ts
- packages/maskbook/src/web3/hooks/useERC20TokenApproveCallback.ts
- packages/maskbook/src/web3/hooks/useEtherTransferCallback.ts
> chore: simplify gas margin

- packages/maskbook/src/components/InjectedComponents/BreakdownDialog.tsx
- packages/maskbook/src/extension/options-page/DashboardComponents/WalletAssetsTable.tsx
- packages/maskbook/src/extension/options-page/DashboardDialogs/Wallet.tsx
- packages/maskbook/src/plugins/Gitcoin/UI/DonateDialog.tsx
- packages/maskbook/src/plugins/ITO/UI/ClaimDialog.tsx
- packages/maskbook/src/plugins/ITO/UI/CompositionDialog.tsx
- packages/maskbook/src/plugins/ITO/UI/ConfirmDialog.tsx
- packages/maskbook/src/plugins/ITO/UI/CreateForm.tsx
- packages/maskbook/src/plugins/ITO/UI/ITO.tsx
- packages/maskbook/src/plugins/ITO/UI/ITO_Card.tsx
- packages/maskbook/src/plugins/ITO/UI/PoolInList.tsx
- packages/maskbook/src/plugins/ITO/UI/ShareDialog.tsx
- packages/maskbook/src/plugins/ITO/define.tsx
- packages/maskbook/src/plugins/RedPacket/UI/RedPacket.tsx
- packages/maskbook/src/plugins/RedPacket/UI/RedPacketForm.tsx
- packages/maskbook/src/plugins/RedPacket/UI/RedPacketInList.tsx
- packages/maskbook/src/plugins/RedPacket/define.tsx
- packages/maskbook/src/plugins/Trader/UI/balancer/TradeRoute.tsx
- packages/maskbook/src/plugins/Trader/UI/trader/TokenPanel.tsx
- packages/maskbook/src/plugins/Trader/UI/trader/TradeSummary.tsx
- packages/maskbook/src/plugins/Trader/UI/trader/Trader.tsx
- packages/maskbook/src/plugins/Trader/trader/useTradeStateComputed.ts
- packages/maskbook/src/plugins/Wallet/formatter.ts
> chore: simplify format balance (part 2)

- packages/maskbook/src/extension/options-page/DashboardDialogs/Wallet.tsx
- packages/maskbook/src/plugins/Gitcoin/UI/DonateDialog.tsx
- packages/maskbook/src/plugins/ITO/UI/ClaimDialog.tsx
- packages/maskbook/src/plugins/ITO/UI/ClaimGuide.tsx
- packages/maskbook/src/plugins/ITO/UI/CreateForm.tsx
- packages/maskbook/src/plugins/ITO/UI/ShareDialog.tsx
- packages/maskbook/src/plugins/RedPacket/UI/RedPacketForm.tsx
- packages/maskbook/src/web3/helpers.ts
- packages/maskbook/src/web3/hooks/useERC20TokenApproveCallback.ts
- packages/maskbook/src/web3/hooks/useERC20TokenTransferCallback.ts
- packages/maskbook/src/web3/hooks/useEtherTransferCallback.ts
> chore: simplify big number using

- packages/shared/src/ShadowRoot/ShadowRootStyleProvider.tsx
> fix: cannot read property cssRules of null close gh-2834

- packages/maskbook/src/plugins/Trader/UI/trending/PopperView.tsx
- packages/maskbook/src/plugins/Trader/UI/trending/SearchResultView.tsx
- packages/maskbook/src/plugins/Trader/UI/trending/TrendingViewDeck.tsx
> fix(trending): shows available data/trade providers only

- packages/maskbook/src/plugins/RedPacket/define.tsx
> chore: fix redpacket label amount

- packages/maskbook/src/plugins/Wallet/apis/zerion.ts
> chore: shut zerion down

- packages/maskbook/src/components/InjectedComponents/ToolboxHint.tsx
- packages/maskbook/src/plugins/Trader/UI/trader/TradeFooter.tsx
- packages/maskbook/src/plugins/Trader/UI/trader/Trader.tsx
- packages/maskbook/src/plugins/Trader/UI/trader/TraderDialog.tsx
- packages/maskbook/src/plugins/Trader/UI/trending/TrendingViewDeck.tsx
- packages/maskbook/src/plugins/Trader/define.tsx
- packages/maskbook/src/plugins/Trader/messages.ts
- packages/maskbook/src/resources/tool-icon/index.ts
- packages/maskbook/src/utils/hooks/useRemoteControlledDialog.ts
> feat: add a separate swap dialog

- packages/maskbook/src/components/InjectedComponents/ToolboxHint.tsx
> chore: ui toolbox menu cut off

- packages/maskbook/src/_locales/en/messages.json
- packages/maskbook/src/_locales/ja/messages.json
- packages/maskbook/src/_locales/zh/messages.json
- packages/maskbook/src/plugins/ITO/UI/ClaimDialog.tsx
- packages/maskbook/src/plugins/ITO/UI/ConfirmDialog.tsx
- packages/maskbook/src/plugins/ITO/hooks/useSwapCallback.ts
> feat: receive tx hash redirect

- packages/maskbook/src/plugins/Trader/UI/trending/SearchResultView.tsx
- packages/maskbook/src/plugins/Trader/UI/trending/TrendingViewError.tsx
- packages/maskbook/src/utils/hooks/useSettingSwitcher.tsx
> fix: add an provider switcher as reaction to trending error

- packages/maskbook/src/plugins/ITO/UI/ClaimDialog.tsx
- packages/maskbook/src/plugins/ITO/constants.ts
Redirect to tx url as soon as recieving tx hash without click close dialog button.
> chore: recieve tx hash redirect

- packages/maskbook/src/plugins/ITO/UI/ITO.tsx
- packages/maskbook/src/plugins/ITO/constants.ts
> chore: update contract

- packages/maskbook/src/extension/options-page/DashboardComponents/FixedTokenList.tsx
> fix: set mask as the primary token

- packages/maskbook/src/plugins/ITO/UI/ITO.tsx
- packages/maskbook/src/plugins/ITO/hooks/useAvailabilityComputed.ts
- packages/maskbook/src/plugins/ITO/hooks/useSwapCallback.ts
- packages/maskbook/src/plugins/Polls/UI/PollsInPost.tsx
- packages/maskbook/src/plugins/Snapshot/hooks/useProposal.ts
- packages/maskbook/src/plugins/Trader/apis/trending/index.ts
closes #
see https://mdn.io/date/now
> chore: simplify get now

- packages/maskbook/src/plugins/ITO/UI/ITO.tsx
> chore: fix claimed button

- packages/maskbook/src/utils/hooks/useMenu.tsx
> feat: add useShadowRoot option with useMenu

- packages/maskbook/src/plugins/ITO/UI/ITO.tsx
> fix: ito graph exception

- docs/local-or-remote-dialog.md
> docs: add dialog guide

- packages/maskbook/src/social-network-adaptor/twitter.com/injection/PostInspector.tsx
> fix: lost links

- packages/maskbook/src/extension/options-page/DashboardComponents/CollectibleList/index.tsx
> fix: style error in the collectible tab 

- packages/maskbook/src/_locales/en/messages.json
- packages/maskbook/src/plugins/ITO/UI/ConfirmDialog.tsx
> fix: ito ui detail

- packages/maskbook/src/plugins/ITO/hooks/useClaimCallback.ts
> fix: ito claim re-check

- packages/maskbook/src/plugins/Collectible/UI/Account.tsx
- packages/maskbook/src/plugins/Collectible/UI/TokenTab.tsx
- packages/maskbook/src/plugins/Collectible/constants.ts
- packages/maskbook/src/plugins/Collectible/pipes/index.ts
> feat: add trait url

- packages/maskbook/src/plugins/Trader/UI/trending/PriceChart.tsx
- packages/maskbook/src/plugins/Trader/graphs/usePriceLineChart.ts
- packages/maskbook/src/plugins/hooks/usePriceLineChart.ts
> chore(UI): adjust tooltip aligned

- packages/maskbook/src/plugins/Collectible/hooks/useAsset.ts
- packages/maskbook/src/plugins/Collectible/types/opensea.ts
> feat: hidden bid button with owner

- packages/maskbook/src/plugins/ITO/hooks/useAvailabilityComputed.ts
Add expired label for legacy ITO
> fix: old ito expired ui

- packages/maskbook/src/extension/background-script/EthereumServices/chainState.ts
- packages/maskbook/src/extension/background-script/EthereumServices/providers/Maskbook.ts
- packages/maskbook/src/extension/background-script/EthereumServices/providers/MetaMask.ts
- packages/maskbook/src/extension/background-script/EthereumServices/providers/WalletConnect.ts
- packages/maskbook/src/extension/background-script/EthereumServices/send.ts
- packages/maskbook/src/extension/options-page/DashboardRouters/Settings.tsx
- packages/maskbook/src/plugins/Wallet/settings.ts
- packages/maskbook/src/settings/settings.ts
- packages/maskbook/src/web3/hooks/useBlockNumber.ts
> refactor: move settings

- packages/maskbook/src/plugins/Trader/apis/trending/hotfix.ts
- packages/maskbook/src/plugins/Trader/apis/trending/index.ts
> chore: simplify trending apis

- packages/maskbook/src/social-network-adaptor/twitter.com/injection/PostDialog.tsx
- packages/maskbook/src/social-network-adaptor/twitter.com/injection/PostInspector.tsx
> feat: hide media card from twitter

- packages/shared/src/TypedMessage/utils/internal.ts
> fix: adjust `createIsType` judgment conditions

- packages/maskbook/src/plugins/ITO/UI/CreateForm.tsx
> fix: ito show default contract

- packages/maskbook/src/plugins/Collectible/hooks/useOrders.ts
> fix: correct expiration time in collectible

- packages/maskbook/src/plugins/Trader/UI/trader/TradeFooter.tsx
- packages/maskbook/src/plugins/Trader/UI/trending/TrendingViewDeck.tsx
> fix: missing border of TradeFooter

- packages/maskbook/src/plugins/Trader/UI/trending/CoinMetadataTable.tsx
- packages/maskbook/src/plugins/Trader/UI/trending/CoinMetadataTags.tsx
- packages/maskbook/src/plugins/Trader/UI/trending/Linking.tsx
> fix: trader plugin CMC/Gecko token tag display glitch

- packages/maskbook/src/plugin-infra/host.ts
- packages/plugin-infra/README.md
- packages/plugin-infra/src/manager/dashboard.ts
- packages/plugin-infra/src/manager/manage.ts
- packages/plugin-infra/src/manager/sns-adaptor.ts
- packages/plugin-infra/src/manager/worker.ts
- packages/plugin-infra/src/types.ts
- packages/plugin-infra/src/utils/internal.ts
- packages/plugins/example/src/Dashboard/index.tsx
- packages/plugins/example/src/SNSAdaptor/index.tsx
- packages/plugins/example/src/Worker/index.ts
- packages/plugins/example/src/index.ts
> docs: enrich the document of the new plugin infra

- packages/maskbook/src/plugins/Collectible/UI/TokenTab.tsx
- packages/maskbook/src/plugins/Collectible/hooks/useAsset.ts
- packages/maskbook/src/plugins/Collectible/pipes/index.ts
- packages/maskbook/src/plugins/Collectible/types/opensea.ts
- packages/maskbook/src/plugins/Collectible/types/rarible.ts
> fix: collectible trait url

- packages/maskbook/src/components/InjectedComponents/SetupGuide.tsx
- packages/maskbook/src/extension/options-page/DashboardDialogs/Base.tsx
- packages/maskbook/src/extension/options-page/DashboardRouters/Setup.tsx
> fix: input style does not correct, close  #3090

- packages/maskbook/src/plugins/Collectible/hooks/useAsset.ts
> fix: rarible image display glitch

- packages/maskbook/src/_locales/en/messages.json
- packages/maskbook/src/_locales/ja/messages.json
- packages/maskbook/src/_locales/zh/messages.json
- packages/maskbook/src/plugins/Ethereum/UI/TransactionDialog.tsx
- packages/maskbook/src/plugins/Ethereum/constants.ts
- packages/maskbook/src/web3/hooks/useTransactionState.ts
> chore: rpc server error msg

- packages/maskbook/src/plugins/ITO/UI/ClaimAllDialog.tsx
close https://github.com/DimensionDev/Maskbook/issues/3106
> fix: ito text color

- packages/dashboard/.storybook/preview.js
- packages/dashboard/src/App.tsx
- packages/dashboard/src/index.tsx
- packages/maskbook/src/extension/dashboard/index.tsx
- packages/maskbook/src/extension/options-page/index.tsx
- packages/maskbook/src/extension/popup-page/UI.tsx
- packages/theme/.storybook/preview.js
> fix: css order

- packages/maskbook/src/extension/background-script/EthereumServices/tokenList.ts
- packages/maskbook/src/extension/options-page/DashboardComponents/TokenIcon.tsx
- packages/maskbook/src/extension/options-page/DashboardComponents/WalletAssetsTable.tsx
- packages/maskbook/src/plugins/Collectible/UI/TokenTab.tsx
- packages/maskbook/src/plugins/ITO/UI/ConfirmDialog.tsx
- packages/maskbook/src/plugins/ITO/UI/RemindDialog.tsx
- packages/maskbook/src/plugins/ITO/UI/UnlockDialog.tsx
- packages/maskbook/src/plugins/Trader/UI/trending/CoinMarketTable.tsx
- packages/maskbook/src/plugins/Trader/UI/trending/CoinMetadataTable.tsx
- packages/maskbook/src/plugins/Trader/UI/trending/TickersTable.tsx
- packages/maskbook/src/plugins/Trader/UI/trending/TrendingViewDeck.tsx
- packages/maskbook/src/plugins/Wallet/UI/WalletStatusDialog.tsx
- packages/maskbook/src/plugins/Wallet/hooks/useAssets.ts
- packages/maskbook/src/plugins/Wallet/hooks/useAssetsMerged.ts
- packages/maskbook/src/plugins/Wallet/services/assets.ts
- packages/maskbook/src/plugins/Wallet/services/erc1155.ts
- packages/maskbook/src/plugins/Wallet/services/erc20.ts
- packages/maskbook/src/plugins/Wallet/services/erc721.ts
- packages/maskbook/src/plugins/Wallet/services/helpers.ts
- packages/maskbook/src/plugins/Wallet/services/wallet.ts
- packages/maskbook/src/web3/hooks/useERC20TokenDetailed.ts
- packages/maskbook/src/web3/hooks/useERC721TokenDetailed.ts
- packages/maskbook/src/web3/hooks/useStableTokensDebank.ts
- packages/shared/src/wallet/components.tsx
- packages/shared/src/wallet/formatter.tsx
closes #
+ Remove `formatToken`
+ Remove `formatChecksumAddress `
> refactor: formatter

- jest.config.ts
> chore: migrate jest

- packages/maskbook/src/content-script.ts
- packages/maskbook/src/extension/background-script/Jobs/InjectContentScripts.ts
- packages/maskbook/src/extension/options-page/index.tsx
- packages/maskbook/src/extension/popup-page/UI.tsx
- packages/maskbook/src/extension/popup-page/index.tsx
- packages/maskbook/src/setup.ui.ts
- packages/maskbook/src/social-network-adaptor/index.ts
- packages/maskbook/src/social-network/define.ts
- packages/maskbook/src/social-network/index.ts
- packages/maskbook/src/social-network/ui.ts
- packages/maskbook/src/social-network/worker.ts
- packages/maskbook/src/utils/debug/ui.ts
- packages/maskbook/src/utils/native-rpc/Web.ts
> feat: load minimal code in content script if no SNS Adaptor started

- packages/maskbook/src/extension/options-page/DashboardDialogs/Persona/Import.tsx
> fix:  Overlap in "Import Your Persona" dialog

- packages/maskbook/src/_locales/en/messages.json
- packages/maskbook/src/_locales/ja/messages.json
- packages/maskbook/src/_locales/ko/messages.json
- packages/maskbook/src/_locales/zh/messages.json
- packages/maskbook/src/web3/UI/EthereumWalletConnectedBoundary.tsx
> refactor: updating gas fee

- packages/dashboard/src/initialization/Dashboard.tsx
- packages/dashboard/src/pages/Personas/api.ts
- packages/maskbook/src/extension/background-script/SettingsService.ts
- packages/maskbook/src/extension/service.ts
- packages/theme/src/theme.ts
> feat: able to reflect the theme settings in new dashboard

- packages/maskbook/src/_locales/en/messages.json
> fix: fill empty locale field

- packages/maskbook/src/plugins/Collectible/constants.ts
- packages/maskbook/src/plugins/Collectible/hooks/useAsset.ts
- packages/maskbook/src/plugins/Collectible/types/rarible.ts
> fix(collectible): nft from raible

- packages/maskbook/src/plugins/Collectible/UI/ListingByPriceCard.tsx
> fix: add missing expiration date when enable including ending price

- packages/maskbook/src/plugins/Collectible/UI/ListingByHighestBidCard.tsx
- packages/maskbook/src/plugins/Collectible/UI/ListingByPriceCard.tsx
- packages/maskbook/src/plugins/Collectible/UI/MakeOfferDialog.tsx
> fix(Collectible): make datetime input fullWidth

- packages/maskbook/src/plugins/Gitcoin/UI/DonateDialog.tsx
- packages/maskbook/src/plugins/Trader/UI/trending/SearchResultView.tsx
> fix: clear eslint warnings

- packages/maskbook/src/components/InjectedComponents/ToolboxHint.tsx
> fix: wrap chainstate provider

- packages/maskbook/src/components/InjectedComponents/DecryptedPost/DecryptedPost.tsx
- packages/maskbook/src/components/InjectedComponents/PostComments.tsx
- packages/maskbook/src/components/InjectedComponents/PostInspector.tsx
- packages/maskbook/src/extension/background-script/CryptoServices/decryptFrom.ts
- packages/maskbook/src/social-network/defaults/inject/CommentBox.tsx
- packages/maskbook/src/social-network/defaults/inject/PostInspector.tsx
- packages/plugin-infra/src/PostInfo.ts
> refactor: remove deprecated fields in postinfo

- docs/caveats.md
> docs: update note about react devtools

- .circleci/config.yml
https://app.circleci.com/pipelines/github/DimensionDev/Maskbook/11406/workflows/f834b688-f198-46ed-9fa6-87ef56f9d8be/jobs/27659
> chore: resolve postinstall failure with pnpm@6.4.0

- packages/dashboard/.storybook/main.js
> fix: disable reactDocgen

- packages/maskbook/src/plugins/RedPacket/hooks/useCreateCallback.ts
> fix: estimate gas erorr

- packages/maskbook/src/plugins/Collectible/UI/Collectible.tsx
closes #3196
from https://github.com/DimensionDev/Maskbook/issues/3196#issuecomment-854309370
> fix: collectible listing wrap issue

- packages/cli/locale-kit/utils.ts
> fix: locale-kit should only resolve directory as locale name

- packages/maskbook/src/plugins/Collectible/UI/ArticleTab.tsx
> feat(plugins/Collectible): support previewing video NFT

- packages/maskbook/src/_locales/en/messages.json
- packages/maskbook/src/_locales/ja/messages.json
- packages/maskbook/src/_locales/ko/messages.json
- packages/maskbook/src/_locales/zh/messages.json
- packages/maskbook/src/plugins/ITO/UI/ExchangeTokenPanel.tsx
- packages/maskbook/src/web3/UI/TokenAmountPanel.tsx
> fix(plugins/ITO): if no token selected, info that with placeholder

- package.json
- packages/maskbook/src/utils/type-transform/BackupFormat/JSON/DBRecord-JSON/PostRecord.ts
- packages/theme/.storybook/main.js
- pnpm-lock.yaml
> fix: disable reactDocgen and fix lint warnings

- packages/shared/src/utils/number.ts
> chore: isZero fastpath

- packages/maskbook/package.json
- pnpm-lock.yaml
Related: ef1e87aeb2c7aa017458a07a5a3ea842f2106aab
> chore: remove 'react-docgen-typescript-loader'

- packages/cli/locale-kit/locale-kit.ts
> fix: remove duplicated code

- packages/web3-shared/src/assets/chains.json
> feat: update polygon explorer url

- packages/icons/general/Search.tsx
> fix: incorrect import path

- packages/icons/general/Search.tsx
- packages/maskbook/miscs/package-overrides/xhr2-cookies.js
- packages/maskbook/package.json
- packages/maskbook/webpack.config.ts
- pnpm-lock.yaml
- Revert "fix: incorrect import path (#3333)"
- fix: runtime error
closes #
> fix: netlify

- packages/maskbook/src/plugins/Collectible/UI/ListingByHighestBidCard.tsx
- packages/maskbook/src/plugins/Collectible/UI/ListingByPriceCard.tsx
- packages/maskbook/src/plugins/Collectible/UI/MakeOfferDialog.tsx
- packages/maskbook/src/plugins/ITO/UI/CreateForm.tsx
- packages/maskbook/src/web3/UI/DateTimePanel.tsx
> feat: add min/max to DateTimePanel to control min/max of datetime input

- packages/maskbook/src/_locales/zh/messages.json
> fix: chinese typo

- packages/dashboard/public/index.html
- packages/maskbook/miscs/template.html
> chore: dns prefetch

- packages/maskbook/src/plugins/dHEDGE/UI/Icon.tsx
- packages/maskbook/src/plugins/dHEDGE/define.tsx
- packages/maskbook/src/plugins/types.ts
- packages/maskbook/src/resources/DHEDGEIcon.tsx
> fix: add dHEDGE icon

- packages/maskbook/src/plugins/RedPacket/UI/RedPacketForm.tsx
Fix https://mask.atlassian.net/browse/MASK-40
> fix: rp detect switch chain

- packages/maskbook/src/plugins/Wallet/hooks/useAssetsMerged.ts
> fix: unsupported chain crash

- packages/maskbook/src/plugins/RedPacket/UI/RedPacketDialog.tsx
> chore: rp sign password

- packages/maskbook/src/plugins/Snapshot/UI/VotesCard.tsx
- packages/maskbook/src/plugins/Snapshot/hooks/useVotes.ts
- packages/maskbook/src/plugins/Snapshot/types.ts
> fix: snapshot api break change

- packages/maskbook/src/plugins/Trader/constants/balancer.ts
- packages/maskbook/src/plugins/dHEDGE/UI/PoolStats.tsx
> chore: simplify bignumber

- packages/shared/src/wallet/formatter.tsx
> fix: incorrect numeric format in tradeview

- packages/maskbook/src/extension/options-page/DashboardComponents/Drawer.tsx
> chore: update comment

- packages/maskbook/src/_locales/README.md
> chore: improve locales readme

- packages/maskbook/src/extension/options-page/DashboardComponents/TokenIcon.tsx
- packages/maskbook/src/extension/options-page/DashboardComponents/TokenIconSpeialIconList.json
> chore: move special icon list to json file

- packages/maskbook/src/_locales/en/messages.json
- packages/maskbook/src/_locales/ja/messages.json
- packages/maskbook/src/_locales/ko/messages.json
- packages/maskbook/src/_locales/zh/messages.json
- packages/maskbook/src/plugins/RedPacket/UI/RedPacket.tsx
> fix: rp show claimed amount

- packages/maskbook/src/plugins/ITO/UI/CompositionDialog.tsx
- packages/maskbook/src/plugins/ITO/UI/ConfirmDialog.tsx
- packages/maskbook/src/web3/UI/TxFeeEstimation.tsx
Reset gas price after closed tx confirm dialog or sent the tx.
@AinuX Please test it.
> fix: reset gas price

- packages/contracts/types/HappyRedPacketV1.d.ts
- packages/contracts/types/HappyRedPacketV2.d.ts
- packages/maskbook/src/plugins/RedPacket/hooks/useClaimCallback.ts
- packages/maskbook/src/plugins/RedPacket/hooks/useCreateCallback.ts
- packages/maskbook/src/plugins/RedPacket/hooks/useRefundCallback.ts
- packages/maskbook/src/plugins/dHEDGE/hooks/useInvestCallback.ts
> refactor: recompile red packet abis

- packages/maskbook/src/plugins/RedPacket/UI/RedPacket.tsx
- packages/maskbook/src/plugins/RedPacket/contracts/useRedPacketContract.ts
> fix: rp version type

- packages/maskbook/src/components/DataSource/usePostInfo.ts
- packages/maskbook/src/components/InjectedComponents/DecryptedPost/DecryptedPost.tsx
- packages/maskbook/src/components/InjectedComponents/DecryptedPost/DecryptedPostDebug.tsx
- packages/maskbook/src/components/InjectedComponents/PostComments.tsx
- packages/maskbook/src/components/InjectedComponents/PostInspector.tsx
- packages/maskbook/src/components/InjectedComponents/PostReplacer.tsx
- packages/maskbook/src/plugins/Collectible/define.tsx
- packages/maskbook/src/plugins/Gitcoin/define.tsx
- packages/maskbook/src/plugins/NFT/define.tsx
- packages/maskbook/src/plugins/RedPacket/UI/RedPacketInPost.tsx
- packages/maskbook/src/plugins/Snapshot/define.tsx
- packages/maskbook/src/plugins/VCent/define.tsx
- packages/maskbook/src/plugins/dHEDGE/define.tsx
- packages/maskbook/src/social-network/defaults/inject/CommentBox.tsx
- packages/plugin-infra/src/PostInfo.ts
> refactor: let usePostInfoDetails support reference (#3422)

- packages/maskbook/src/plugins/ITO/UI/CompositionDialog.tsx
> fix: ito configured data will not be cleared after close ITO dialog

- .github/workflows/build.yml
- .github/workflows/e2e.yml
- .github/workflows/linters.yml
> ci: add develop branch

- packages/maskbook/src/extension/options-page/DashboardDialogs/Persona/Create.tsx
- packages/maskbook/src/extension/options-page/DashboardRouters/Setup.tsx
- packages/maskbook/src/utils/constants.ts
> fix: user can create persona by more than 24 characters

- packages/maskbook/src/plugins/ITO/UI/CompositionDialog.tsx
> fix: clear poolSettings crash

- packages/maskbook/src/extension/background-script/EthereumServices/wallet.ts
- packages/maskbook/src/extension/options-page/DashboardComponents/FixedTokenList.tsx
- packages/maskbook/src/extension/options-page/DashboardComponents/TokenInList.tsx
- packages/maskbook/src/extension/options-page/DashboardComponents/WalletAssetsTable.tsx
- packages/maskbook/src/plugins/Collectible/hooks/useAsset.ts
- packages/maskbook/src/plugins/ITO/UI/SwapDialog.tsx
- packages/maskbook/src/plugins/ITO/hooks/useSwapCallback.ts
- packages/maskbook/src/plugins/Wallet/services/wallet.ts
- packages/maskbook/src/web3/hooks/useERC20TokensDetailedFromTokenLists.ts
- packages/web3-shared/src/hooks/useWallet.ts
- packages/web3-shared/src/hooks/useWallets.ts
- packages/web3-shared/src/utils/index.ts
> chore: simplify same address

- packages/web3-shared/src/hooks/useConstant.ts
- packages/web3-shared/src/pipes/index.ts
- packages/web3-shared/src/utils/index.ts
should not import from any business-related module
> fix(web3-shared): circular dependencies

- packages/maskbook/src/extension/options-page/DashboardComponents/TokenIcon.tsx
- packages/maskbook/src/plugins/ITO/apis/index.ts
- packages/maskbook/src/plugins/Trader/apis/LBP/index.ts
- packages/maskbook/src/plugins/Trader/apis/balancer/index.ts
- packages/maskbook/src/plugins/Trader/apis/blocks/index.ts
- packages/maskbook/src/plugins/Trader/apis/uniswap-health/index.ts
- packages/maskbook/src/plugins/Trader/apis/uniswap-v2-subgraph/index.ts
- packages/maskbook/src/plugins/Trader/trader/useTradeContext.ts
- packages/maskbook/src/plugins/Wallet/services/assets.ts
- packages/web3-shared/src/utils/index.ts
> chore: remove `getConstant`

- packages/maskbook/src/plugins/Trader/apis/trending/index.ts
> fix: hide uniswap info if non-ethereum network was selected

- packages/maskbook/src/plugins/Trader/apis/trending/index.ts
- packages/maskbook/src/plugins/Trader/trending/useAvailableDataProviders.ts
- packages/maskbook/src/plugins/Trader/trending/useAvailableTraderProviders.ts
> fix: react to chain id 

- packages/maskbook/src/extension/background-script/EthereumServices/tokenList.ts
- packages/web3-shared/src/pipes/index.ts
- packages/web3-shared/src/utils/index.ts
> chore: simplify chain id

- docs/npm-scope.md
> chore: add npm scope documentation

- packages/maskbook/src/utils/hooks/useImageFailover.ts
> fix: New token selected in ITO shows incorrect icon

- packages/contracts/package.json
- packages/icons/package.json
- packages/plugins/example/package.json
> chore: reorder package json

- packages/dashboard/src/components/DashboardFrame/Navigation.tsx
use `insert` prop for ListItemText
> fix: navigation submenu `nested` error

- packages/maskbook/src/plugins/RedPacket/constants.ts
> chore: clean warnings

- .github/workflows/linters.yml
> chore(CI): zero tolerance on linting warings

- packages/maskbook/src/extension/options-page/DashboardDialogs/Wallet/Import.tsx
- packages/maskbook/src/utils/utils.ts
> fix: creation button can't be enabled in ImportWallet dialog

- .github/auto_assign.yml
- .github/stale.yml
> chore: update github bot configuration

- packages/dashboard/src/pages/Wallets/components/TokenTableRow/index.tsx
- packages/maskbook/src/extension/options-page/DashboardDialogs/Persona/Create.tsx
- packages/maskbook/src/extension/options-page/DashboardDialogs/Plugin.tsx
- packages/maskbook/src/extension/options-page/DashboardRouters/Setup.tsx
- packages/maskbook/src/plugins/ITO/define.tsx
- packages/maskbook/src/plugins/RedPacket/SNSAdaptor/RedPacket.tsx
- packages/maskbook/src/plugins/Trader/UI/trending/CoinMetadataTags.tsx
- packages/maskbook/src/social-network-adaptor/minds.com/injection/PostDialogHint.tsx
> chore: clean jsx

- packages/maskbook/src/database/helpers/avatar.ts
- packages/maskbook/src/plugins/Wallet/apis/gasnow.ts
- packages/maskbook/src/utils/hooks/useQRCodeImageScan.tsx
- packages/maskbook/src/utils/hooks/useQueryNavigatorPermission.ts
> chore: clean event bound

- packages/maskbook/src/utils/hooks/useQueryNavigatorPermission.ts
> refactor: useQueryNavigatorPermission

- packages/dashboard/package.json
- packages/dashboard/src/components/FileUpload/index.tsx
- packages/maskbook/package.json
- packages/maskbook/src/database/helpers/avatar.ts
- packages/maskbook/src/extension/options-page/DashboardComponents/RestoreFromBackupBox.tsx
- packages/maskbook/src/extension/options-page/DashboardComponents/RestoreFromQRCodeImageBox.tsx
- pnpm-lock.yaml
closes #
https://github.com/DimensionDev/kit/commit/886532bfaaf28e0eebc3461b2c1964a39c731319
> chore: clean file reader

- packages/shared/package.json
- packages/shared/src/hooks/useSnackbarCallback.tsx
- packages/theme/package.json
- pnpm-lock.yaml
closes #Jira-82
**Snackbar** as common component in theme.
**useSnackbarCallback** as share hook in shared package ant it depend on i18n.
> fix: add notistack for theme

- .github/workflows/bot.yml
see https://github.com/marketplace/actions/auto-label-merge-conflicts
> chore: github bot auto add conflict label to pr

- .github/workflows/bot.yml
> chore: set gh-actions name

- packages/maskbook/src/plugins/FileService/SNSAdaptor/MainDialog.tsx
- packages/maskbook/src/plugins/FileService/SNSAdaptor/index.tsx
> chore: simplify file service entry

- packages/maskbook/src/plugins/Transak/SNSAdaptor/index.tsx
> fix: transak should not available in the composition dialog
